-- require("map/level")

local musttasks =
{
	"DesertIsland",
	"DoydoyIslandGirl",
	"DoydoyIslandBoy",
	"IslandCasino",
	"PirateBounty",
	"ShellingOut",
	"JungleMarsh",
	"IslandMangroveOxBoon",
	"SharkHome",
	"IslandOasis",
	-- "VolcanoIsland",
}

local cantasks =
{
	"BeachBothJungles",
	"IslandParadise",
	"Cranium",
	"BeachJingleS",
	"BeachSavanna",
	"GreentipA",
	"GreentipB",
	"HalfGreen",
	"BeachRockyland",
	"LotsaGrass",
	"CrashZone",
	"BeachJungleD",
	"AllBeige",
	"BeachMarsh",
	"Verdant",
	"Vert",
	"VerdantMost",
	"Florida Timeshare",
	"PiggyParadise",
	"BeachPalmForest",
	"IslandJungleShroomin",
	"IslandJungleNoFlowers", 
	"IslandBeachGrassy",
	"IslandBeachRocky",
	"IslandBeachSpider",
	"IslandBeachNoCrabbits",
	"JungleSRockyland",
	"JungleSSavanna",
	"JungleBeige",
	"Spiderland",
	"IslandJungleBamboozled",
	"IslandJungleNoBerry",
	"IslandBeachDunes",
	"IslandBeachSappy",
	"IslandBeachNoLimpets",
	"JungleDense",
	"JungleDMarsh",
	"JungleDRockyland",
	"JungleDRockyMarsh",
	"JungleDSavanna",
	"JungleDSavRock",
	"ThemeMarshCity",
	"IslandJungleCritterCrunch",
	"IslandRockyTallJungle",
	"IslandBeachNoFlowers",
	"NoGreen A",
	"KelpForest",
	"GreatShoal",
	"BarrierReef",
	"HotNSticky",
	"Marshy",
	"Rockyland",
	"IslandJungleMonkeyHell",
	"IslandJungleSkeleton",
	"FullofBees",
	"IslandJungleRockyDrop",
	"IslandJungleEvilFlowers",
	"IslandBeachCrabTown",
	"IslandBeachForest",
	"IslandJungleNoRock",
	"IslandJungleNoMushroom",
	"NoGreen B",
	"Savanna",
	"IslandBeachLimpety",
	"IslandMeadowBees",
	"IslandRockyGold",
	"IslandRockyTallBeach",
	"IslandMeadowCarroty",
}

return {musttasks, cantasks}