return {
ACTIONSFAIL = {
	REPAIRBOAT =
	{
		GENERIC = "My vessel is renewed!",
	},
},
ANNOUNCE_MAGIC_FAIL = "Its magicks have weakened!",
ANNOUNCE_OTHER_WORLD_PLANT = "Such a plant could never thrive in this realm!",

ANNOUNCE_BOAT_DAMAGED = "My vessel is wounded!",
ANNOUNCE_BOAT_SINKING = "The sea pulls me toward Hel!",
ANNOUNCE_BOAT_SINKING_IMMINENT = "These black depths will soon claim me!",
ANNOUNCE_CRAB_ESCAPE = "It has vanished!",
ANNOUNCE_MAPWRAP_LOSECONTROL = "The currents are my master!",
ANNOUNCE_MAPWRAP_RETURN = "I hath emerged from the fog!",
ANNOUNCE_MAPWRAP_WARN = "I hath reached the edges of the world!",
ANNOUNCE_MORETREASURE = "I am smiled upon this day!",
ANNOUNCE_OTHER_WORLD_TREASURE = "This map describes another land.",
ANNOUNCE_SHARX = "Foes from the froth!",
ANNOUNCE_TRAWL_FULL = "My net has been filled with a marvelous bounty.",
ANNOUNCE_TREASURE = "The map tells of treasure!",
ANNOUNCE_VOLCANO_ERUPT = "Is Ragnarok upon me?!",
ANNOUNCE_WAVE_BOOST = "Carry me forth!",
ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "A beast lurks beneath the waves...",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "I have lost the beast's trail...",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "I cannot read these rough waters...",
DESCRIBE = {

		-- PORTABLECOOKPOT_ITEM = "Cooking, a noble profession.",
	    CHEFPACK = "The companion of a wise chef.",
	    -- PORTABLECOOKPOT = 
	    -- {
			-- COOKING_LONG = "The chef's culinary patience is beyond my own.",
			-- COOKING_SHORT = "I can smell the victorious stench of fresh food coming!",
			-- DONE = "This refined pot cooks the mightiest meals!",
			-- EMPTY = "Nothing in there. Where's the chef!",
        -- },
	    -- WARLY = 
        -- {
	        -- GENERIC = "Good health and cooking to you, %s!",
	        -- ATTACKER = "Your honor wavers, %s.",
	        -- MURDERER = "May we meet again in Valhalla!",
	        -- REVIVER = "%s has Andhrímnir's blessing.",
	        -- GHOST = "Meditate on Andhrímnir's blessings, %s. I'll find a heart..",
	        -- FIRESTARTER = "Have you misplaced your cooking pot, %s?",
        -- },
	    --

		SEAWEED_STALK = "I have no use for it!", --copied from the Wikia because I couldn't find it in the game files. -M

		LEIF_PALM = "To arms!", --"That is an ancient woodland being."
		BIGFISHINGROD = "I will ensnare delicious fish meat.",
		COFFEEBOT = "The best machine under the sun.",
		DEPLETED_GRASS_WATER = "It is thoroughly vanquished.",
		INVENTORYGRAVE = "I will see thee in Valhalla!",
		INVENTORYMOUND = "I will see thee in Valhalla!",
		LIMPETS_COOKED = "Let us feast!",
		BOAT_WOODLEGS = "I would prefer a longship.",
		WOODLEGSHAT = "Pales in comparison to my helm.",
		SAIL_WOODLEGS = "A fearsome sheet.",
		SOLOFISH_DEAD = "Rest easy in Valhalla.",
		FISH_MED_COOKED = "Joy!",
        GHOST_SAILOR = "He must have been a valiant warrior.",
		PALMLEAF_UMBRELLA = "I dislike plants, but I dislike wet armor more.",
		-- BANANAPOP = "I've somehow found a way to make it even LESS appealing!",
		BISQUE = "Not a bad dish.",
		-- CEVICHE = "Fancy for my taste, but it'll do.",
		SEAFOODGUMBO = "A meal fit for a queen.",
		SURFNTURF = "Yuck! Turf!",
		SHARKFINSOUP = "Delicious!",
		LOBSTERDINNER = "I triumphed over my wobster foe.",
		LOBSTERBISQUE = "That's more like it.",
		JELLYOPOP = "I could go berserk on these!",
		CALIFORNIAROLL = "That's just a morsel of fish food.",
		AERODYNAMICHAT = "My head shall cut the air!",
		ANTIVENOM = "No venom shall flow through my veins!",
		ARMOR_LIFEJACKET = "Adventure offers no true safety!",
		ARMOR_SNAKESKIN = "Rain is bested!",
		ARMOR_WINDBREAKER = "I shall break the wind with every step!",
		ARMORLIMESTONE = "It's heft is reassuring on my bones.",
		ARMOROBSIDIAN = "Come at me now, fiends!",
		ARMORSEASHELL = "I shall not wash up on the shores of Valhalla wearing this!",
		BOAT_ARMOURED = "Now this is a vessel fit for a Viking!",
		BABYOX = "When you grow up you will become even more meat, meat.",
		BALLPHIN = "A blow struck may simply bounce off.",
		BALLPHINPOD = "A raiding party!",
		BAMBOO = "Sticks of great versatility.",
		BAMBOOTREE = "A very hearty weed.",
		BERMUDATRIANGLE = "Is this a plaything of Loki?",
		BIOLUMINESCENCE = "What magic is this?",
		BLOWDART_POISON = "To weaken from a distance. Odin forgive me...",
		BOAT_INDICATOR = "I shall launch my craft.",
		BOAT_LANTERN = "See me, foul beasts of the shadow seas!",
		BOATCANNON = "It smites mine enemies for me!?",
		BOATREPAIRKIT = "Most sensible cargo.",
		BOTTLELANTERN = "A most curious torch.",
		BURIEDTREASURE = "May luck smile on me this day.",
		SNAKEDEN = "You skulking wretch!",
		CANNONSHOT = "Sound and fury!",
		CAPTAINHAT = "It would be better with horns.",
		BOAT_CARGO = "A boat fit for a long journey.",
		CHIMINEA = "What kind of fire hides in a hole?",
		CIRCLINGSEAGULL = "Sky filth!",
		SAIL_CLOTH = "A fine sail.",
		COCONADE = "Fire that can be thrown.",
		COCONUT = "The hardest of fruits.",
		COCONUT_SAPLING = "The hard fruit gave way to a flimsy tree.",
		COFFEE = "Bitter and pulse-pounding.",
		COFFEEBEANS = "I take mine black.",
		
		COFFEEBUSH = "Just add water?",
		CORAL = "The sea bequeaths such strange gifts.",
		ROCK_CORAL = "A hard and brittle place. I like it.",
		CRAB = "Your armor cannot protect you, meat!",
		CRABHOLE = "Does shame drive them to this hole?",
		CUTLASS = "Oh, great sword of piscean death. I shall swing you with honor.",
		SWORDFISH_DEAD = "Onward to Valhalla, brave fish.",
		DEPLETED_BAMBOOTREE = "Have some respect for yourself.",
		DEPLETED_BUSH_VINE = "Not so viney now are you?",
		DOYDOY = "It shows no trace of fear for me!",
		DOYDOYBABY = "I honor you, young warrior of the DoyDoys.",
		DOYDOYEGG = "Within this egg grows a Viking of another feather.",
		
		DOYDOYFEATHER = "The treasured feather of a fallen bird warrior.",
		DOYDOYNEST = "The nest where more brave ones will hatch!",
		DUBLOON = "The spoils of the fallen!",
		DUG_BAMBOOTREE = "If I plant you, will you repay me?",
		DUG_BERRYBUSH2 = "My own personal fount of berries!",
		DUG_BUSH_VINE = "To vine or not to vine?",
		DUG_COFFEEBUSH = "Coffee to go.",
		EARRING = "This is not of my ear.",
		FABRIC = "Sewing is not warrior's work...",
		SAIL_FEATHER = "The brave birds gift me their swift feathers!",
		FIRERAIN = "True warrior's weather!",
		FIRERAINSHADOW = "By Odin!",
		FISHINHOLE = "Do you wish to surrender, fish?",
		FROG_POISON = "Back, foul reptilian scourge!",
		GASHAT = "Armor of sorts for my nose and throat!",
		GOLDENMACHETE = "I shall swing you with pride.",
		ICEMAKER = "Reminds me of home.",
		IRONWIND = "This contraption runs on Odin's steeds!",
		JELLYFISH = "You are much too small to be a sea monster.",
		JELLYFISH_COOKED = "The sea monster cooks up well!",
		JELLYFISH_DEAD = "The sea monster rides to Valhalla!",
		JELLYFISH_PLANTED = "I expected sea monsters to be bigger.",
		JELLYJERKY = "My teeth shall do battle with you.",
		LAVAPOOL = "A puddle of fire!",
		LIMESTONENUGGET = "Hard as an unripe fruit.",
		LIMPETS = "Rock meat!",
		
		LOBSTER = "You are dressed for battle, sea-dweller.",
		LOBSTERHOLE = "The armored ones dwell here...",
		BOAT_LOGRAFT = "You will not carry me far, but you will carry me.",
		MACHETE = "A fine length of blade.",
		MESSAGEBOTTLE = "A message from Valhalla?",
		MESSAGEBOTTLEEMPTY = "Empty of both messages and drink. Pity.",
		MOSQUITO_POISON = "Poison! The work of a coward!",
		MUSSEL = "You don't look strong.",
		MUSSEL_STICK = "The foolish mussels shall climb this stick.",
		OBSIDIAN = "Pebbles from the fire mountain!",
		OBSIDIAN_WORKBENCH = "Fire forge!",
		OBSIDIANAXE = "Now THIS is an axe!",
		OBSIDIANCOCONADE = "Throwing fire is the coward's way. But such fun!",
		OBSIDIANFIREPIT =
		{
			EMBERS = "The fire's nearly dead.",
			GENERIC = "A fire fit for a Viking!",
			HIGH = "The fire roars!",
			LOW = "The fire's slowly dying.",
			NORMAL = "Warm fire, warm Wigfrid.",
			OUT = "And the light flickers out.",
		},
		OBSIDIANMACHETE = "A tool for cutting. A tool for burning.",
		SPEAR_OBSIDIAN = "Feel the burn.",
		OBSIDIANSPEARGUN = "I normally prefer to set fires up close.",
		OX = "Praise Odin for this bountiful hoofed feast!",
		PACKIM = "Will you follow me to Valhalla?",
		PACKIM_FISHBONE = "A curious bauble.",
		PALMLEAF = "A Viking-sized leaf!",
		PALMTREE =
		{
			BURNING = "The wood's ablaze!",
			BURNT = "Loge took that one.",
			CHOPPED = "Chopped by the warrior of the woods!",
			GENERIC = "Do you forsake branches, tree?",
		},
		PALMTREE_BURNT = "I smell burnt coconut.",
		PALMTREE_STUMP = "You will be fueling my hearth in Valhalla.",
		PARROT = "Hold your tongue, bird!",
		PEACOCK = "It will be a shame to ruin those feathers, meat.",
		PIRATEHAT = "This hat confuses my character... I mean, my soul.",
		PIRATIHATITATOR = "This contraption has the smell of Loki about it...",
		POISONHOLE = "The ground belches with sickness!",
		BOAT_RAFT = "A Viking fears not dampness!",
		BOAT_ROW = "Rowing is in my blood.",
		SAIL_PALMLEAF = "A curious sail, but it shall do.",
		SAND = "You are a very clean dirt.",
		SANDCASTLE = "A scale model of my future keep.",
		SANDBAG = "Bagged sand.",
		SANDBAG_ITEM = "Keeps the floods at bay.",
		SANDDUNE = "I will not make a mountain out of a sandhill.",
		SEAGULL = "Vile bird!",
		SEAGULL_WATER = "You foul the water you float upon!",
		SEASACK = "Disgusting, but useful in its way.",
		SEASHELL = "The currency of the sea.",
		SEASHELL_BEACHED = "A tiny elf shield?",
		SEATRAP = "Bring me spoils of the sea!",
		SEAWEED = "Watery plant filth!",
		
		SEAWEED_PLANTED = "A weed I cannot crush under my boot.",
		SHARK_FIN = "A token from a fallen warrior.",
		SHARX = "Ah, a worthy sea opponent!",
		SLOTMACHINE = "A machine of fate and misery.",
		SNAKE = "Never trust those who slither.",
		SNAKE_FIRE = "They speak with the volcano's mouth!",
		SNAKE_POISON = "Keep your foul fangs from my hide!",
		SNAKESKIN = "A snake has slipped its skin. With a little help...",
		SNAKESKINHAT = "Shall I wear the serpent?",
		SOLOFISH = "It seems the sea is offering me a feast.",
		SPEAR_POISON = "This spear awards a coward's victory.",
		SPEARGUN = "A coward's weapon.",
		SPEARGUN_POISON = "I am not some sneak hiding in the shadows! Am I?",
		SPOILED_FISH = "You smell of your failure.",
		STUNGRAY = "Have you no honor, stinky ones?",
		SUPERTELESCOPE = "Odin has lent me his eye!",
		SWORDFISH = "Now you are a fish after my heart!",
		TELESCOPE = "What trickery is this?",
		TIGERSHARK = "Take me to Valhalla, devil of the sea!",
		TIGERSHARKSHADOW = "The shadow of the beast!",
		TORNADO = "The wind has taken furious form!",
		TOUCAN = "Fight with me, long-nosed bird! Together we shall dine in Valhalla!",
		TRAWLNET = "I shall ransack the sea!",
		TRAWLNETDROPPED = "And now to see about my loot!",
		TRIDENT = "A weapon fit for a god!",
		TRINKET_IA_13 = "What foul mead is this?",
		TRINKET_IA_14 = "The toy of a babe. Or is it?",
		TRINKET_IA_15 = "A weapon of annoyance.",
		TRINKET_IA_16 = "A piece of armor?",
		TRINKET_IA_17 = "A warrior walks to Valhalla barefoot...",
		TRINKET_IA_18 = "I don't recognize the craftsmanship.",
		TRINKET_IA_19 = "It is always clear skies for a righteous warrior.",
		TURBINE_BLADES = "What sort of strange sword is this?",
		TURF_BEACH = "Feels good between my toes.",
		TURF_JUNGLE = "You could lose yourself in this...",
		TWISTER = "You hide beneath wind, villain!",
		VENOMGLAND = "The source of the fevers.",
		VINE = "What can you do for me?",
		VOLCANO = "A mountain of fire!",
		VOLCANO_ALTAR = "I must appease the fire god that lives inside this mountain.",
		VOLCANO_ALTAR_BROKEN = "Senseless destruction of a weapon forge...",
		VOLCANO_EXIT = "I weary of this infernal realm.",
		VOLCANOSTAFF = "Call down the wrath of fire mountain!",
		WALL_LIMESTONE = "Fine work.",
		WALL_LIMESTONE_ITEM = "Will you stand with me?",
		WHALE_BLUE = "I will end your moping, giant!",
		WHALE_CARCASS_BLUE = "I will toast you in Valhalla.",
		WHALE_CARCASS_WHITE = "Oh, how the mighty stink.",
		WHALE_WHITE = "It would be an honor to kill you.",
		NEEDLESPEAR = "Tis truly a wondrous war lance!",
		ARMORCACTUS = "It will make of me a friend to the cactus.",
		BAMBOOTREE =
		{
			BURNT = "Your hollow sorcery could not save you from fire.",
			CHOPPED = "You could not hack it!",
			GENERIC = "What sorcery is this? Wood that is hollow?",
		},
		BLOWDART_FLUP = "A coward's weapon, dropped by a pitiful, sneaking creature.",
		BLUBBER = "This is much prized by my people!",
		BLUBBERSUIT = "Rue my suit of fat, moisture!",
		BOAT_TORCH = "The night sea is alight!",
		BRAINJELLYHAT = "My brain has the might of my sword!",
		BUOY = "It buoys my spirits to see it above the waves.",
		BUSH_VINE =
		{
			BURNT = "It's burnt. No sense vine-ing about it.",
			CHOPPED = "It needed a haircut.",
			GENERIC = "This bush has helm head.",
		},
		COCONADE =
		{
			BURNING = "The nut will spew its fire soon!",
			GENERIC = "This is no ordinary nut!",
		},
		COCONUT_COOKED = "I shall feast on this large nut.",
		COCONUT_HALVED = "I have cleaved the nut and it has shown me its insides!",
		COFFEEBEANS_COOKED = "It smells energizing.",
		COFFEEBUSH =
		{
			BARREN = "Did you even put up a fight?",
			GENERIC = "It bears strange volcano fruits.",
			PICKED = "Its fruits must be reborn.",
			WITHERED = "Weakling bush!",
		},
		CORAL_BRAIN = "If I eat of it will I gain its knowledge?",
		CORAL_BRAIN_ROCK = "A mystical, all-knowing water rock!",
		CRAB =
		{
			GENERIC = "Do battle with me, armored one!",
			HIDDEN = "Un-bury thyself, coward!",
		},
		CRATE = "Yield your secrets, box!",
		DOUBLE_UMBRELLAHAT = "What kind of strange helm is this?",
		DOYDOYEGG_COOKED = "I shall eat of this fearless bird's bounty.",
		DOYDOYEGG_CRACKED = "Its fearlessness leaks out.",
		DRAGOON = "A fellow berserker whose belly is full of fire!",
		DRAGOONDEN = "A berserker has to live somewhere.",
		DRAGOONEGG = "I can hear the beating heart of a warrior within!",
		DRAGOONHEART = "My fallen foe has given me a gift!",
		DRAGOONSPIT = "I wish I could spit fire...",
		DUG_ELEPHANTCACTUS = "I shall get to the point. You belong to me now.",
		ELEPHANTCACTUS = "I sense the spirit of a berserker within you, plant.",
		ELEPHANTCACTUS_ACTIVE = "Finally the earth sprouts a worthy adversary!",
		ELEPHANTCACTUS_STUMP = "Coward!",
		FISH_MED = "This sea meat will serve me well.",
		FISH_SMALL = "This sea meat will serve me well.",
		FISH_SMALL_COOKED = "This meat will swim in my belly!",
		FLAMEGEYSER = "The ground belches fire!",
		FLOTSAM = "I must fish it from the sea if I'm to learn its secrets.",
		FLUP = "You cowardly mudlurker!",
		-- FRESHFRUITCREPES = "So light and airy!",
		GRASS_WATER = "Grass I can pick from my longship!",
		HAIL_ICE = "The sky is throwing ice!",
		ICEMAKER =
		{
			HIGH = "The machine is fired up!",
			LOW = "It is spitting considerably less ice forth.",
			NORMAL = "Ice from fire!",
			OUT = "It needs more fire!",
			VERYLOW = "Its fire is about to go out.",
		},
		-- JUNGLETREE = "A mighty tree!",
		-- JUNGLETREE_BURNT = "Goodbye, giant.",
		-- JUNGLETREE_STUMP = "I will see you in Valhalla, tree.",
		JUNGLETREESEED = "The strength of the tree, in a seed.",
        JUNGLETREESEED_SAPLING = "It will grow mightily.",
		JUNGLETREE =
		{
			BURNING = "The tree burns.",
			BURNT = "The tree is no more.",
			CHOPPED = "A strong tree, but not so strong as my axe.",
			GENERIC = "There are no trees like this where I sail from.",
		},
		KNIGHTBOAT = "My longship speeds me to war!",
		KRAKEN = "I'll return you to Hel herself!",
		KRAKENCHEST = "Spoils of war!",
		KRAKEN_TENTACLE = "The arm of the beast!",
		ROCK_LIMPET =
		{
			GENERIC = "The meat stone!",
			PICKED = "The stone is meatless for now...",
		},
		TROPICALFAN = "The luxuries of camp, on the go.",
		LIVINGJUNGLETREE = "I do not like your face, tree!",
		LOBSTER_DEAD = "Sleep in Valhalla, armored one.",
		LOBSTER_DEAD_COOKED = "Your armor hides tasty meat.",
		LUGGAGECHEST = "I hope I am spoiled by these spoils of the sea!",
		MAGIC_SEAL = "I shall wield this with proper respect for the mighty warrior wizard that left it.",
		MAGMAROCK = "What can I use to roll these rocks?",
		MAGMAROCK_FULL = "What can I use to roll these rocks?",
		MAGMAROCK_GOLD = "It shimmers...",
		MAGMAROCK_GOLD_FULL = "It shimmers...",
		MANGROVETREE = "I have never felled a tree from my longship before!",
		MANGROVETREE_BURNT = "Everything above the water is char.",
		MARSH_PLANT_TROPICAL = "A meager plant.",
		MERMFISHER = "I quarrel not with fisherfolk, so long as they do not take up arms.",
		MERMHOUSE_FISHER = "The fisherfolk dwell here.",
		MONKEYBALL = "A bit of monkey merriment.",
		-- MONSTERTARTARE = "Still quivering.",
		MOSQUITOSACK_YELLOW = "The pest dropped its sack of sickness.",
		MUSSELBOUILLABAISE = "Thin, but warming.",
		MUSSEL_COOKED = "Strong taste.",
		MUSSEL_FARM =
		{
			GENERIC = "It builds mussels.",
			STICKPLANTED = "Become one with the stick...",
		},
		MYSTERYMEAT = "The food of my enemy's children is... what to me?",
		OCTOPUSCHEST = "The chest holds offerings.",
		OCTOPUSKING = "He seems open to bartering.",
		OXHAT = "This helm will keep my scalp dry.",
		OX_FLUTE = "I have no rhythm...",
		OX_HORN = "Ah, a fine mug it would make!",
		PALMLEAF_HUT = "Keeps the rain off my helm.",
		PARROT_PIRATE = "You talk too much!",
		PEG_LEG = "This leg will make a fine basher!",
		PIKE_SKULL = "Reminds me of home.",
		PIRATEGHOST = "To Hel, spirit!",
		PIRATEPACK = "Builds chest muscles.",
		PIRATIHATITATOR =
		{
			BURNT = "Its magic has floated away as embers.",
			GENERIC = "What awkward sorcery is this?",
		},
		PORTAL_SHIPWRECKED = "This longship looks unfit for a warrior.",
		PRIMEAPE = "You are as amusing as you are hairy.",
		PRIMEAPEBARREL = "By this mess I would say a Viking lives here.",
		RAWLING = "Finally! Someone to rehearse with.",
		BARREL_GUNPOWDER = "This cask packs a punch!",
		ROCK_CHARCOAL = "Rocks burn?",
		ROCK_OBSIDIAN = "Lava stone!",
		SAIL_STICK = "I command the wind!",
		SANDBAGSMALL = "This bag of sand battles the water!",
		SANDBAGSMALL_ITEM = "Water crashes against it feebly!",
		SANDCASTLE =
		{
			GENERIC = "I want to pretend I'm a giant and crush it!",
			SAND = "Time has crushed it.",
		},
		SEAWEED_COOKED = "Sea snack.",
		SEAWEED_DRIED = "It is chewy...",
		SHADOWSKITTISH_WATER = "An enemy looms!",
		SHARKITTEN = "It is your momma I want...",
		SHARKITTENSPAWNER =
		{
			GENERIC = "Something lies in wait!",
			INACTIVE = "Just sand... for now...",
		},
		SHARK_GILLS = "Shark gills!",
		SHARK_TEETHHAT = "A helm after my warriors heart!",
		SHIPWRECKED_ENTRANCE = "A new land to plunder and pillage!",
		SHIPWRECKED_EXIT = "Off to a new land...",
		SNAKEDEN =
		{
			BURNT = "It's burnt. No sense vine-ing about it.",
			CHOPPED = "It needed a haircut.",
			GENERIC = "This bush has helm head.",
		},
		SNAKEOIL = "What powerful properties does this bestow?",
		SAIL_SNAKESKIN = "A sail made of murder!",
		SPEAR_LAUNCHER = "A gift from Odin!",
		SUNKEN_BOAT =
		{
			ABANDONED = "The sea claims another!",
			GENERIC = "He has something to say!",
		},
		SUNKEN_BOAT_BURNT = "A Viking funeral has taken place...",
		SUNKEN_BOAT_TRINKET_1 = "Some kind of crude weapon?", 
		SUNKEN_BOAT_TRINKET_2 = "A child's longship.", 
		SUNKEN_BOAT_TRINKET_3 = "Soggy candle.", 
		SUNKEN_BOAT_TRINKET_4 = "Sea sorcery.", 
		SUNKEN_BOAT_TRINKET_5 = "Not my size.",
		SWEETPOTATOSOUFFLE = "It is filled with delicious air!",
		SWEET_POTATO = "I have never heard of a potato that is sweet! ...Gross!",
		SWEET_POTATO_COOKED = "I won't eat it, but I appreciate the color.",
		SWEET_POTATO_PLANTED = "There are inedible plantsweets in the ground!",
		SWEET_POTATO_SEEDS = "These will grow sweetly.",
		SWIMMINGHORROR = "Are you here to give me a Viking's funeral?",
		TELEPORTATO_SW_BASE = "It is missing things.",
		TELEPORTATO_SW_BOX = "It is part of something.",
		TELEPORTATO_SW_CRANK = "It cranks. But for what?",
		TELEPORTATO_SW_POTATO = "What strange contraption is this?",
		TELEPORTATO_SW_RING = "Is it valuable?",
		THATCHPACK = "I hope my spear doesn't poke a hole in it.",
		TIDALPOOL = "A tiny lake!",
		TIDAL_PLANT = "Soggy plant.",
		TIGEREYE = "I've got the eye of the tigershark!",
		TRAWLNETDROPPED =
		{
			GENERIC = "Plunderful!",
			SOON = "The plunder will sink soon.",
			SOONISH = "I think my plunder will sink soon.",
		},
		TRINKET_IA_20 = "Some kind of crude weapon?", 
		TRINKET_IA_21 = "A child's longship.",
		TRINKET_IA_22 = "Soggy candle.", 
		TRINKET_IA_23 = "A broken something.", 
		FISH_TROPICAL = "Inside it is the color of meat!",
		TUNACAN = "Food that can survive a voyage!",
		TURF_ASH = "A piece of the battlefield.",
		TURF_MAGMAFIELD = "A piece of the battlefield.",
		TURF_MEADOW = "A piece of the battlefield.",
		TURF_SNAKESKIN = "My enemy's hide feels good beneath my feet!",
		TURF_SWAMP = "A piece of the battlefield.",
		TURF_TIDALMARSH = "A piece of the battlefield.",
		TURF_VOLCANO = "A piece of the battlefield.",
		TWISTER_SEAL = "You were the little guy doing all that huffing and puffing?!?",
		VOLCANO_ALTAR =
		{
			GENERIC = "The altar of the fire gods sleeps.",
			OPEN = "It is ready to receive sacrifice!",
		},
		VOLCANO_ALTAR_TOWER = "An altar to the fire gods!",
		VOLCANO_SHRUB = "You look burnt out.",
		WALLYINTRO_DEBRIS = "Is this the wreckage of my longship?",
		WATERYGRAVE = "Plunder under!",
		WHALE_BUBBLES = "Something lurks beneath.",
		WHALE_TRACK = "I shall whale on you!",
		WILBUR_CROWN = "I plunder what this is?",
		WILBUR_UNLOCK = "I kneel to no king, even adorable ones!",
		WILDBORE = "I sense a kindred spirit!",
		WILDBOREHEAD = "Save a mug in Valhalla for me.",
		WILDBOREHOUSE = "A terrible place to live!",
		WIND_CONCH = "I feel a breeze...",
		WOODLEGS_CAGE = "A locked cage!",
		WOODLEGS_KEY1 = "What might this open?",
		WOODLEGS_KEY2 = "Another key!",
		WOODLEGS_KEY3 = "A strange key!",
		SHIPWRECK = "Longships litter the path to Valhalla.",
        BOAT_ENCRUSTED = "It's no Viking longship, but it will carry me.",    
        BABYOX = "What cute meat.",
        BALLPHINHOUSE = "A gathering place for swimming meat.",
        DORSALFIN = "No more will it crest the waves.",     
        NUBBIN = "No Excalibur juts from its center.",
        CORALLARVE = "Be you meat?",
        RAINBOWJELLYFISH = "Hail, fish of jelly!",
        RAINBOWJELLYFISH_PLANTED = "Blessed with beauty by Freyr herself.",
        RAINBOWJELLYFISH_DEAD = "To swim, to sting no more.",
        RAINBOWJELLYFISH_COOKED = "Ah, a proper meal!",
        RAINBOWJELLYJERKY = "A feast!",
        WALL_ENFORCEDLIMESTONE = "No wall can hold my warrior's spirit!",
        WALL_ENFORCEDLIMESTONE_ITEM = "To build ",    
        CROCODOG = "Finally, a worthy foe!",
        POISONCROCODOG = "What venom flows through thy veins?",
        WATERCROCODOG = "My, what big teeth you have!",     
        QUACKENBEAK = "The remains of a thrilling battle.",
        QUACKERINGRAM = "I will knock down all who stand in my path!",
        CAVIAR = "I would have rathered the fish.",
        CORMORANT = "A beast of both sky and sea!",
        PURPLE_GROUPER = "Aegir shall not save you this day.",
        PIERROT_FISH = "I wish this meat did not have such large eyes.",
        NEON_QUATTRO = "Thou shalt swim no more.",
        PURPLE_GROUPER_COOKED = "Thank Njord for this gift!",
        PIERROT_FISH_COOKED = "Thank you, fish, for the gift of thy meat.",
        NEON_QUATTRO_COOKED = "Njord gives me my fill this day.",

        FISH_FARM = 
        {
        	EMPTY = "The goddess Ran has blessed me with her net.",
			STOCKED = "Now I wait for Ran to smile upon me!",
			ONEFISH = "The meat has sprouted!",
			TWOFISH = "The swimming meat flourishes!",
			REDFISH = "A thriving oasis of swimming meat!",
			BLUEFISH  = "Thank Njord for this meaty bounty!",
        },
        ROE = "One day you may be true meat.",
        ROE_COOKED = "You shall never be true meat now.",
        
        SEA_YARD = 
        {
            ON = "An altar to Njord!",
            OFF = "There will be no mending my longship this day.",
            LOWFUEL = "I need more fuel!",
        },
        
        SEA_CHIMINEA =
        {
            EMBERS = "Fire, fire, why dost thou burnest low?",
            GENERIC = "To protect my fires from Aegir's grasp.",
            HIGH = "Loge's power repels the night!",
            LOW = "I might stoke thine fire.",
            NORMAL = "A humble flame.",
            OUT = "The fire has lost its fight.",
        }, 

        TAR = "Surely a substance of pure evil.",
        TAR_EXTRACTOR =
        {
            ON = "It is exorcising evil from the sea.",
            OFF = "I have halted its dark work for now.",
            LOWFUEL = "The machine shall not hold much longer.",
        },
        TAR_POOL = "Something vile bubbles from beneath.",

        TARLAMP = "A light to guide mine longship!",
        TARSUIT = "This shall repel Aegir's clammy touch.",
        TAR_TRAP = "To ensnare mine enemies!",
        TROPICALBOUILLABAISSE = "Tis a fish feast!",
        
        SEA_LAB = "Aegir, bless me with thy wisdom!",
        WATERCHEST = "Spares my effects from the sea's dark depths.",
        QUACKENDRILL = "To thrust into the heart of the sea!",
        HARPOON = "I shalt bring the hunt to the seas!",
        MUSSEL_BED = "Sea meat in the making.",
},
}
