return {
ACTIONFAIL = {
	REPAIRBOAT =
	{
		GENERIC = "Not right now.",
	},
	READ =
	{
		--Maxwell can't get Birds Of The World in SW, but he can in DST. Improvise why Hurricane blocks this! -M
		NOBIRDS = "Drat! Those blasted birds refuse to come down.",
	},
},

ANNOUNCE_MAGIC_FAIL = "Such magic does not belong here.",
ANNOUNCE_OTHER_WORLD_PLANT = "I can't possibly plant this here.",
ANNOUNCE_MESSAGEBOTTLE =
{
	"The penmanship is atrocious. I can't make it out.",
},
ANNOUNCE_BOAT_DAMAGED = "My vessel is sustaining damage.",
ANNOUNCE_BOAT_SINKING = "I fear I've sprung a leak.",
ANNOUNCE_BOAT_SINKING_IMMINENT = "After everything, is this how it ends?!",
ANNOUNCE_CRAB_ESCAPE = "Crafty crustacean...",
ANNOUNCE_MAPWRAP_LOSECONTROL = "I am consumed by the abyss!",
ANNOUNCE_MAPWRAP_RETURN = "Thank goodness.",
ANNOUNCE_MAPWRAP_WARN = "I want nothing to do with mists and fogs.",
ANNOUNCE_MORETREASURE = "Ah. Another guide to a lost treasure.",
ANNOUNCE_OTHER_WORLD_TREASURE = "I don't believe this treasure is located nearby.",
ANNOUNCE_SHARX = "It seems I'm being pursued.",
ANNOUNCE_TRAWL_FULL = "The net is full to bursting!",
ANNOUNCE_TREASURE = "It appears I can follow this to some sort of... treasure.",
ANNOUNCE_VOLCANO_ERUPT = "There's no need for such outbursts.",
ANNOUNCE_WAVE_BOOST = "Truly!",
ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "Pursue the beast!",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Foiled by a fish!",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "I've lost sight of the whale!",

DESCRIBE = {
	-- PORTABLECOOKPOT_ITEM = "An instrument of the dark culinary arts.",
	CHEFPACK = "It puts its contents into hibernation.",
	-- PORTABLECOOKPOT = 
	-- {
		-- COOKING_LONG = "A true culinarian has patience when cooking like none other.",
		-- COOKING_SHORT = "Warly's cooking is nearly plated.",
		-- DONE = "Finally, some quality grub.",
		-- EMPTY = "Just the thought makes my mouth water.",
    -- },
	-- WARLY = 
    -- {
        -- GENERIC = "Good day, Mr. %s.",
        -- ATTACKER = "%s is stirring up trouble...",
        -- MURDERER = "Murderous fiend! Taste my wrath!",
        -- REVIVER = "%s has excellent command of the dark culinary arts.",
        -- GHOST = "You know the price of revival as well as I do, %s.",
		-- FIRESTARTER = "That is not where cooking fires go, %s.",
    -- },

	SEAWEED_STALK = "So much work for some wet weeds.", --copied from the Wikia because I couldn't find it in the game files. -M

	LEIF_PALM = "Cease this nonsense!", --"Disgusting creature!",
	-- BANANAPOP = "Hm... I don't know what I was expecting.",
	BISQUE = "Excellent food, but the ambiance could be improved.",
	-- CEVICHE = "A delightful, cultured dish.",
	SEAFOODGUMBO = "It looks passable.",
	SURFNTURF = "A very balanced meal, I suppose.",
	SHARKFINSOUP = "My refined palate relishes the taste of endangerment.",
	LOBSTERDINNER = "And here I forgot my bib.",
	LOBSTERBISQUE = "Ah, I do enjoy the finer things.",
	JELLYOPOP = "Hm... I don't think this meshes well with my cultivated look.",
	TROPICALFAN = "Is it windy out or is it just my fan?",
	PALMLEAF_UMBRELLA = "It serves its purpose.",
	SOLOFISH_DEAD = "Stay.",
	FISH_MED_COOKED = "It still stinks.",
	GHOST_SAILOR = "He reminds me of someone...",
	AERODYNAMICHAT = "Quite sleek, if not elegant.",
	ANTIVENOM = "A cure to what ails you.",
	ARMORCACTUS = "Nothing says \"stay away\" quite like this.",
	ARMORLIMESTONE = "It renders me... sluggish.",
	ARMOROBSIDIAN = "I've bent the flame to my will.",
	ARMORSEASHELL = "Perhaps not the sturdiest, but it will conceal my vulnerabilities.",
	ARMOR_LIFEJACKET = "Sadly my cultured countenance must take a backseat to sensibility.",
	ARMOR_SNAKESKIN = "Quite dapper!",
	ARMOR_WINDBREAKER = "Sigh.",
	BOAT_ARMOURED = "This boat knows how to take a hit like a champion.",
	BABYOX = "Stop chewing my cufflinks, wretched cur.",
	BALLPHIN = "They're much craftier than they appear at first glance.",
	BAMBOO = "I have several ideas in mind for this.",
	BAMBOOTREE =
	{
		BURNT = "It will not be returning.",
		CHOPPED = "It needs time to replenish.",
		GENERIC = "It can grow through just about anything.",
	},
	BERMUDATRIANGLE = "It's calling to me to dive in.",
	BIGFISHINGROD = "Perhaps I'll have better luck with the swimming meat now.",
	BIOLUMINESCENCE = "Quite otherworldly, no?",
	BLOWDART_FLUP = "This is quite a stunning contraption.",
	BLOWDART_POISON = "I've turned the venom of this world against itself.",
	BLUBBER = "I believe I can... eat it...",
	BLUBBERSUIT = "This is undignified.",
	BOATCANNON = "It's about time I got my hands on one of these.",
	BOATREPAIRKIT = "It will hold off my vessel's inevitable decay.",
	BOAT_LANTERN = "It lends an eerie glow to all around it.",
	BOAT_TORCH = "Sailing at night seems unsafe, but this makes it somewhat better.",
	BOTTLELANTERN = "Their lives have found purpose in servitude.",
	BRAINJELLYHAT = "I feel inspired.",
	BUOY = "It floats with ease.",
	BURIEDTREASURE = "Ah, what's this then?",
	BUSH_VINE =
	{
		BURNT = "It's met its end.",
		CHOPPED = "Used up, for now.",
		GENERIC = "These have taken over the island.",
	},
	CAPTAINHAT = "It makes me feel commanding.",
	BOAT_CARGO = "Ah, plenty of room to breathe.",
	CHIMINEA = "Safe keeping for my hard earned fires.",
	SAIL_CLOTH = "It will aid in my travels.",
	COCONADE =
	{
		BURNING = "I may want to take cover.",
		GENERIC = "I foresee death in the future.",
	},
	COCONUT = "Could do considerable damage to a person's noggin.",
	COCONUT_SAPLING = "It can't hurt anyone anymore.",
	COCONUT_COOKED = "It will last me for now.",
	COCONUT_HALVED = "I made one coconut into two... Magic!",
	COFFEE = "I look forward to this.",
	COFFEEBEANS = "It's strange to see them this color.",
	COFFEEBEANS_COOKED = "Better than raw, but perhaps there's a better way to prepare them?",
	COFFEEBOT = "It will do my coffee-related bidding.",
	COFFEEBUSH =
	{
		BARREN = "Barren.",
		GENERIC = "Delightful coffee beans.",
		PICKED = "I've picked them all.",
		WITHERED = "Decay has overtaken it.",
	},
	CORAL = "It's quite lovely.",
	ROCK_CORAL = "This could likely support a wide array of life.",
	CORAL_BRAIN = "Now I can harness its thoughtpower for myself.",
	CORAL_BRAIN_ROCK = "I wonder what it's thinking?",
	CRAB =
	{
		GENERIC = "An edible crustacean.",
		HIDDEN = "The crabbit is hiding.",
	},
	CRABHOLE = "It can't hide forever.",
	CRATE = "Perhaps I could pry it open.",
	CUTLASS = "A gentleman's weapon.",
	SWORDFISH_DEAD = "Perhaps it should have taken more fencing lessons.",
	DEPLETED_BAMBOOTREE = "It's gone.",
	DEPLETED_BUSH_VINE = "No more.",
	DEPLETED_GRASS_WATER = "That was all there was.",
	DEVTOOL = "How odd.",
	DEVTOOL_NODEV = "I fear I cannot grasp it.",
	DOUBLE_UMBRELLAHAT = "This looks silly.",
	DOYDOY = "This sad creature has no hope of survival.",
	DOYDOYBABY = "Now there will be more of them.",
	DOYDOYEGG = "Hmm, propagate a dying species or enjoy a light snack?",
	DOYDOYEGG_COOKED = "A light snack is always the best option.",
	DOYDOYEGG_CRACKED = "Whoops.",
	DOYDOYFEATHER = "It would look dashing tucked in a Sunday hat.",
	DOYDOYNEST = "What are their chances, you think?",
	DRAGOON = "Don't you know who I am?",
	DRAGOONDEN = "I see no reason to disturb them.",
	DRAGOONEGG = "It radiates an oppressive heat.",
	DRAGOONHEART = "Hearts only bring pain anyway.",
	DRAGOONSPIT = "Quite uncouth.",
	DUBLOON = "The clinking sound when they rub together is intensely satisfying.",
	DUG_BAMBOOTREE = "I suppose I should find a place for this.",
	DUG_BUSH_VINE = "I should find a proper place for this.",
	DUG_COFFEEBUSH = "This is worth replanting.",
	DUG_ELEPHANTCACTUS = "I'd better not run with it.",
	EARRING = "I would look quite dashing in it, were my ear pierced.",
	ELEPHANTCACTUS = "It won't be shooting anyone like this.",
	ELEPHANTCACTUS_ACTIVE = "Take cover!",
	ELEPHANTCACTUS_STUMP = "Good riddance.",
	FABRIC = "I've fashioned the bamboo into something useful.",
	SAIL_FEATHER = "I suppose it's better than paddling.",
	FISHINHOLE = "They would be much more content in my stomach.",
	FISH_MED = "Could use a touch of fire.",
	FISH_SMALL = "Have I been reduced to this?",
	FISH_SMALL_COOKED = "...Bottoms up.",
	FLAMEGEYSER = "That puts on quite a spectacle.",
	FLOTSAM = "Perhaps I could reel it in somehow.",
	FLUP = "That thing is quite beneath me.",
	-- FRESHFRUITCREPES = "Deserves to be eaten with fine silverware. Sadly, I've just my hands.",
	FROG_POISON = "I had better teach it some manners.",
	GASHAT = "Cleans the stench away.",
	GOLDENMACHETE = "I've always wanted to hack things in luxury.",
	GRASS_WATER = "It is partially submerged.",
	HAIL_ICE = "Slightly chilly.",
	HOUNDFIRE = "A biting flame!",
	ICEMAKER =
	{
		HIGH = "It's working hard to make ice for me.",
		LOW = "I'd better fill it up.",
		NORMAL = "It appears to be doing its job.",
		OUT = "It's not doing its job.",
		VERYLOW = "It's on its last legs.",
	},
	IRONWIND = "Thank goodness, I have places to be!",
	JELLYFISH = "What a strange little creature.",
	JELLYFISH_COOKED = "It will do, I suppose.",
	JELLYFISH_DEAD = "I like it better dead.",
	JELLYFISH_PLANTED = "It's quite shocking.",
	JELLYJERKY = "I actually don't mind this?",
	JUNGLETREE =
	{
		BURNING = "It is not long for this world.",
		BURNT = "In another lifetime, perhaps.",
		CHOPPED = "I have used it for my own purposes.",
		GENERIC = "I believe it wants me to chop it down.",
	},
	JUNGLETREESEED = "I could replant this, theoretically.",
	JUNGLETREESEED_SAPLING = "Good. I was right.",
	KNIGHTBOAT = "Obey me, fool!",
	KRAKEN = "You will bow to me.",
	KRAKENCHEST = "Now for my reward.",
	KRAKEN_TENTACLE = "How dare you touch me?",
	LAVAPOOL = "Exceptionally toasty.",
	LIMESTONENUGGET = "Perhaps this sealife's death will find use after all.",
	ROCK_LIMPET =
	{
		GENERIC = "Could be used as a food source in a pinch.",
		PICKED = "Just a rock now.",
	},
	LIMPETS = "Slimy and vaguely ingestible.",
	LIMPETS_COOKED = "A delicacy? Really?",
	LIVINGJUNGLETREE = "Nothing out of the ordinary here.",
	LOBSTER = "Now that looks like a proper meal.",
	LOBSTERHOLE = "Show yourself, delicious critters.",
	LOBSTER_DEAD = "Excellent.",
	LOBSTER_DEAD_COOKED = "I forgot my bib.",
	BOAT_LOGRAFT = "It seems like there should be regulations against this.",
	LUGGAGECHEST = "Quite a dapper briefcase if I do say so.",
	MACHETE = "Truthfully I was always a hack.",
	MAGIC_SEAL = "I sense a powerful force within it.",
	MAGMAROCK = "Well, it's a rock.",
	MAGMAROCK_FULL = "Well, it's a rock.",
	MAGMAROCK_GOLD = "This rock is much more luxurious.",
	MAGMAROCK_GOLD_FULL = "This rock is much more luxurious.",
	MANGROVETREE = "A tree like any other... but wet.",
	MANGROVETREE_BURNT = "It has been destroyed.",
	MARSH_PLANT_TROPICAL = "Not of much use to me.",
	MERMFISHER = "I have no quarrel with him.",
	MERMHOUSE_FISHER = "I suppose everyone needs to live somewhere...",
	MESSAGEBOTTLE = "What is this primitive communication?",
	MESSAGEBOTTLEEMPTY = "Given enough time I could build a ship inside.",
	MONKEYBALL = "What am I supposed to do with this?",
	-- MONSTERTARTARE = "It's less than appetizing.",
	MOSQUITOSACK_YELLOW = "I'll be taking that blood back, thank you.",
	MOSQUITO_POISON = "I would like to avoid being bitten by this one.",
	MUSSEL = "They're a delicacy... somewhere.",
	MUSSELBOUILLABAISE = "I truly look forward to a full meal.",
	MUSSEL_COOKED = "Looks to be less of a health hazard now.",
	MUSSEL_FARM =
	{
		GENERIC = "It appears to be a convenient gathering of food.",
		STICKPLANTED = "They're oblivious to their approaching death.",
	},
	MUSSEL_STICK = "The mussels won't be able to resist.",
	MYSTERYMEAT = "Rather disgusting.",
	NEEDLESPEAR = "Exceedingly sharp.",
	OBSIDIAN = "What a delightful color.",
	OBSIDIANAXE = "It seems to work best when alight.",
	OBSIDIANCOCONADE = "This is definitely overkill.",
	OBSIDIANFIREPIT =
	{
		EMBERS = "I should attend to that.",
		GENERIC = "The stone was born for this.",
		HIGH = "A roaring fire.",
		LOW = "It's getting low.",
		NORMAL = "It's burning in style.",
		OUT = "It's gone cold.",
	},
	OBSIDIANMACHETE = "This seems like a dangerous thing to farm with.",
	OBSIDIANSPEARGUN = "Projectile flame. I quite like it.",
	OBSIDIAN_WORKBENCH = "This workstation ignites a spark of creativity in my heart...",
	OCTOPUSCHEST = "It looks... rotten.",
	OCTOPUSKING = "I could use his generosity to my advantage.",
	OX = "It is smelly and very stupid.",
	OXHAT = "Sometimes one must sacrifice form for function.",
	OX_FLUTE = "Goodness. It's been awhile since I played.",
	OX_HORN = "The beast stood no chance.",
	PACKIM = "His irritating appearance is tempered by his usefulness and willing servitude.",
	PACKIM_FISHBONE = "I think I should hold onto it.",
	PALMLEAF = "Now I just need servants to fan my glorious self!",
	PALMLEAF_HUT = "Phew.",
	PALMTREE =
	{
		BURNING = "It is not long for this world.",
		BURNT = "In another lifetime, perhaps.",
		CHOPPED = "I have used it for my own purposes.",
		GENERIC = "How luxurious.",
	},
	PARROT = "Hm. Colorful.",
	PARROT_PIRATE = "Perhaps I can shut him up.",
	PEACOCK = "This creature understands showmanship.",
	PEG_LEG = "Good for whacking.",
	PIKE_SKULL = "Drab.",
	PIRATEGHOST = "I'll not be meeting the same fate!",
	PIRATEHAT = "Is this amusing?",
	PIRATEPACK = "I suppose it will do.",
	PIRATIHATITATOR =
	{
		BURNT = "Ashes to ashes.",
		GENERIC = "Such a fascinating device.",
	},
	POISONHOLE = "I can see it just fine from here... No need to get closer.",
	PORTAL_SHIPWRECKED = "Useless!",
	PRIMEAPE = "This pitiful creature possesses only a modicum of intelligence.",
	PRIMEAPEBARREL = "Keep me away from that.",
	BOAT_RAFT = "Much too precarious for my liking.",
	RAWLING = "Oh good. A talking sack of stuffing.",
	BARREL_GUNPOWDER = "It's bursting with potential.",
	ROCK_CHARCOAL = "I can't help but admire the natural formations.",
	ROCK_OBSIDIAN = "It refuses to bend to my tools.",
	BOAT_ROW = "Manually operated. A pity.",
	SAIL_PALMLEAF = "It will be smooth sailing with this at my back.",
	SAIL_STICK = "A stick, presumably for sailing.",
	SAND = "Rocks so thoroughly beaten down they are no longer recognizable.",
	SANDBAG = "A bag of dirt that keeps water out.",
	SANDBAGSMALL = "A bag of dirt that keeps water out.",
	SANDBAGSMALL_ITEM = "A bag of dirt I can carry.",
	SANDBAG_ITEM = "A bag of dirt I can carry.",
	SANDDUNE = "A little mound of yellow sand.",
	SANDCASTLE =
	{
		GENERIC = "I found that wholly unenjoyable. I swear.",
		SAND = "Decorative sand.",
	},
	SEAGULL = "It is loud and irritating.",
	SEAGULL_WATER = "Rather uncivil.",
	SEASACK = "It won't make me stronger, but it'll give me more pockets.",
	SEASHELL = "Holding it makes me feel like a tourist.",
	SEASHELL_BEACHED = "A little kitschy for my taste.",
	SEATRAP = "The curiosity will get the best of you eventually.",
	SEAWEED = "Sea garbage.",
	SEAWEED_COOKED = "I'm loathe to eat this.",
	SEAWEED_DRIED = "Ugh.",
	SEAWEED_PLANTED = "It thrives here.",
	SHADOWSKITTISH_WATER = "Oh dear.",
	SHARKITTEN = "A charming monstrosity.",
	SHARKITTENSPAWNER =
	{
		GENERIC = "The pile stirs when I mention treats.",
		INACTIVE = "An ordinary pile of sand.",
	},
	SHARK_FIN = "A trophy from a most excellent kill.",
	SHARK_GILLS = "I suppose they're worth hanging on to.",
	SHARK_TEETHHAT = "I respect this fashion choice.",
	SHARX = "It's not a question of \"if\" I will conquer it, but when.",
	SHIPWRECKED_ENTRANCE = "I hope you're prepared.",
	SHIPWRECKED_EXIT = "Farewell.",
	SLOTMACHINE = "I admittedly have a penchant for tempting fate.",
	SNAKE = "A cruel yet elegant beastie.",
	SNAKEDEN =
	{
		BURNT = "It's met its end.",
		CHOPPED = "Used up, for now.",
		GENERIC = "These have taken over the island.",
	},
	SNAKEOIL = "Perhaps I could turn a profit with this.",
	SNAKESKIN = "The texture is delectable.",
	SNAKESKINHAT = "Quite dashing, actually.",
	SAIL_SNAKESKIN = "For ease of travel.",
	SNAKE_FIRE = "Something's got that snake heated.",
	SNAKE_POISON = "Perhaps I'll give that one a wide berth.",
	SOLOFISH = "It smells like wet dog.",
	SPEARGUN = "This projectile flinger may come in handy.",
	SPEARGUN_POISON = "I've made sure it packs an extra wallop.",
	SPEAR_LAUNCHER = "This projectile flinger may come in handy.",
	SPEAR_OBSIDIAN = "I've made sure it packs a fiery wallop.",
	SPEAR_POISON = "I've made sure it packs an extra wallop.",
	SPOILED_FISH = "I believe I should dispose of this.",
	STUNGRAY = "It smells quite atrocious.",
	SUNKEN_BOAT =
	{
		ABANDONED = "It's ferociously guarded.",
		GENERIC = "It will never sail again.",
	},
	SUNKEN_BOAT_BURNT = "All things are doomed in time.",
	SUNKEN_BOAT_TRINKET_1 = "Exactly what it looks like. Err... What does it look like?",
	SUNKEN_BOAT_TRINKET_2 = "I feel as though it is mocking my situation.",
	SUNKEN_BOAT_TRINKET_3 = "It has no apparent function.",
	SUNKEN_BOAT_TRINKET_4 = "An advanced little gadget.",
	SUNKEN_BOAT_TRINKET_5 = "It was probably hideous before soaking in bilgewater.",
	SUPERTELESCOPE = "This may help me get the lay of the land.",
	SWEETPOTATOSOUFFLE = "Why, this looks halfway palatable!",
	SWEET_POTATO = "Ready for cooking.",
	SWEET_POTATO_COOKED = "Storebought just doesn't taste the same.",
	SWEET_POTATO_PLANTED = "I've eaten worse things. Much worse.",
	SWEET_POTATO_SEEDS = "Perhaps something will grow if I shove these in the ground.",
	SWIMMINGHORROR = "I've had enough of your kind, fiend.",
	SWORDFISH = "Ah, a sparring partner!",
	TELEPORTATO_SW_BASE = "I see the makings of something quite handsome.",
	TELEPORTATO_SW_BOX = "Another piece of the puzzle.",
	TELEPORTATO_SW_CRANK = "Excellent. Not long now.",
	TELEPORTATO_SW_POTATO = "I do admit it's a little ridiculous.",
	TELEPORTATO_SW_RING = "Ah, another piece.",
	TELESCOPE = "This may help me get the lay of the land.",
	THATCHPACK = "Not much, but the extra space is better than nothing.",
	TIDALPOOL = "Much deeper than it lets on.",
	TIDAL_PLANT = "It's a bit of a runt.",
	TIGEREYE = "Not something a gentleman handles without gloves.",
	TIGERSHARK = "Aptly named.",
	TOUCAN = "Colorful vermin.",
	TRAWLNET = "I see no downside to using this.",
	TRAWLNETDROPPED =
	{
		GENERIC = "Just think of the meals I'll make.",
		SOON = "Into the depths...",
		SOONISH = "It's working its way down.",
	},
	TRIDENT = "A fork fit for ocean royalty.",
	TRINKET_IA_13 = "A welcome change from seawater.",
	TRINKET_IA_14 = "This seems like bad voodoo.",
	TRINKET_IA_15 = "It only has four strings.",
	TRINKET_IA_16 = "Letters and numbers... some sort of secret code?",
	TRINKET_IA_17 = "It was probably hideous before soaking in bilgewater.",
	TRINKET_IA_18 = "A little superglue and it would make a lovely centerpiece.",
	TRINKET_IA_19 = "Neither red nor blue.",
	TRINKET_IA_20 = "Exactly what it looks like. Err... What does it look like?",
	TRINKET_IA_21 = "Might be nice in a hot bath...",
	TRINKET_IA_22 = "Looks like something one would find at a backwater flea market.",
	TRINKET_IA_23 = "It's not communicating with anyone now.",
	FISH_TROPICAL = "It belongs on a skewer.",
	TUNACAN = "Fish is presumably contained inside.",
	TURBINE_BLADES = "It appears expertly engineered.",
	TURF_ASH = "It appears to be some turf.",
	TURF_BEACH = "It appears to be some turf.",
	TURF_JUNGLE = "It appears to be some turf.",
	TURF_MAGMAFIELD = "It appears to be some turf.",
	TURF_MEADOW = "It appears to be some turf.",
	TURF_SNAKESKIN = "It appears to be some turf.",
	TURF_SWAMP = "It appears to be some turf.",
	TURF_TIDALMARSH = "It appears to be some turf.",
	TURF_VOLCANO = "It appears to be some turf.",
	TWISTER = "I would rather not get sucked into that.",
	TWISTER_SEAL = "It's, uh... cute?",
	VENOMGLAND = "Could this be the cure?",
	VINE = "It's twisted and gnarled.",
	VOLCANO = "I respect its power.",
	VOLCANOSTAFF = "It feels at home in my hands.",
	VOLCANO_ALTAR =
	{
		GENERIC = "It appears to be a place of offering.",
		OPEN = "Do I dare play with more forces beyond my control?",
	},
	VOLCANO_ALTAR_BROKEN = "A true pity.",
	VOLCANO_ALTAR_TOWER = "What a captivating structure.",
	VOLCANO_EXIT = "I must take my leave.",
	VOLCANO_SHRUB = "Had I any pity, I would give it to this tree.",
	WALLYINTRO_DEBRIS = "What nonsense is this now?",
	WALL_LIMESTONE = "It will hold.",
	WALL_LIMESTONE_ITEM = "Where should I begin building my fortress?",
	WATERYGRAVE = "Not all find a final resting place.",
	WHALE_BLUE = "Surrender to me.",
	WHALE_BUBBLES = "You've given yourself away, pal.",
	WHALE_CARCASS_BLUE = "Size truly doesn't matter!",
	WHALE_CARCASS_WHITE = "I triumphed over it!",
	WHALE_TRACK = "I'm in hot pursuit!",
	WHALE_WHITE = "We meet again.",
	WILBUR_CROWN = "The inside is filthy.",
	WILBUR_UNLOCK = "Well I suppose there's no sending you back now.",
	WILDBORE = "I'll easily dispose of that swinish brute.",
	WILDBOREHEAD = "Lovely ambiance.",
	WILDBOREHOUSE = "Is this what passes for architecture around here?",
	WIND_CONCH = "Beautiful on the outside, destructive on the inside.",
	BOAT_WOODLEGS = "Seems dependable.",
	WOODLEGSHAT = "Swashbuckling...",
	SAIL_WOODLEGS = "A fine sail.",
	WOODLEGS_CAGE = "We are all trapped, in one way or another.",
	WOODLEGS_KEY1 = "Brittle.",
	WOODLEGS_KEY2 = "A key of fine gold.",
	WOODLEGS_KEY3 = "Just common iron.",
	SHIPWRECK = "It stood no chance.",
	CALIFORNIAROLL = "We meet again, crabbit.",

	--- 5C DLC ------------------------------------------------------------------------------------------------
	
	BOAT_ENCRUSTED = "It seems sturdy enough to carry me.",
	BABYOX = "You'll get no special treatment from me, beast.",
	BALLPHINHOUSE = "Ah. I need a castle like that.",
	DORSALFIN = "I could build a decent castle with this.",
	NUBBIN = "It's not bald! It's distinguished!",
	CORALLARVE = "You're not cute.",
	RAINBOWJELLYFISH = "Such extraneous colors...",
	RAINBOWJELLYFISH_PLANTED = "Hm. It's very fond of bioluminescence.",
	RAINBOWJELLYFISH_DEAD = "That one's not getting back up.",
	RAINBOWJELLYFISH_COOKED = "Done, like dinner.",
	RAINBOWJELLYJERKY = "Not the easiest on my teeth.",
	WALL_ENFORCEDLIMESTONE = "About as well constructed as sea trash can be.",
	WALL_ENFORCEDLIMESTONE_ITEM = "I suppose I could place this on the water.",
	CROCODOG = "Oh great, another abomination.",
	POISONCROCODOG = "It won't obey me.",
	WATERCROCODOG = "Smells like wet dog.",
	QUACKENBEAK = "Just look at the size of that thing.",
	QUACKERINGRAM = "Quacker before me!! Uh, I mean quiver...!",

	--- DLC ------------------------------------------------------------------------------------------------    

	CAVIAR = "A meal fitting of my stature.",
	CORMORANT = "Unlike me, it has no trouble surviving out here.",

	PURPLE_GROUPER = "Truly an ugly creature.",
	PIERROT_FISH = "Delightfully pinstriped.",
	NEON_QUATTRO = "Don't you ever blink?",

	PURPLE_GROUPER_COOKED = "Purple on the outside, pink in the middle.",
	PIERROT_FISH_COOKED = "I'll be picking bones out of my teeth for weeks.",
	NEON_QUATTRO_COOKED = "Don't worry, there's plenty of them in the sea.",

	FISH_FARM = 
	{
		EMPTY = "I need some fish eggs if I want fish.",
		STOCKED = "I put the eggs in. Where are my fish?",
		ONEFISH = "Success! A fish.",
		TWOFISH = "The more the merrier!",
		REDFISH = "I better not see any rowdiness, fish.",
		BLUEFISH  = "Who would ever need this many fish?",
	},

	ROE = "Raw fish eggs. Fantastic.",
	ROE_COOKED = "The fish eggs are cooked now.",
	
	SEA_YARD = 
	{
		ON = "Much needed ship maintenance.",
		OFF = "Out of commission. For now.",
		LOWFUEL = "This maintenance machine needs maintaining.",
	},

	SEA_CHIMINEA =
	{
		EMBERS = "A flame not long for this world.",
		GENERIC = "It will protect the flames from the waves.",
		HIGH = "I may have overdone it.",
		LOW = "There's barely any heat.",
		NORMAL = "It's burning just fine.",
		OUT = "Out like a light.",
	}, 

	TAR = "Congealed evil.",
	TAR_EXTRACTOR =
	{
		ON = "It's doing its job.",
		OFF = "It's no use to me if it's off.",
		LOWFUEL = "The contraption needs replenishing.",
	},
	TAR_POOL = "Something foul festers beneath.",

	TARLAMP = "A little light in the dark.",
	TARSUIT = "I hope this won't tar-nish my dapper image.",
	TAR_TRAP = "Slow going.",

	TROPICALBOUILLABAISSE = "Hm... Needs more fish.",

	SEA_LAB = "There are watery mysteries to be unlocked yet.",
	WATERCHEST = "My suits had best not get moldy in there.",
	QUACKENDRILL = "I will quack open the sea itself.",
	HARPOON = "How barbaric.",
	MUSSEL_BED = "They'll grow where I tell them to.",
},
}
