return {
ACTIONFAIL = {
	REPAIRBOAT =
	{
		GENERIC = "No need. It already floats our boat.",
	},
},
ANNOUNCE_MAGIC_FAIL = "I don't think this thing likes it here.",
ANNOUNCE_MESSAGEBOTTLE =
{
	"Eight eyes isn't enough to read this.",
},
ANNOUNCE_OTHER_WORLD_PLANT = "We can't grow this here.",
ANNOUNCE_BOAT_DAMAGED = "Our boat's hurt!",
ANNOUNCE_BOAT_SINKING = "Down, down, down we go!",
ANNOUNCE_BOAT_SINKING_IMMINENT = "Help! We can't swim!",
ANNOUNCE_CRAB_ESCAPE = "You slippery snail... er, crabbit!",
ANNOUNCE_MAPWRAP_LOSECONTROL = "We're trembling in our pantaloons!",
ANNOUNCE_MAPWRAP_RETURN = "That was scary!",
ANNOUNCE_MAPWRAP_WARN = "I don't like this...",
ANNOUNCE_MORETREASURE = "Yay! Another treasure hunt!",
ANNOUNCE_OTHER_WORLD_TREASURE = "I don't think I can find this treasure here.",
ANNOUNCE_SHARX = "Mean sea hounds! Leave us alone!",
ANNOUNCE_TRAWL_FULL = "Let's pull'er up!",
ANNOUNCE_TREASURE = "A map! We should follow it!",
ANNOUNCE_VOLCANO_ERUPT = "It's raining fire!",
ANNOUNCE_WAVE_BOOST = "Weee!",
ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "We're on the trail!",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "It went home...",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "It's so choppy!",
DESCRIBE = {
	-- PORTABLECOOKPOT_ITEM = "Makes yummies!",
	CHEFPACK = "It doesn't fit on our head, only on our back.",
	-- PORTABLECOOKPOT = 
	-- {
		-- COOKING_LONG = "Warly says to wait for dinner.",
		-- COOKING_SHORT = "Almost ready!",
		-- DONE = "Warly's cooked us supper!",
		-- EMPTY = "Warly doesn't like us touching it without his supervision.",
    -- },
	-- WARLY = 
    -- {
	    -- GENERIC = "Hello Mr. %s!",
	    -- ATTACKER = "Uhh, Mr. %s might have other things on the menu tonight...",
	    -- MURDERER = "Take it easy, %s! Is dinner cancelled?",
	    -- REVIVER = "Mr. %s makes good meals for us! They're tasty!",
	    -- GHOST = "Don't worry Mr. %s, we'll find you a heart!",
	    -- FIRESTARTER = "%s, what are you cooking this time?",
    -- },

	SEAWEED_STALK = "We should plant this somewhere in the ocean.", --copied from the Wikia because I couldn't find it in the game files. -M

	INVENTORYGRAVE = "They're just sleeping.",
	INVENTORYMOUND = "They're just sleeping.",
	SOLOFISH_DEAD = "All dogfish go to heaven, right?",
	FISH_MED_COOKED = "Flaky and moist. Delicious.",
	GHOST_SAILOR = "He looks kind of sad.",
	TROPICALFAN = "This thing is huge!",
	PALMLEAF_UMBRELLA = "It won't keep us from playing in puddles!",
	-- BANANAPOP = "Yaaay! Popsicle, popsicle!",
	BISQUE = "We lift our pinkies when we eat it.",
	-- CEVICHE = "Yucky!",
	SEAFOODGUMBO = "We could eat it forever!",
	SURFNTURF = "Eww, healthy!",
	SHARKFINSOUP = "Yum, yum, soup!",
	LOBSTERDINNER = "We have to eat it with our eyes closed. Too many legs!",
	LOBSTERBISQUE = "We want to pour it all over our tongues!",
	JELLYOPOP = "Yummy!",
	AERODYNAMICHAT = "We feel light on our feet.",
	ANTIVENOM = "This is medicine?",
	ARMOR_LIFEJACKET = "It pays to be safe.",
	ARMOR_SNAKESKIN = "Rain will bead off this reptilian coat.",
	ARMOR_WINDBREAKER = "Wind can't hold us back!",
	ARMORLIMESTONE = "Our back hurts...",
	ARMOROBSIDIAN = "Our enemies will feel the heat!",
	ARMORSEASHELL = "We feel like a knight in not-so-shiny armor.",
	BOAT_ARMOURED = "It provides peace of mind at sea.",
	BABYOX = "Hey lil fella!",
	BALLPHIN = "Playful rubber blobs. We'll watch from afar.",
	BALLPHINPOD = "Why don't they like us!",
	BAMBOO = "Such a useful stick-type thing.",
	BAMBOOTREE = "Such a small but helpful tree.",
	BERMUDATRIANGLE = "How unsettling!",
	BERRYBUSH2_SNAKE = "Ripe for the pickin'.",
	BERRYBUSH_SNAKE = "Ripe for the pickin'.",
	BIOLUMINESCENCE = "Wooow! Pretty water lights!",
	BLOWDART_POISON = "A sneaky weapon...",
	BOAT_LANTERN = "Seeing where we're going is sure handy!",
	BOATCANNON = "With this we can make a warship!",
	BOATREPAIRKIT = "Never leave home without one.",
	BOTTLELANTERN = "Hey in there, thanks for the light!",
	BURIEDTREASURE = "Treasure, treasure, treasure!",
	BUSH_VINE = "What a crazy looking plant.",
	CAPTAINHAT = "Just like a real boatguy!",
	BOAT_CARGO = "Ah, we can stretch all our legs...",
	CHIMINEA = "Our fires can stay safe from the wind's clutches.",
	CIRCLINGSEAGULL = "Don't poop on us!",
	SAIL_CLOTH = "Now we can harness the wind!",
	COCONADE = "We should throw this very much far away from ourselves.",
	COCONUT = "Food! From a tree!",
	COCONUT_SAPLING = "Aw. It's so little.",
	COFFEE = "Bitter.",
	COFFEEBEANS = "These smell very... adult.",
	
	COFFEEBUSH = "These don't look tasty.",
	CORAL = "Pretty colors.",
	ROCK_CORAL = "A coral party!",
	CRABHOLE = "The sixlegger lives underground.",
	CUTLASS = "There's something fishy about this sword.",
	SWORDFISH_DEAD = "Should we eat it or use it?",
	DEPLETED_BAMBOOTREE = "Come back, bamboos.",
	DEPLETED_BUSH_VINE = "Will the vines come back?",
	DOYDOY = "Nothing behind the eyes...",
	DOYDOYBABY = "Aww, it's a lil dummy.",
	DOYDOYEGG = "Where dumb life begins.",
	
	DOYDOYFEATHER = "Hmmm, it dropped this.",
	DOYDOYNEST = "The lil dummies come from these.",
	DUBLOON = "Shiny coins!",
	DUG_BAMBOOTREE = "We're a gardening expert!",
	DUG_BUSH_VINE = "Where should we put this?",
	DUG_COFFEEBUSH = "With a little love it could grow again.",
	EARRING = "This belonged to a pirate!",
	FABRIC = "We could make a new blankie. Or not.",
	SAIL_FEATHER = "A feathery sail makes for swift travel.",
	FIRERAIN = "It's raining fire!",
	FIRERAINSHADOW = "Duck and cover!",
	FISHINHOLE = "Fishies for the taking!",
	FROG_POISON = "If we get licked by those we'll get sick.",
	GASHAT = "We are protected from sick smells.",
	GOLDENMACHETE = "What a beautiful blade!",
	ICEMAKER = "Ice is useful in this heat.",
	IRONWIND = "Who needs a sail!",
	LEIF_PALM = "Mean tree!",
	JELLYFISH = "That blob is alive!",
	JELLYFISH_COOKED = "We hoped it would be more... solid.",
	JELLYFISH_DEAD = "It's not jelly or fish. It's also not alive.",
	JELLYJERKY = "We'll try anything once.",
	JELLYFISH_PLANTED = "The sea is full of such weird junk.",
	JUNGLETREE =
	{
		BURNING = "What a senseless waste of firewood.",
		BURNT = "That's one less place for snakes to slither from.",
		CHOPPED = "Bye-bye, big tree.",
		GENERIC = "Oh neat, a big tree.",
	},
	JUNGLETREESEED = "Hard to believe such a big tree comes from this!",
	JUNGLETREESEED_SAPLING = "Grow, grow, grow!",
	LAVAPOOL = "Blazing hot!",
	LIMESTONENUGGET = "So bumpy!",
	ROCK_LIMPET =
	{
		GENERIC = "This rock is covered in food things!",
		PICKED = "Come back, yumyums.",
	},
	LIMPETS = "Do we have to eat these?",
	LIMPETS_COOKED = "Tastes like ocean.",
	
	LOBSTER = "This meat wears armor!",
	LOBSTERHOLE = "That is where the armored meat goes during the day.",
	BOAT_LOGRAFT = "This does not look swift.",
	MACHETE = "Hyah! Hyah!",
	MESSAGEBOTTLE = "Maybe there's a comic book in here!",
	MESSAGEBOTTLEEMPTY = "We wish it was filled with soda pop.",
	MOSQUITO_POISON = "These ones leave a gift when they bite.",
	
	MUSSEL = "Maybe one day I'll have big mussels.",
	MUSSEL_STICK = "The mussels do pull-ups on this.",
	OBSIDIAN = "Volcano rocks rock!",
	OBSIDIAN_WORKBENCH = "We forge the fire items here!",
	OBSIDIANAXE = "We'll be unstoppable!",
	OBSIDIANCOCONADE = "The weather will be bomb-y!",
	OBSIDIANFIREPIT =
	{
		EMBERS = "We should put something on the fire before it goes out.",
		GENERIC = "We made the fire stones into a fire home!",
		HIGH = "That fire is huge!",
		LOW = "The fire's getting a touch low.",
		NORMAL = "The toastiest of fires.",
		OUT = "Well, that's done. But not forever!",
	},
	OBSIDIANMACHETE = "It cooks with each cut!",
	SPEAR_OBSIDIAN = "One jab makes'em burn up!",
	OBSIDIANSPEARGUN = "Like shooting fireworks!",
	OX = "Cool horns.",
	PACKIM = "Hello, large-mouthed friend!",
	PACKIM_FISHBONE = "We wonder what this is?",
	PALMLEAF = "Big leaf.",
	PALMTREE = 
	{
		BURNING = "What a senseless waste of firewood.",
		BURNT = "It's dropped its last coconut.",
		CHOPPED = "Goodbye, Tree of Palms.",
		GENERIC = "This tree has presents!",
	},
	PARROT = "Aren't you a chatty fellow!",
	PEACOCK = "Such pretty feathers!",
	PIRATEHAT = "Aaargh, we feel so salty!",
	PIRATIHATITATOR = "With this pirate hat we'll harness dark, cursed stuff.",
	POISONHOLE = "Yikes! The ground is farting!",
	BOAT_RAFT = "Do we think this is sturdy enough?",
	BOAT_ROW = "How's that old song go?",
	SAIL_PALMLEAF = "This'll give us a push!",
	SAND = "It's nice to feel it beneath our many feet.",
	SANDCASTLE = "Look what we built!",
	SANDBAG = "Sand pillows!",
	SANDDUNE = "Wish we had a bucket and a shovel.",
	SEAGULL = "We want to throw something at you.",
	SEAGULL_WATER = "It must be nice to fly... and eat garbage.",
	SEASACK = "Eww, it's wet and squishy.",
	SEASHELL = "Sea litter.",
	SEATRAP = "Things swim in. Dinner comes out.",
	SEAWEED = "The salad of the sea.",
	
	SEAWEED_PLANTED = "We should weed that out, maybe.",
	SHARK_FIN = "Do we touch it?",
	SHARX = "Sh...Sh...SHARK!!!!!",
	SLOTMACHINE = "I think I'm too young for this.",
	SNAKE = "We should keep our distance from those ones.",
	SNAKE_FIRE = "Aaaah, fire-breathing volcano thingies!",
	SNAKE_POISON = "These ones have a sick bite!",
	SNAKESKIN = "The skin of a snake!",
	SNAKESKINHAT = "Does snakeskin make us look tough?",
	SOLOFISH = "Say, there's a lot of meat on you!",
	SPEAR_POISON = "One jab'll do ya.",
	SPEARGUN = "We shoot it!",
	SPEARGUN_POISON = "I better point this away from myself.",
	STUNGRAY = "Aren't you cute! Hey, what's that smell...",
	SUPERTELESCOPE = "Helps us see better than with all our eyes, combined!",
	SWORDFISH = "We like your sword face, fish!",
	TELESCOPE = "I can see so far!",
	TIGERSHARK = "Out of the water!",
	TIGERSHARKSHADOW = "We're scared...",
	TORNADO = "We don't like this...",
	TOUCAN = "What a colorful beak you have!",
	TRAWLNET = "I wonder what we'll drag up.",
	TRAWLNETDROPPED = "What goodies are inside!",
	TRIDENT = "We feel like a god with this in our hands!",
	TRINKET_IA_13 = "Is it our birthday!",
	TRINKET_IA_14 = "Reminds me of Teddy.",
	TRINKET_IA_15 = "I wonder if it's in tune.",
	TRINKET_IA_16 = "Where's the automobile?",
	TRINKET_IA_17 = "Too big for us.",
	TRINKET_IA_18 = "This is a lot older than we are.",
	TRINKET_IA_19 = "What's a brain cloud?",
	TURBINE_BLADES = "Weird.",
	TURF_BEACH = "Some ground we dug up.",
	TURF_JUNGLE = "Some ground we dug up.",
	TWISTER = "Nature hates us!",
	VENOMGLAND = "The key to feeling better if we get sick.",
	VINE = "This stuff is wild.",
	VOLCANO = "Is that a... oh my...",
	VOLCANO_ALTAR = "We can feed the hungry volcano! But what does it like to eat?",
	VOLCANO_ALTAR_BROKEN = "That is a burning shame.",
	VOLCANO_EXIT = "We can escape the heat here.",
	VOLCANOSTAFF = "The volcano does our bidding!",
	WALL_LIMESTONE = "Is this wall made of limes?",
	WALL_LIMESTONE_ITEM = "Why is it called limestone? It's not even green.",
	WHALE_BLUE = "Buck up, big fella!",
	WHALE_CARCASS_BLUE = "Its suffering is over now.",
	WHALE_CARCASS_WHITE = "This is a very big dead thing.",
	WHALE_WHITE = "His eyes burn with hatred!",

	ARMORCACTUS = "Weaponized hugs!",
	BAMBOOTREE =
	{
		BURNT = "It's bamburnt.",
		CHOPPED = "It has a bamboo-boo.",
		GENERIC = "Cute little bamboo.",
	},
	BIGFISHINGROD = "Perhaps we'll hook something good.",
	BLOWDART_FLUP = "I can't imagine this would hurt very much.",
	BLUBBER = "Fat and happy.",
	BLUBBERSUIT = "A boy inside a spider inside a whale.",
	BOAT_TORCH = "It will light my way!",
	BRAINJELLYHAT = "It feels smart and squishy on our head.",
	BUOY = "I'm a little buoy too!",
	BUSH_VINE =
	{
		BURNT = "All burned up.",
		CHOPPED = "We took it all.",
		GENERIC = "It's a nice bush.",
	},
	COCONADE =
	{
		BURNING = "Fire in the hole!",
		GENERIC = "This will be so fun!",
	},
	COCONUT_COOKED = "Just needs a tiny umbrella.",
	COCONUT_HALVED = "Now there's one for each of us.",
	COFFEEBEANS_COOKED = "These make me feel funny.",
	COFFEEBOT = "The machine that makes the hyper juice!",
	COFFEEBUSH =
	{
		BARREN = "No more mean beans.",
		GENERIC = "It's covered in the happy beans.",
		PICKED = "We took them all.",
		WITHERED = "The bean bush looks sad.",
	},
	CORAL_BRAIN = "Yummy headmeats!",
	CORAL_BRAIN_ROCK = "I want to poke it, but I'm afraid our hand will get stuck.",
	CRAB =
	{
		CRAB = "One, two... s-six legs. Aw, we thought maybe you were a friend.",
		HIDDEN = "Come out, come out, wherever you are!",
	},
	CRATE = "Wow, a crate.",
	DEPLETED_GRASS_WATER = "All gone.",
	DOUBLE_UMBRELLAHAT = "One for each of us!",
	DOYDOYEGG_COOKED = "To make an omelette you have to endanger a few species.",
	DOYDOYEGG_CRACKED = "It cracked under the pressure.",
	DRAGOON = "It's a trailblazer!",
	DRAGOONDEN = "Maybe we'll leave that alone.",
	DRAGOONEGG = "Will it hatch soon?",
	DRAGOONHEART = "It's strangely hot.",
	DRAGOONSPIT = "Keep your bodily fluids to yourself!",
	DUG_ELEPHANTCACTUS = "Now I can use it.",
	ELEPHANTCACTUS = "It's withered, but still hurts to touch.",
	ELEPHANTCACTUS_ACTIVE = "It's made of hurt!",
	ELEPHANTCACTUS_STUMP = "Are you sleeping in there?",
	FISH_MED = "It would probably be better cooked.",
	FISH_SMALL = "It's a little fishy.",
	FISH_SMALL_COOKED = "Boney.",
	FLAMEGEYSER = "The ground is angry.",
	FLOTSAM = "There must be a way to grab it.",
	FLUP = "Why is it so aggressive!",
	-- FRESHFRUITCREPES = "Cripes! We can't wait for these crepes!",
	GRASS_WATER = "It's going for a swim.",
	HAIL_ICE = "Brrr!",
	HOUNDFIRE = "It's gonna burn away all our spider hair!",
	ICEMAKER =
	{
		HIGH = "It's running pretty good!",
		LOW = "I think it needs our help.",
		NORMAL = "Looks alright to us.",
		OUT = "Dead.",
		VERYLOW = "This thing's on its last legs. Maybe it can borrow some of ours?",
	},
	JUNGLETREE =
	{
		BURNING = "Too hot!",
		BURNT = "It's not green anymore.",
		CHOPPED = "We cut it up!",
		GENERIC = "Not a bad tree.",
	},
	KNIGHTBOAT = "It's mean!",
	KRAKEN = "Run away!",
	KRAKENCHEST = "Let's open it!",
	KRAKEN_TENTACLE = "Leave me alone!",
	ROCK_LIMPET =
	{
		GENERIC = "It's covered in limpets.",
		PICKED = "All gone.",
	},
	LIVINGJUNGLETREE = "Nothing out of the ordinary here.",
	LOBSTER_DEAD = "It's not moving anymore.",
	LOBSTER_DEAD_COOKED = "Yum, yum, yum!",
	LUGGAGECHEST = "Better finish packing.",
	MAGIC_SEAL = "Woah, magic-y!",
	MAGMAROCK = "It's a bunch of stony stones.",
	MAGMAROCK_FULL = "It's a bunch of stony stones.",
	MAGMAROCK_GOLD = "It's a bunch of shiny stones.",
	MAGMAROCK_GOLD_FULL = "It's a bunch of shiny stones.",
	MANGROVETREE = "It would be a cool place for a treehouse.",
	MANGROVETREE_BURNT = "So no treehouse, then.",
	MARSH_PLANT_TROPICAL = "It looks like a weed.",
	MERMFISHER = "Half-human, half-animal. Too weird.",
	MERMHOUSE_FISHER = "Can I come in?",
	MONKEYBALL = "We've made a friend!",
	-- MONSTERTARTARE = "Looks amazing!",
	MOSQUITOSACK_YELLOW = "The backside of a mosquito.",
	MUSSELBOUILLABAISE = "About as appetizing as they get.",
	MUSSEL_COOKED = "Still kind of gross.",
	MUSSEL_FARM =
	{
		GENERIC = "Yuck.",
		STICKPLANTED = "Is it done yet?",
	},
	MYSTERYMEAT = "It's a big goopy mess.",
	NEEDLESPEAR = "This could really hurt someone.",
	OCTOPUSCHEST = "Let's look inside!",
	OCTOPUSKING = "It looks friendly.",
	OXHAT = "How do we look?",
	OX_FLUTE = "It's just begging to be played!",
	OX_HORN = "We could put these on something to make it sharp.",
	PALMLEAF_HUT = "Almost as good as a spider nest.",
	PARROT_PIRATE = "As far as birds go, this one's very fashionable.",
	PEG_LEG = "This be our smackin' leg.",
	PIKE_SKULL = "We don't like that!",
	PIRATEGHOST = "As if normal pirates weren't scary enough!",
	PIRATEPACK = "A booty bundle.",
	PIRATIHATITATOR =
	{
		BURNT = "All burned up!",
		GENERIC = "This is definitely a thing. A magic pirate thing.",
	},
	PORTAL_SHIPWRECKED = "No one's going through this.",
	PRIMEAPE = "My best frenemy.",
	PRIMEAPEBARREL = "Too many monkeys.",
	RAWLING = "We like the wild ball man.",
	BARREL_GUNPOWDER = "Boom-material!",
	ROCK_OBSIDIAN = "This rock is pretty tough.",
	SAIL_STICK = "It's a stick!",
	SANDBAGSMALL = "Keeps the wet stuff out.",
	SANDBAGSMALL_ITEM = "Remember to lift with your legs... all eight of them!",
	SANDBAG = "Remember to lift with your legs... all eight of them!",
	SANDBAG_ITEM = "Remember to lift with your legs... all eight of them!",
	SANDCASTLE =
	{
		GENERIC = "That was fun!",
		SAND = "We wish we could live inside.",
	},
	SEASHELL_BEACHED = "We can hear the ocean with these. We can also hear it without them.",
	SEAWEED_COOKED = "Very salty.",
	SEAWEED_DRIED = "It sticks to the roof of our mouth!",
	SHADOWSKITTISH_WATER = "Eep!",
	SHARKITTEN = "Here kitty, kitty!",
	SHARKITTENSPAWNER =
	{
		GENERIC = "Maybe some kitties will come out and play?",
		INACTIVE = "Bland sand.",
	},
	SHARK_GILLS = "A big fish's breathing bits.",
	SHARK_TEETHHAT = "A smile to wear on our forehead!",
	SHIPWRECKED_ENTRANCE = "Let the adventure begin!",
	SHIPWRECKED_EXIT = "Bye-bye!",
	SNAKEDEN =
	{
		BURNT = "All burned up.",
		CHOPPED = "We took it all.",
		GENERIC = "It's a nice bush.",
	},
	SNAKEOIL = "It really works!",
	SAIL_SNAKESKIN = "With our sheet of gross skins, we're ready for adventure.",
	SPEAR_LAUNCHER = "Why would anyone launch a spear? Someone might get hurt.",
	SPOILED_FISH = "It's no good to anyone now.",
	SUNKBOAT = "So close, so far away.",
	SUNKEN_BOAT =
	{
		ABANDONED = "Maybe it's time to abandon ship, birdie.",
		GENERIC = "It's not much to look at.",
	},
	SUNKEN_BOAT_BURNT = "Hard to believe this thing was ever seaworthy.",
	SUNKEN_BOAT_TRINKET_1 = "It's very shiny.",
	SUNKEN_BOAT_TRINKET_2 = "Yaaaay!",
	SUNKEN_BOAT_TRINKET_3 = "We probably can't light that.",
	SUNKEN_BOAT_TRINKET_4 = "Is this a toy?",
	SUNKEN_BOAT_TRINKET_5 = "We'll boil this if we get desperate.",
	SWEETPOTATOSOUFFLE = "It's so dainty.",
	SWEET_POTATO = "You say \"po-tat-o\", I say \"dinner\"!",
	SWEET_POTATO_COOKED = "Orange foodmush.",
	SWEET_POTATO_PLANTED = "We want to eat that!",
	SWEET_POTATO_SEEDS = "We could plant these to grow more sweet potatoes.",
	SWIMMINGHORROR = "AHH!",
	TELEPORTATO_SW_BASE = "Can we eat off this?",
	TELEPORTATO_SW_BOX = "Someone's got a screw loose.",
	TELEPORTATO_SW_CRANK = "It's weird!",
	TELEPORTATO_SW_POTATO = "Aw, it's not even edible.",
	TELEPORTATO_SW_RING = "Maybe it's for hulahooping?",
	THATCHPACK = "Helps carry goodies!",
	TIDALPOOL = "It's like a fishbowl... without the bowl!",
	TIDAL_PLANT = "A little shrub.",
	TIGEREYE = "What're you looking at?",
	TRAWLNETDROPPED =
	{
		GENERIC = "What a tangled web we weave!",
		SOON = "It's going down!",
		SOONISH = "It's going down. Slowly.",
	},
	TRINKET_IA_20 = "It's very shiny.",
	TRINKET_IA_21 = "Yaaaay!",
	TRINKET_IA_22 = "What was in the bottle?",
	TRINKET_IA_23 = "Where did the words go?",
	FISH_TROPICAL = "It's pretty!",
	TUNACAN = "We left our can opener at home.",
	TURF_ASH = "Some ground that we dug up.",
	TURF_MAGMAFIELD = "Some ground that we dug up.",
	TURF_MEADOW = "Some ground that we dug up.",
	TURF_SNAKESKIN = "Some ground that we dug up.",
	TURF_SWAMP = "Some ground that we dug up.",
	TURF_TIDALMARSH = "Some ground that we dug up.",
	TURF_VOLCANO = "Some ground that we dug up.",
	TWISTER_SEAL = "Its cheeks look so pinchable!",
	VOLCANO_ALTAR =
	{
		GENERIC = "We can't use it right now.",
		OPEN = "The altar is ready for presents!",
	},
	VOLCANO_ALTAR_TOWER = "It's big!",
	VOLCANO_SHRUB = "I think it's speaking to me.",
	WALLYINTRO_DEBRIS = "Where's the rest of the ship?",
	WATERYGRAVE = "Blub blub.",
	WHALE_BUBBLES = "Which end are those coming from?",
	WHALE_TRACK = "Follow that whale!",
	WILBUR_CROWN = "We want to wear it.",
	WILBUR_UNLOCK = "He will make a nice friend.",
	WILDBORE = "I don't think he's friendly.",
	WILDBOREHEAD = "He doesn't look too happy.",
	WILDBOREHOUSE = "Muffled oinking is coming from inside.",
	WIND_CONCH = "A nice ocean breeze waits inside this shell. Well, maybe not so nice.",
	BOAT_WOODLEGS = "Ready for the open seas!",
	WOODLEGSHAT = "Yarr! Haha.",
	SAIL_WOODLEGS = "One fancy piece of cloth.",
	WOODLEGS_CAGE = "He needs our help!",
	WOODLEGS_KEY1 = "What will it open?",
	WOODLEGS_KEY2 = "This key's probably worth more than what it unlocks.",
	WOODLEGS_KEY3 = "A thing for opening other things.",
	SHIPWRECK = "A reminder to respect the sea.",
	CALIFORNIAROLL = "Hmm, something smells fishy about this!",

	--- 5C DLC ------------------------------------------------------------------------------------------------

	BOAT_ENCRUSTED = "Ready to set sail!",     
	BABYOX = "Pat pat.",
	BALLPHINHOUSE = "We'll just stay over here... and watch...",
	DORSALFIN = "Probably as close as I can get to these guys.",      
	NUBBIN = "It'll grow some hair soon.",
	CORALLARVE = "Aw, hi there.",
	RAINBOWJELLYFISH = "What do you think it eats?",
	RAINBOWJELLYFISH_PLANTED = "You look really nice!",
	RAINBOWJELLYFISH_DEAD = "Sorry, fishy.",
	RAINBOWJELLYFISH_COOKED = "I love brightly colored food!",
	RAINBOWJELLYJERKY = "Tough to chew, even with our big fangs!",
	WALL_ENFORCEDLIMESTONE = "Maybe the rubber blobs would like a playpen!",
	WALL_ENFORCEDLIMESTONE_ITEM = "We could put this down on the water.",      
	CROCODOG = "Ohh, oh no, uh, fetch??",
	POISONCROCODOG = "Leave us alone!",
	WATERCROCODOG = "Don't mind us, Mr. Dog!",     
	QUACKENBEAK = "Can it still eat me?",
	QUACKERINGRAM = "Everyone get out of our way!!",
	
	--- DLC ------------------------------------------------------------------------------------------------    

	CAVIAR = "So fancy!",
	CORMORANT = "That's a big bird!",

	PURPLE_GROUPER = "Haha! What a silly face.",
	PIERROT_FISH = "It's slippery!",
	NEON_QUATTRO = "You're so slimy!",

	PURPLE_GROUPER_COOKED = "He likes the fish heads. I don't.",
	PIERROT_FISH_COOKED = "It's not as cute anymore.",
	NEON_QUATTRO_COOKED = "Mmm, smells good!",

	FISH_FARM = 
	{
		EMPTY = "No fishies.",
		STOCKED = "We drew the sign ourself.",
		ONEFISH = "A fish! It looks lonely.",
		TWOFISH = "Fish friends!",
		REDFISH = "So many fish!",
		BLUEFISH  = "A whole school! Let's give them homework.",
	},

	ROE = "These aren't spider eggs.",
	ROE_COOKED = "Not the kind of eggs we're used to.",
	
	SEA_YARD = 
	{
		ON = "It's making the boats feel better!",
		OFF = "It won't work again until we fuel it.",
		LOWFUEL = "We gotta fill it up soon.",
	},
	SEA_CHIMINEA =
	{
		EMBERS = "It's not very hot.",
		GENERIC = "We used coral to corral the fire!",
		HIGH = "Woah! It's so hot!",
		LOW = "The fire's kinda low.",
		NORMAL = "The fire's burning alright.",
		OUT = "Fire's gone!",
	}, 

	TAR = "Eww! It's stuck in our fur!",
	TAR_EXTRACTOR =
	{
		ON = "It's running real good!",
		OFF = "It's off right now.",
		LOWFUEL = "It's running out of juice.",
															
												   
	},
	TAR_POOL = "The yucky stuff down there might be useful.",

	TARLAMP = "We could burn some tar for light.",
	TARSUIT = "Oh, oh yuck! We'll never get that out of our fur!",
	TAR_TRAP = "Yuck! It's sticky!",

	TROPICALBOUILLABAISSE = "Mmm! Tastes like food!",

	SEA_LAB = "We keep dropping our tools in the water by accident.",
	WATERCHEST = "We could keep our bath toys in it!",	
	QUACKENDRILL = "It might help us find more tar.",
	HARPOON = "It's awful sharp.",
	MUSSEL_BED = "They'd be happier in the water.",	
},
}
