return {
ACTIONFAIL =
{
	REPAIRBOAT =
	{
		GENERIC = "It's already in better shape than I am.",
	},
},
ANNOUNCE_MAGIC_FAIL = "It's not doing anything. Sigh.",
ANNOUNCE_OTHER_WORLD_PLANT = "It doesn't belong here. Just like me.",
ANNOUNCE_MESSAGEBOTTLE =
{
	"All things fade, in time...",
},
ANNOUNCE_BOAT_DAMAGED = "This vessel is damaged. I can relate.",
ANNOUNCE_BOAT_SINKING = "I will soon face a watery grave.",
ANNOUNCE_BOAT_SINKING_IMMINENT = "I surrender myself to the depths!",
ANNOUNCE_CRAB_ESCAPE = "It eluded death another day.",
ANNOUNCE_MAPWRAP_LOSECONTROL = "Watch as I sail straight into the maw of death!",
ANNOUNCE_MAPWRAP_RETURN = "I return once again to this world.",
ANNOUNCE_MAPWRAP_WARN = "Perhaps I'll sail from the edge of the earth.",
ANNOUNCE_TREASURE = "A treasure map... How exciting!",
ANNOUNCE_MORETREASURE = "Another map... Less exciting!",
ANNOUNCE_OTHER_WORLD_TREASURE = "This is a guide to a faraway land.",
ANNOUNCE_SHARX = "I am pursued by miscreants!",
ANNOUNCE_TRAWL_FULL = "The sea offers up its bounty.",
ANNOUNCE_VOLCANO_ERUPT = "Not with a bang, but with an ERUPTION!",
ANNOUNCE_WAVE_BOOST = "Joy...",
ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "The behemoth reveals itself!",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Like Ishmael, my hunt is doomed.",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "I will find you, beast!",

DESCRIBE = {
	-- PORTABLECOOKPOT_ITEM = "For when the hunger gnaws at my tiny stomach...",
	CHEFPACK = "Only a true chef knows its tricks.",
	-- PORTABLECOOKPOT = 
	-- {
		-- COOKING_LONG = "Whatever's in there isn't dead yet.",
		-- COOKING_SHORT = "It needs to boil.",
		-- DONE = "Finally, food.",
		-- EMPTY = "As empty as my soul.",
    -- },
	-- WARLY = 
    -- {
        -- GENERIC = "How are you coping, %s?",
        -- ATTACKER = "I don't trust %s. Fear makes people dangerous.",
        -- MURDERER = "%s, this is the end... for you!",
        -- REVIVER = "Abigail likes you, %s. I like your food.",
        -- GHOST = "We'll get a heart, but are you sure you want to come back, %s?",
		-- FIRESTARTER = "You must have used too much fire for your cooking, %s.",
    -- },

	SEAWEED_STALK = "They desire a watery grave.", --copied from the Wikia because I couldn't find it in the game files. -M

	LEIF_PALM = "Oh... no...", -- "A lumbering beast.",
	INVENTORYGRAVE = "Would they mind if I crawled in with them?",
	INVENTORYMOUND = "Would they mind if I crawled in with them?",
	LIMPETS_COOKED = "Depressing.",
	TROPICALFAN = "When I am still, it is as lifeless as Abigail.",
	PALMLEAF_UMBRELLA = "The sun beats down.",
	FISH_MED_COOKED = "A proper grilling puts a stop to the flopping.",
	SOLOFISH_DEAD = "It has shed its earthly tether.",
	GHOST_SAILOR = "He has found no respite.",
	-- BANANAPOP = "I used to eat these with Abigail...",
	BISQUE = "Feed the body, starve the soul...",
	-- CEVICHE = "All I taste is my sadness...",
	SEAFOODGUMBO = "A sea once teeming with life. No more.",
	SURFNTURF = "It could be worse.",
	SHARKFINSOUP = "It's tasted a mortal escape. I'll be tasting it.",
	LOBSTERDINNER = "Its death will give me life.",
	LOBSTERBISQUE = "I would like a spoon.",
	JELLYOPOP = "Death comes to us all. Sometimes on a stick.",
	CALIFORNIAROLL = "Crabbit, dressed up in a seaweed jacket.",
	AERODYNAMICHAT = "I cut through the air!",
	ANTIVENOM = "A potion to stave off the sickness.",
	ARMOR_LIFEJACKET = "I'd prefer a dry grave, thank you.",
	ARMOR_SNAKESKIN = "A jacket of dead flesh. Fashionable.",
	ARMOR_WINDBREAKER = "The wind's tendrils cannot hold me!",
	ARMORLIMESTONE = "Heavy...",
	ARMOROBSIDIAN = "Is it wise to don a suit of fire stone?",
	ARMORSEASHELL = "Armor made of the homes of dead goo.",
	BOAT_ARMOURED = "A boat that can take a bite or two.",
	BABYOX = "Youth is but a grain of sand, slipping through the hourglass.",
	BALLPHIN = "What a chipper little fellow. Does he know life has no meaning?",
	BALLPHINPOD = "Does swimming in pods stave off the loneliness of existence?",
	BAMBOO = "Green sticks... who cares...",
	BAMBOOTREE = "A long blade could part you from your life.",
	BERMUDATRIANGLE = "Dark energy courses through these mysterious portals...",
	BERRYBUSH2_SNAKE = "A snack, perchance?",
	BERRYBUSH_SNAKE = "A snack, perchance?",
	BIOLUMINESCENCE = "Life takes such curious forms! Yet death claims them all.",
	BLOWDART_POISON = "Sending ill will with a whisper.",
	BOAT_INDICATOR = "Where shall I launch my hopeless craft?",
	BOAT_LANTERN = "To see the vast nothingness in the black of night.",
	BOATCANNON = "It brings low death to high seas!",
	BOATREPAIRKIT = "This could save a boat from destruction, and me with it.",
	BOTTLELANTERN = "The light of life. Trapped.",
	BURIEDTREASURE = "Dead people's stuff.",
	BUSH_VINE = "They look as if they want to choke something.",
	SNAKEDEN = "They look as if they want to choke something.",
	CAPTAINHAT = "No living soul commands the sea...",
	BOAT_CARGO = "This transports more junk to nowhere.",
	CHIMINEA = "This shall protect a fire from the wind's prying fingers.",
	CIRCLINGSEAGULL = "Stay in the air, flying meat. There is nothing worth landing for.",
	SAIL_CLOTH = "With sail in hand I shall beat a hasty escape. But to where?",
	COCONADE = "A coconut filled with hot, fiery death.",
	COCONUT = "What secrets must this fruit hide beneath its armor?",
	COCONUT_SAPLING = "I was expecting a darker secret.",
	COFFEE = "Dark. Bitter...",
	COFFEEBEANS = "These look stimulating.",
	
	COFFEEBUSH = "This plant takes nourishment from fiery death.",
	CORAL = "The sea gives them life, and yet they stretch to escape it.",
	ROCK_CORAL = "The coral grows to escape the sea.",
	CRAB = "There is soft meat beneath that hard shell.",
	CRABHOLE = "A hole is just a grave that has yet to be covered.",
	CUTLASS = "It will feel no guilt from the kill. It is but a tool.",
	SWORDFISH_DEAD = "Its sword face couldn't save it...",
	DEPLETED_BAMBOOTREE = "It clings to life. Barely.",
	DEPLETED_BUSH_VINE = "The strangling vines have themselves been strangled.",
	DOYDOY = "This bird seems too stupid to be alive.",
	DOYDOYBABY = "How cute. And dumb.",
	DOYDOYEGG = "What a dumb egg.",
	
	DOYDOYNEST = "With each of these the island gets dumber. And meatier.",
	DUBLOON = "The currency of scallywags.",
	DUG_BAMBOOTREE = "Will you wither, or live?",
	DUG_BUSH_VINE = "Planting you again would be the true cruelty.",
	DUG_COFFEEBUSH = "Do you wish to return to the ground?",
	EARRING = "But no ear...",
	FABRIC = "I wonder if the bamboo finds this new form agreeable?",
	SAIL_FEATHER = "Those dumb birds sure make a speedy sail.",
	FIRERAIN = "Death from above!",
	FIRERAINSHADOW = "That can't be good.",
	FISHINHOLE = "The meat swims round and round. Oblivious.",
	FROG_POISON = "A poisonous lick from that and this nightmare will end.",
	GASHAT = "This hat prevents me from breathing in death.",
	GOLDENMACHETE = "What a fancy blade to ruin bamboo with!",
	ICEMAKER = "My heart makes ice too.",
	IRONWIND = "If I'm lucky I'll sail off the edge of the earth.",
	JELLYFISH = "How can such a curious thing even live?",
	JELLYFISH_COOKED = "It's sort of like gelatin.",
	JELLYFISH_DEAD = "It was a painless death. The beast had no nervous system.",
	JELLYFISH_PLANTED = "The sting isn't deadly. Only painful.",
	JELLYJERKY = "So... tough.",
	JUNGLETREESEED = "It's a parcel of potential.",
	JUNGLETREESEED_SAPLING = "There's no going back, now.",
	LAVAPOOL = "This pool churns with the volcano's anger!",
	LIMESTONENUGGET = "When coral dies it hardens into stone.",
	LIMPETS = "They eat of the rock. I eat of them.",
	
	LOBSTER = "It would taste excellent dead and smothered in butter.",
	LOBSTERHOLE = "A lobster dinner lives there.",
	BOAT_LOGRAFT = "This looks heavy, slow and dangerous.",
	MACHETE = "This is a lot of blade.",
	MESSAGEBOTTLE = "The last, desperate act of a doomed soul. In a bottle.",
	MESSAGEBOTTLEEMPTY = "Empty. Like my soul.",
	MOSQUITO_POISON = "As if bloodsucking wasn't low enough, this one leaves you sick.",
	MUSSEL = "You cannot hide beneath the waves, meat!",
	MUSSEL_STICK = "The mussels cling to this stick. Fools.",
	OBSIDIAN = "A stone forged of fire.",
	OBSIDIAN_WORKBENCH = "Ah, this is where fiery items are forged.",
	OBSIDIANAXE = "It cuts and burns.",
	OBSIDIANCOCONADE = "The tree's children will raze the world.",
	OBSIDIANFIREPIT =
	{
		EMBERS = "Don't give up, little flame!",
		GENERIC = "A flame to keep the horrors at bay.",
		HIGH = "This fire burns with passion!",
		LOW = "It's losing the will to go on.",
		NORMAL = "It burns with the anger of its maker.",
		OUT = "I'd better relight this.",
	},
	OBSIDIANMACHETE = "The blade both bites and burns.",
	SPEAR_OBSIDIAN = "Jabbing with fire.",
	OBSIDIANSPEARGUN = "I deliver fire with the pull of a trigger.",
	OX = "You are heavy with meat. Let me lighten your load.",
	PACKIM = "I would not trust him with a fish, but perhaps my junk...",
	PACKIM_FISHBONE = "A dead fish thingy. Looks important.",
	PALMLEAF = "I bet this leaf mourns its fallen tree.",
	PALMTREE =
	{
		BURNING = "I should probably step back.",
		BURNT = "It's turned a beautiful shade of black.",
		CHOPPED = "What lovely destruction.",
		GENERIC = "Its fruit bestows life, but only if I kill it.",
	},
	PALMTREE_BURNT = "It met a fiery end.",
	PALMTREE_STUMP = "Its tree torment is over.",
	PARROT = "Is it my ears, or does the creature chatter a lonesome monologue?",
	PEACOCK = "Such pretty feathers hiding tasty meat!",
	PIRATEHAT = "That hat of a cutthroat killer. I admire it.",
	PIRATIHATITATOR = "This is but a step from madness.",
	POISONHOLE = "The ground belches death.",
	BOAT_RAFT = "Perhaps if I ride upon the waves I shall join my sister.",
	BOAT_ROW = "I wonder how many leagues this can convey me?",
	SAIL_PALMLEAF = "Harness the wind and fly to... nowhere.",
	SAND = "I wonder if the sand knows of its own insignificance?",
	SANDCASTLE = "I suppose this diversion brings some comfort.",
	SANDBAG = "They hold back ruin. For a time...",
	SANDDUNE = "This looks impermanent.",
	SEAGULL = "The scavengers of land and sea.",
	SEAGULL_WATER = "As if it weren't bad enough that they foul the air.",
	SEASACK = "It slows the rot and decay.",
	SEASHELL = "Whatever used to live in this is probably dead now.",
	SEATRAP = "Come, creatures of the sea! Enjoy a lovely snack!",
	SEAWEED = "Even the sea is infested by weeds.",
	
	SEAWEED_PLANTED = "A hearty weed.",
	SHARK_FIN = "It won't be needing this anymore.",
	SHARX = "Terror of the sea!",
	SLOTMACHINE = "Ah, this seems a sensible test of fate.",
	SNAKE = "Devoid of arms or legs. I'd be angry too.",
	SNAKE_FIRE = "The children of the volcano. They breath its fire.",
	SNAKE_POISON = "The only thing worse than a snake is a poison one.",
	SNAKESKIN = "It shed its skin, with my assistance.",
	SNAKESKINHAT = "A hat of trophies, wrenched from the dead!",
	SOLOFISH = "Such graceful swimming. Such tasty flesh.",
	SPEAR_POISON = "One jab and they'll be retching.",
	SPEARGUN = "It deals death from a distance!",
	SPEARGUN_POISON = "Each shot inflicts a suffocating sickness.",
	STUNGRAY = "They fly to escape their own hideousness.",
	SUPERTELESCOPE = "I can see so much more useless nothing.",
	SWORDFISH = "This fish cuts death with its face!",
	TELESCOPE = "To peer over the horizon with an unabiding longing.",
	TIGERSHARK = "Orange striped death on water!",
	TIGERSHARKSHADOW = "Peril!",
	TORNADO = "Nature's ravenous wrath!",
	TOUCAN = "It sings a tortured song.",
	TRAWLNET = "A way to wrest items from the sea's grip.",
	TRAWLNETDROPPED = "I wonder what this net pulled from the sea?",
	TRIDENT = "The peoples that forged this are long dead.",
	TRINKET_IA_13 = "Maybe if I drank this stuff I'd return to my sister.",
	TRINKET_IA_14 = "If I pushed a pin into this doll, who would feel it?",
	TRINKET_IA_15 = "Whoever this belonged to isn't walking anymore.",
	TRINKET_IA_16 = "Whatever this belonged to met a bad end.",
	TRINKET_IA_17 = "Whoever wore this is surely dead.",
	TRINKET_IA_18 = "A remnant of a civilization lost at sea.",
	TRINKET_IA_19 = "The owner's brain has surely clouded for good by now.",
	TURBINE_BLADES = "No longer turning.",
	TURF_BEACH = "Sand does not make good grave fill.",
	TURF_JUNGLE = "A gnarled and twisted surface.",
	TWISTER = "Nature is very angry!",
	VENOMGLAND = "Their dead drop the cure to their sickness.",
	VINE = "Unruly life.",
	VOLCANO = "The mountain that spews death to the heavens!",
	VOLCANO_ALTAR = "The will of the volcano flows through this shrine!",
	VOLCANO_ALTAR_BROKEN = "Shame. No more weapons of fire to forge.",
	VOLCANO_EXIT = "Shall I leave this place of hot death?",
	VOLCANOSTAFF = "The fiery breath of the volcano is mine to command!",
	WALL_LIMESTONE = "A wall of the dead to beat back the living.",
	WALL_LIMESTONE_ITEM = "A wall made of living coral... No longer.",
	WHALE_BLUE = "It looks sad.",
	WHALE_CARCASS_BLUE = "Something this big and dead will surely stink.",
	WHALE_CARCASS_WHITE = "It is very big. And very dead.",
	WHALE_WHITE = "There is the hate of life burning in its eyes!",
	WOODLEGS_CAGE = "At least his soul escaped.",
	VOLCANO_SHRUB = "A wretched shadow of its former self.",
	ROCK_OBSIDIAN = "Do you burn to the touch?",
	ROCK_CHARCOAL = "I can't tell what you used to be.",
	DRAGOONDEN = "Cruel hearts dwell within.",

	ARMORCACTUS = "It makes me as prickly outside as I am inside!",
	BAMBOOTREE =
	{
		BURNT = "So it goes.",
		CHOPPED = "I've won this round.",
		GENERIC = "I can bend it to my will.",
	},
	BIGFISHINGROD = "Ye be warned, creatures of the sea. Death cometh to you.",
	BLOWDART_FLUP = "Now when I shoot someone a look it'll pack a punch!",
	BLUBBER = "The perfect meal for a blubbering fool.",
	BLUBBERSUIT = "Disturbing, but cozy.",
	BOAT = "It's a boat.",
	BOAT_TORCH = "How illuminating.",
	BRAINJELLYHAT = "Does this make my brain look big?",
	BUOY = "Float on, little friend.",
	BUSH_VINE =
	{
		BURNT = "I think it looks better like this.",
		CHOPPED = "Your sacrifice will not be in vain.",
		GENERIC = "It's quite pretty.",
	},
	COCONADE =
	{
		BURNING = "Fire in the hole!",
		GENERIC = "I hold someone's explosive death in my hands.",
	},
	COCONUT_COOKED = "It's a little sweet.",
	COCONUT_HALVED = "Two halves that were once whole. Where are you now, Abigail?",
	COFFEEBEANS_COOKED = "Who knew the will to live came in bean form?",
	COFFEEBOT = "I take mine black.",
	COFFEEBUSH =
	{
		BARREN = "It could use a pick me up.",
		GENERIC = "A beany gift from the heavens.",
		PICKED = "All wounds heal in time, little bush.",
		WITHERED = "I feel the same way.",
	},
	CORAL_BRAIN = "Is that what I look like inside?",
	CORAL_BRAIN_ROCK = "That's one smart-looking plant.",
	CRAB =
	{
		GENERIC = "This island has a crustacean infestation.",
		HIDDEN = "You can't hide from your problems forever. I've tried.",
	},
	CRATE = "It's just a box.",
	DEPLETED_GRASS_WATER = "No more.",
	DOUBLE_UMBRELLAHAT = "This seems excessive.",
	DOYDOYEGG_COOKED = "Not extinct yet, though not from lack of trying.",
	DOYDOYEGG_CRACKED = "This is probably a mercy.",
	DOYDOYFEATHER = "A spot of color in a dreary world.",
	DRAGOON = "Would make a lovely pet, if not for the whole \"murder\" thing.",
	DRAGOONEGG = "Hard to imagine this would birth forth such a horrific monster.",
	DRAGOONHEART = "This heart's as dead as my own, although much warmer.",
	DRAGOONSPIT = "Yuck!",
	DUG_ELEPHANTCACTUS = "Do I have to carry it?",
	ELEPHANTCACTUS = "It's sad and painful.",
	ELEPHANTCACTUS_ACTIVE = "This plant doesn't want anyone to touch it.",
	ELEPHANTCACTUS_STUMP = "It's hiding below.",
	FISH_MED = "It's been decapitated.",
	FISH_SMALL = "There are other fish in the sea. Bigger ones, hopefully.",
	FISH_SMALL_COOKED = "It will... tide... me over for now.",
	FLAMEGEYSER = "It's hot!",
	FLOTSAM = "I can't quite reach it.",
	FLUP = "That's too many eyes!",
	-- FRESHFRUITCREPES = "Could I get this a la mode?",
	GRASS_WATER = "Damp.",
	HAIL_ICE = "Frozen like my heart.",
	ICEMAKER =
	{
		HIGH = "It's in great shape.",
		LOW = "It seems a little depressed.",
		NORMAL = "It's feeling okay.",
		OUT = "It gave up.",
		VERYLOW = "It's running on fumes.",
	},
	JUNGLETREE =
	{
		BURNING = "I should probably step back.",
		BURNT = "It's turned a beautiful shade of black.",
		CHOPPED = "What lovely destruction.",
		GENERIC = "A jungle tree.",
	},
	KNIGHTBOAT = "That thing has anger issues!",
	KRAKEN = "Kneel to me, foul beast!",
	KRAKENCHEST = "What wonders lie within?",
	KRAKEN_TENTACLE = "Oh gee, I'm Quacken in my boots.",
	ROCK_LIMPET =
	{
		GENERIC = "Those look edible... sort of.",
		PICKED = "I picked it clean.",
	},
	LIVINGJUNGLETREE = "This unassuming tree looks exactly how I feel.",
	LOBSTER_DEAD = "It's met its maker. I've met my lunch.",
	LOBSTER_DEAD_COOKED = "It's a feast!",
	LUGGAGECHEST = "A very dapper item storage system.",
	MAGIC_SEAL = "It pulses with unknown power.",
	MAGMAROCK = "The earth's guts, cooled and ready for mining.",
	MAGMAROCK_FULL = "The earth's guts, cooled and ready for mining.",
	MAGMAROCK_GOLD = "The earth's guts, cooled and ready for mining.",
	MAGMAROCK_GOLD_FULL = "The earth's guts, cooled and ready for mining.",
	MANGROVETREE = "It's quite elegant.",
	MANGROVETREE_BURNT = "What a shame.",
	MARSH_PLANT_TROPICAL = "What a pathetic sprout.",
	MERMFISHER = "I commend this creature's commitment to cannibalism.",
	MERMHOUSE_FISHER = "How quaint.",
	MONKEYBALL = "It makes me feel less alone. Plus I can throw it.",
	-- MONSTERTARTARE = "Looks good, tastes horrible.",
	MOSQUITOSACK_YELLOW = "What a lovely shade of puke-yellow.",
	MUSSELBOUILLABAISE = "My mouth's watering just looking at it.",
	MUSSEL_COOKED = "I sure strongarmed this mussel.",
	MUSSEL_FARM =
	{
		GENERIC = "They don't look that tough to me.",
		STICKPLANTED = "Ha!",
	},
	MYSTERYMEAT = "That's grotesque.",
	NEEDLESPEAR = "One could end it all with this.",
	OCTOPUSCHEST = "That doesn't look like a reliable place to store things.",
	OCTOPUSKING = "I envy his contentment.",
	OXHAT = "Dashing.",
	OX_FLUTE = "That I might play a tune to soothe my troubled heart.",
	OX_HORN = "It's been severed from its owner.",
	PALMLEAF_HUT = "A welcome respite.",
	PARROT_PIRATE = "If I whispered my secrets to it, would it keep them safe?",
	PEG_LEG = "But where's the rest of the peg-person?",
	PIKE_SKULL = "I guess he chose Not-To-Be.",
	PIRATEGHOST = "A future friend of Abigail's?",
	PIRATEPACK = "This should help me carry more junk.",
	PIRATIHATITATOR =
	{
		BURNT = "Whatever it was, it's burnt now.",
		GENERIC = "I don't know what this is.",
	},
	PORTAL_SHIPWRECKED = "Like my beloved sister, I can never return.",
	PRIMEAPE = "His joviality is almost endearing. Almost.",
	PRIMEAPEBARREL = "Looks filthy.",
	RAWLING = "It speaks to me.",
	BARREL_GUNPOWDER = "This is a safety hazard. Good.",
	SAIL_STICK = "It's... a stick.",
	SANDBAGSMALL = "Dense and heavy.",
	SANDBAGSMALL_ITEM = "A bag of dirt I can carry.",
	SANDBAG_ITEM = "Looks like a back injury waiting to happen.",
	SANDCASTLE =
	{
		GENERIC = "Its beauty will undoubtedly succumb to the tide.",
		SAND = "If only molding the sands of time were so easy.",
	},
	SEASHELL_BEACHED = "She sells seashells... oh, what's the point.",
	SEAWEED_COOKED = "Better, but it's still a weed.",
	SEAWEED_DRIED = "It keeps longer like this. Tastes better too.",
	SHADOWSKITTISH_WATER = "Yikes.",
	SHARKITTEN = "I could see myself growing old with a houseful of these.",
	SHARKITTENSPAWNER =
	{
		GENERIC = "I smell... kitty litter?",
		INACTIVE = "A sizable sandpile.",
	},
	SHARK_GILLS = "No one's breathing through these now.",
	SHARK_TEETHHAT = "Chic, yet fearsome.",
	SHIPWRECKED_ENTRANCE = "Curiouser and curiouser.",
	SHIPWRECKED_EXIT = "Onward to the next adventure.",
	SNAKEDEN =
	{
		BURNT = "I think it looks better like this.",
		CHOPPED = "Your sacrifice will not be in vain.",
		GENERIC = "It's quite pretty.",
	},
	SNAKEOIL = "This fills me with a sense of mistrust.",
	SAIL_SNAKESKIN = "Gross, but efficient.",
	SPEAR_LAUNCHER = "Why throw a spear when you can shoot it?",
	SPOILED_FISH = "Farewell, chum.",
	SUNKEN_BOAT =
	{
		ABANDONED = "Are you all alone?",
		GENERIC = "Oh, the stories this ship could tell.",
	},
	SUNKEN_BOAT_BURNT = "A poetic end.",
	SUNKEN_BOAT_TRINKET_1 = "I just use it as a paperweight.",
	SUNKEN_BOAT_TRINKET_2 = "What sort of simple mind would be amused by this?",
	SUNKEN_BOAT_TRINKET_3 = "It's completely drenched.",
	SUNKEN_BOAT_TRINKET_4 = "I have no idea what that is.",
	SUNKEN_BOAT_TRINKET_5 = "What a cliche.",
	SWEETPOTATOSOUFFLE = "Delicate, but delicious.",
	SWEET_POTATO = "Sweet. Just like me.",
	SWEET_POTATO_COOKED = "Would that my despair tasted half so sweet.",
	SWEET_POTATO_PLANTED = "That looks like lunch.",
	SWEET_POTATO_SEEDS = "Perhaps these could give new life.",
	SWIMMINGHORROR = "I want to put some distance between myself and that!",
	TELEPORTATO_SW_BASE = "It's missing something.",
	TELEPORTATO_SW_BOX = "Looks a little screwy.",
	TELEPORTATO_SW_CRANK = "It seems incomplete.",
	TELEPORTATO_SW_POTATO = "What possible use could this have?",
	TELEPORTATO_SW_RING = "This ring's probably not for wearing.",
	THATCHPACK = "I was always destined to carry a heavy load.",
	TIDALPOOL = "When I gaze into this limpid pool I dream I can see Abigail.",
	TIDAL_PLANT = "It's sharp.",
	TIGEREYE = "Tyger, tyger, burning bright...",
	TRAWLNETDROPPED =
	{
		GENERIC = "What creatures will this wrest from the ocean?",
		SOON = "Its journey is almost at an end.",
		SOONISH = "It's started its journey into the depths.",
	},
	TRINKET_IA_20 = "I just use it as a paperweight.",
	TRINKET_IA_21 = "What sort of simple mind would be amused by this?",
	TRINKET_IA_22 = "Very DIY.",
	TRINKET_IA_23 = "How unfortunate.",
	FISH_TROPICAL = "It's offensively bright.",
	TUNACAN = "This is plainly false advertising.",
	TURF_ASH = "It's just ground.",
	TURF_MAGMAFIELD = "It's just ground.",
	TURF_MEADOW = "It's just ground.",
	TURF_SNAKESKIN = "It's just ground.",
	TURF_SWAMP = "It's just ground.",
	TURF_TIDALMARSH = "It's just ground.",
	TURF_VOLCANO = "It's just ground.",
	TWISTER_SEAL = "It has no awareness of the ills of this world.",
	VOLCANO_ALTAR =
	{
		GENERIC = "It's closed for business.",
		OPEN = "Let the sacrifice begin!",
	},
	VOLCANO_ALTAR_TOWER = "A beautiful altar of death.",
	WALLYINTRO_DEBRIS = "The ship has been obliterated.",
	WATERYGRAVE = "I'm not above raiding a grave for loot.",
	WHALE_BUBBLES = "Looks like a fish with a gas problem.",
	WHALE_TRACK = "Whale, ho!",
	WILBUR_CROWN = "Monarchs must have tiny heads.",
	WILBUR_UNLOCK = "His finery does nothing to mask the smell.",
	WILDBORE = "What's it got to be angry about?",
	WILDBOREHEAD = "What lovely decor.",
	WILDBOREHOUSE = "Hopefully they won't invite me in.",
	WIND_CONCH = "A terrifying force of nature contained within a delicate shell.",
	BOAT_WOODLEGS = "A seaworthy vessel if ever there was one!",
	WOODLEGSHAT = "Haughty seadog couture.",
	SAIL_WOODLEGS = "I adore the design.",
	WOODLEGS_KEY1 = "What unfortunate soul donated their bones for this?",
	WOODLEGS_KEY2 = "It probably unlocks something fancy.",
	WOODLEGS_KEY3 = "What do you open?",
	SHIPWRECK = "Its crew is probably dead...",

	BOAT_ENCRUSTED = "A vessel of aquatic death.",
	BABYOX = "Cold, vacant eyes...",
	BALLPHINHOUSE = "A wretched den of joviality.",
	DORSALFIN = "Remnants of destruction.",
	NUBBIN = "Bare and completely devoid of life.",
	CORALLARVE = "What a foul worm.",
	RAINBOWJELLYFISH = "This jellyfish is much more vibrant than the others.",
	RAINBOWJELLYFISH_PLANTED = "It seems so content.",
	RAINBOWJELLYFISH_DEAD = "Death has come for it.",
	RAINBOWJELLYFISH_COOKED = "Beautiful, even in death.",
	RAINBOWJELLYJERKY = "Its death means my life.",
	WALL_ENFORCEDLIMESTONE = "Slimy on top.",
	WALL_ENFORCEDLIMESTONE_ITEM = "It would be more useful if I placed it.",
	CROCODOG = "If I stuck my head in its jaws, that would be the end.",
	POISONCROCODOG = "Pierce me with your venomous fangs...",
	WATERCROCODOG = "A damp death awaits me...",
	QUACKENBEAK = "Its gnashing days are over.",
	QUACKERINGRAM = "I can be assertive, when need be.",

	CAVIAR = "I took their life to sustain my own.",
	CORMORANT = "She is surely an ill omen.",

	PURPLE_GROUPER = "A pitiful creature.",
	PIERROT_FISH = "The stripes symbolize its emotional imprisonment.",
	NEON_QUATTRO = "It misses its watery home.",

	PURPLE_GROUPER_COOKED = "Rest now, fish spirit.",
	PIERROT_FISH_COOKED = "Don't lose your head.",
	NEON_QUATTRO_COOKED = "I've... eaten worse...",

	FISH_FARM = 
	{
		EMPTY = "Life can't come from nothing... I need something...",
		STOCKED = "Life needs time to blossom.",
		ONEFISH = "Look, Abby. We have a visitor.",
		TWOFISH = "Abby... There's more now...",
		REDFISH = "Do they know I'm watching?",
		BLUEFISH  = "They shall never taste freedom.",
	},

	ROE = "The beginnings of life...",
	ROE_COOKED = "I spared them the pain of hatching.",
	
	SEA_YARD = 
	{
		ON = "It wards off the inevitable decay.",
		OFF = "Decay will surely come for my ships now.",
		LOWFUEL = "It is close to giving up, just like me.",
	},
	SEA_CHIMINEA =
	{
		EMBERS = "It will soon be snuffed out.",
		GENERIC = "Afloat upon its own demise.",
		HIGH = "A healthy fire rages within.",
		LOW = "It tenuously clings to this world.",
		NORMAL = "It burns, for now.",
		OUT = "Its warmth and light were fleeting.",
	}, 

	TAR = "Thick, with a stench of corruption.",
	TAR_EXTRACTOR =
	{
		ON = "It is pulling sludge from the depths.",
		OFF = "It's off...",
		LOWFUEL = "It won't last much longer. Me neither.",
	},
	TAR_POOL = "Corruption oozes from beneath.",

	TARLAMP = "It takes vileness and makes it light.",
	TARSUIT = "To make my outside match my inside.",
	TAR_TRAP = "A recipe for a slow painful death.",
	TROPICALBOUILLABAISSE = "A brief respite from the hunger.",

	SEA_LAB = "Do I dare plumb the sea's dark knowledge?",
	WATERCHEST = "Treasures suspended over the bottomless abyss.",
	QUACKENDRILL = "Corruption spills forth from the depths.",
	HARPOON = "It brings naught but death.",
	MUSSEL_BED = "They yearn for the deep.",
},
}
