return {
ACTIONFAIL = {
	REPAIRBOAT =
	{
		GENERIC = "Tip top!",
	},
	READ =
	{
		NOBIRDS = "The birds are not keen on this weather.",
	},
},
ANNOUNCE_OTHER_WORLD_PLANT = "This environment does not meet the basic conditions for this plant to thrive.",
ANNOUNCE_MESSAGEBOTTLE =
{
	"Illegible chickenscratch.",
},
ANNOUNCE_BOAT_DAMAGED = "My vessel is deteriorating!",
ANNOUNCE_BOAT_SINKING = "I do believe this boat is sinking.",
ANNOUNCE_BOAT_SINKING_IMMINENT = "I had best head for shore! Now!",
ANNOUNCE_CRAB_ESCAPE = "Clever crustacean!",
ANNOUNCE_MAPWRAP_LOSECONTROL = "I'm unsure of the results of this venture.",
ANNOUNCE_MAPWRAP_RETURN = "That confirms it! This world is indeed round.",
ANNOUNCE_MAPWRAP_WARN = "The fog's inhabitants remain shrouded in \"mist\"-ery. Ho ho!",
ANNOUNCE_MORETREASURE = "My, what an excess of treasure!",
ANNOUNCE_OTHER_WORLD_TREASURE = "These coordinates do not pertain to this world.",
ANNOUNCE_SHARX = "Houndus Selachii! What a fascinating nuisance.",
ANNOUNCE_TRAWL_FULL = "The net can contain no more.",
ANNOUNCE_TREASURE = "Behold! Gold.",
ANNOUNCE_VOLCANO_ERUPT = "The earth's mantle is churning!",
ANNOUNCE_WAVE_BOOST = "Prime oceanic oscillations!",
ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "What lies past those bubbles?!",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Hmm, the creature has retreated into the depths.",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "I've lost the trail in these turbulent waters!",

DESCRIBE = {
	-- PORTABLECOOKPOT_ITEM = "It will be nice to eat some properly prepared food.",
	CHEFPACK = "Perfectly insulated.",
	-- PORTABLECOOKPOT = 
	-- {
        -- COOKING_LONG = "It's got a bit to go before it's ready.",
        -- COOKING_SHORT = "I'll tell Warly his cooking is nearing completion.",
        -- DONE = "Supper time!",
        -- EMPTY = "It's one of the more sanitary kitchenware I've seen. Apt to cook a fine meal.",
    -- },
	-- WARLY = 
    -- {
        -- GENERIC = "Ah, greetings dear %s!",
        -- ATTACKER = "You're not cooking up trouble, are you %s?",
        -- MURDERER = "I will defend myself from you, foul cad!",
        -- REVIVER = "I appreciate your commitment to group survival, %s.",
        -- GHOST = "%s, don't watch that crock pot of yours too closely now. Tsk.",
		-- FIRESTARTER = "Lighting fires are we now, %s? Keep your crock pot enclosed.",
    -- },

	SEAWEED_STALK = "I've always wanted to become a water-based horticulturist.", --copied from the Wikia because I couldn't find it in the game files. -M

    LEIF_PALM = "Fascinating... it's become bipedal!", --"I... don't even know.",
	BABYOX = "The young's odor wards off predators. And myself.",
	-- BANANAPOP = "Well, isn't that refreshing?",
	BISQUE = "Just what I needed.",
	-- CEVICHE = "Could use a little more sauce.",
	SEAFOODGUMBO = "I can feel the heartburn already!",
	SURFNTURF = "The perfect dish.",
	SHARKFINSOUP = "I may have meddled with a delicate ecosystem to make this.",
	LOBSTERDINNER = "How decadent.",
	LOBSTERBISQUE = "I'd almost forgotten what real food tasted like.",
	JELLYOPOP = "Takes me back to my youth. Sort of.",
	TROPICALFAN = "Its aerodynamic principals are astonishing.",
	PALMLEAF_UMBRELLA = "A leafy parasol that will provide moderate protection.",

	SOLOFISH_DEAD = "A shame.",
	FISH_MED_COOKED = "Beautifully grilled.",
	WHALE_WHITE = "A white whale! If only there were a book about such a thing!",

	AERODYNAMICHAT = "Somewhat prehistoric looking.",
	ANTIVENOM = "The contents should make a most useful antidote.",
	ARMORCACTUS = "This allows for anonymity among the cacti.",
	ARMORLIMESTONE = "A suit of skeletal fragments from the ocean floor.",
	ARMOROBSIDIAN = "Be careful, it's sharp!",
	ARMORSEASHELL = "Prevents infirmity from venomous bites.",
	ARMOR_LIFEJACKET = "Safety first!",
	ARMOR_SNAKESKIN = "Fauna-inspired rainwear.",
	ARMOR_WINDBREAKER = "Pink is not really my color.",
	BOAT_ARMOURED = "A strong vessel.",
	BALLPHIN = "What an adorable cetacean!",
	BAMBOO = "A useful material of high tensile strength.",
	BAMBOOTREE =
	{
		BURNT = "Pity.",
		CHOPPED = "Shall we see how fast it regenerates?",
		GENERIC = "Bamboo is among the fastest growing plants in the world.",
	},
	BERMUDATRIANGLE = "I don't believe in mysterious occurrences.",
	BIGFISHINGROD = "Access to the aquatic food chain.",
	BIOLUMINESCENCE = "Fascinating, beautiful marine biology.",
	BLOWDART_FLUP = "I prefer the flup in this form.",
	BLOWDART_POISON = "To destroy my foes from the inside out.",
	BLUBBER = "A buoyant and lipid-rich substance.",
	BLUBBERSUIT = "My mother would have been proud, I've put so much meat on my bones!",
	BOAT = "Where did this vessel come from?",
	BOATCANNON = "For combat at sea, I presume.",
	BOATREPAIRKIT = "Extends the life of aquatic vessels.",
	BOAT_LANTERN = "My oceanic night light.",
	BOAT_TORCH = "To better observe the nocturnal sea life.",
	BOOK_METEOR = "Rainus Magmus!",
	BOTTLELANTERN = "A portable source of illumination.",
	BRAINJELLYHAT = "Bright ideas shape the future!",
	BUOY = "Provides a bit of comfort out at sea, does it not?",
	BURIEDTREASURE = "My curiosity is getting the better of me!",
	BUSH_VINE =
	{
		BURNT = "Charred matter.",
		CHOPPED = "The stems will grow with time.",
		GENERIC = "A scandent flora.",
	},
	CAPTAINHAT = "The cap of a true boatswoman.",
	BOAT_CARGO = "I can store a few extra books aboard.",
	CHIMINEA = "Invented by an astute meteorologist!",
	SAIL_CLOTH = "An organic form of transportation.",
	COCONADE =
	{
		BURNING = "Count down to combustion!",
		GENERIC = "Explosives make me a tad uneasy.",
	},
	COCONUT = "The seed of Arecaceae. Enormous!",
	COCONUT_SAPLING = "Arecaceae has taken root.",
	COCONUT_COOKED = "Coconut flesh, quite delicious.",
	COCONUT_HALVED = "I managed to pry past its outer defenses.",
	COFFEE = "I do love a cup of coffee and a good book.",
	COFFEEBEANS = "Very high in caffeine.",
	COFFEEBEANS_COOKED = "Ahh, that roast smells delightful.",
	COFFEEBOT = "It produces coffee.",
	COFFEEBUSH =
	{
		BARREN = "It is not flowering at this time.",
		GENERIC = "Coffea genus.",
		PICKED = "Bean gone awhile now.",
		WITHERED = "It is too hot for the Coffea plant.",
},
	CORAL = "A chunk of calcium carbonate.",
	ROCK_CORAL = "I adore marine invertebrates!",
	CORAL_BRAIN = "Ingenious!",
	CORAL_BRAIN_ROCK = "Mussidae Brainus.",
	CRAB =
	{
		GENERIC = "Crabbits have an abnormally thick exoskeleton.",
		HIDDEN = "Attention please, crabbit!",
	},
	CRABHOLE = "A burrowing creature resides here.",
	CRATE = "What's inside?",
	CUTLASS = "Careful, it's sharp.",
	SWORDFISH_DEAD = "Looks a tad less ferocious this way.",
	DEPLETED_BAMBOOTREE = "Future regrowth is not an impossibility.",
	DEPLETED_BUSH_VINE = "Future regrowth is not an impossibility.",
	DEPLETED_GRASS_WATER = "Future regrowth is not an impossibility.",
	DOUBLE_UMBRELLAHAT = "Two tiers of shelter!",
	DOYDOY = "What a fascinating species!",
	DOYDOYBABY = "Reproduction has begun.",
	DOYDOYEGG = "Nature always finds a way.",
	DOYDOYEGG_COOKED = "Green eggs and ham.",
	DOYDOYEGG_CRACKED = "I'm so curious...",
	DOYDOYFEATHER = "A bit of plumage.",
	DOYDOYNEST = "Is it a decoy device?",
	DRAGOON = "These reptiles can withstand great temperatures.",
	DRAGOONDEN = "Could use a little tidying up.",
	DRAGOONEGG = "What could be living within this igneous rock?",
	DRAGOONHEART = "Dissection complete.",
	DRAGOONSPIT = "Mind yourself on that!",
	DUBLOON = "Aha! The currency of pirates.",
	DUG_BAMBOOTREE = "It requires soil to grow.",
	DUG_BUSH_VINE = "It requires soil to grow.",
	DUG_COFFEEBUSH = "It requires soil to grow.",
	DUG_ELEPHANTCACTUS = "It requires soil to grow.",
	EARRING = "Not my style.",
	ELEPHANTCACTUS = "A succulent atop the volcano! Most interesting.",
	ELEPHANTCACTUS_ACTIVE = "Its defenses are up!",
	ELEPHANTCACTUS_STUMP = "This plant is hibernating.",
	FABRIC = "A very fine weave.",
	SAIL_FEATHER = "Sail plumage.",
	FISHINHOLE = "I spy aquatic ectothermic creatures below!",
	FISH_MED = "An odorous slab of fish meat.",
	FISH_SMALL = "Fish flesh.",
	FISH_SMALL_COOKED = "Most nutritious.",
	FLAMEGEYSER = "What a stunning display!",
	FLOTSAM = "How might I retrieve that?",
	FLUP = "Keep that tongue to yourself!",
	-- FRESHFRUITCREPES = "Sticky fingers will ensue.",
	FROG_POISON = "Watch out!",
	GASHAT = "The calcium carbonate purifies the surrounding air particles.",
	GOLDENMACHETE = "The most malleable of metals, but let's see how it slices.",
	GRASS_WATER = "I can see the roots below the water.",
	HAIL_ICE = "Some storms have produced hail the size of cantaloupes.",
	HOUNDFIRE = "High temperatures! Take caution!",
	ICEMAKER =
	{
		HIGH = "Icetastic!",
		LOW = "Its pace is dropping.",
		NORMAL = "The output is quite regular.",
		OUT = "It's out of energy.",
		VERYLOW = "Nearly empty.",
	},
	INVENTORYGRAVE = "The pockets of explorers past.",
	INVENTORYMOUND = "The pockets of explorers past.",
	IRONWIND = "Now this is boating!",
	JELLYFISH = "Jellyfish, the most ancient of multi-organ creatures.",
	JELLYFISH_COOKED = "I have made it edible with a controlled chemical reaction.",
	JELLYFISH_DEAD = "Mind you don't step in that.",
	JELLYFISH_PLANTED = "Polyp-y.",
	JELLYJERKY = "What an inventive preserve.",
	JUNGLETREE =
	{
		BURNING = "It is burning.",
		BURNT = "A carbonized tree.",
		CHOPPED = "It has been harvested.",
		GENERIC = "This species grows to great heights!",
	},
	JUNGLETREESEED = "A seed, indeed.",
	JUNGLETREESEED_SAPLING = "It is thriving.",
	KNIGHTBOAT = "What a puzzling, mechanical sea horse!",
	KRAKEN = "Octopodes have numerous defensive strategies.",
	KRAKENCHEST = "I could take a calculated guess at what's within. But only a guess.",
	KRAKEN_TENTACLE = "Mind the muscular hydrostats!",
	LAVAPOOL = "I won't be wading in that pool.",
	LIMESTONENUGGET = "Commonly used in architecture.",
	ROCK_LIMPET =
	{
		GENERIC = "This boulder is home to various gastropods.",
		PICKED = "The snails have already been harvested.",
	},
	LIMPETS = "Patella vulgata.",
	LIMPETS_COOKED = "Cooked Patella vulgata.",
	LIVINGJUNGLETREE = "Magic botany at its finest.",
	LOBSTER = "A most interesting invertebrate.",
	LOBSTERHOLE = "Home to the arthropod.",
	LOBSTER_DEAD = "I might as well eat it now.",
	LOBSTER_DEAD_COOKED = "Dinner is served!",
	BOAT_LOGRAFT = "Crude nautical transport.",
	LUGGAGECHEST = "Someone has lost their luggage.",
	MACHETE = "Used for hacking through the brush.",
	MAGIC_SEAL = "The young seal has left a gift!",
	MAGMAROCK = "What lies beneath?",
	MAGMAROCK_FULL = "What lies beneath?",
	MAGMAROCK_GOLD = "This formation contains veins of gold.",
	MAGMAROCK_GOLD_FULL = "This formation contains veins of gold.",
	MANGROVETREE = "This tree species is salt tolerant!",
	MANGROVETREE_BURNT = "It will not regrow at this stage.",
	MARSH_PLANT_TROPICAL = "Plantae greenus.",
	MERMFISHER = "This one has sophisticated harvesting skills.",
	MERMHOUSE_FISHER = "An amphibious shack.",
	MESSAGEBOTTLE = "I am intrigued!",
	MESSAGEBOTTLEEMPTY = "I do like when there is a manuscript inside.",
	MONKEYBALL = "My primate decoy.",
	-- MONSTERTARTARE = "Monster meat, dressed up fancy.",
	MOSQUITOSACK_YELLOW = "A healing substance.",
	MOSQUITO_POISON = "The sting of that insect injects a nasty poison.",
	MUSSEL = "Clamus wetus. Very nutritious.",
	MUSSELBOUILLABAISE = "Clam soup.",
	MUSSEL_COOKED = "Don't eat the shell, dear.",
	MUSSEL_FARM =
	{
		GENERIC = "I can't quite reach them from here.",
		STICKPLANTED = "And now we wait! Nature will take its course.",
	},
	MUSSEL_STICK = "To harvest mollusks.",
	MYSTERYMEAT = "Regurgitated sea life. None for me, thanks.",
	NEEDLESPEAR = "Think like a cactus.",
	OBSIDIAN = "A derivative of volcanic lava.",
	OBSIDIANAXE = "This tool generates its own heat.",
	OBSIDIANCOCONADE = "A very powerful explosive projectile.",
	OBSIDIANFIREPIT =
	{
		GENERIC = "To keep quite warm.",
		OUT = "I can re-light it.",
		EMBERS = "The fire has almost self-extinguished.",
		LOW = "The fire could use some more fuel.",
		NORMAL = "Perfect light for reading a book.",
		HIGH = "That fire is burning at an alarming rate.",
	},
	OBSIDIANMACHETE = "This tool generates its own heat.",
	OBSIDIANSPEARGUN = "This tool generates its own heat.",
	OBSIDIAN_WORKBENCH = "Just the spot to learn volcanic craftsmanship.",
	OCTOPUSCHEST = "Looks as though it's been sitting at the bottom of a reef.",
	OCTOPUSKING = "He is the center of this ecosystem.",
	OX = "They do become a bit smelly when wet.",
	OXHAT = "A sturdy head covering.",
	OX_FLUTE = "Its music stirs Mother Nature.",
	OX_HORN = "The lumbering mammal dropped this horn.",
	PACKIM = "Hello, feathered apprentice!",
	PACKIM_FISHBONE = "What sort of fish was this?",
	PALMLEAF = "It fell from the palm.",
	PALMLEAF_HUT = "Refreshing relief from the sun's relentless gaze.",
	PALMTREE =
	{
		CHOPPED = "It has been harvested.",
		BURNING = "The tree is burning.",
		BURNT = "A carbonized tree.",
		GENERIC = "I'd like to sit underneath it with a good book.",
	},
	PARROT = "It is a colorful tropical bird.",
	PARROT_PIRATE = "I wonder if he can read?",
	PEACOCK = "Pavo cristatus.",
	PEG_LEG = "What a curious choice of object for use as a weapon!",
	PIKE_SKULL = "Skeletal remains.",
	PIRATEGHOST = "Paranormal pirate activity.",
	PIRATEHAT = "When in Rome!",
	PIRATEPACK = "A treasure carrying case.",
	PIRATIHATITATOR =
	{
		BURNT = "Not very useful now, is it?",
		GENERIC = "It's a research machine, fueled by the nautical sciences.",
	},
	POISONHOLE = "Keep your distance. Airborne toxins spew out in regular intervals.",
	PORTAL_SHIPWRECKED = "I sense magic here.",
	PRIMEAPE = "These little apes are very cunning.",
	PRIMEAPEBARREL = "A monkey habitat.",
	BOAT_RAFT = "Bamboo how-to.",
	RAWLING = "Mr. Chatty Pants.",
	BARREL_GUNPOWDER = "An explosive chemical reaction will occur when its triggered.",
	ROCK_CHARCOAL = "A carbon rich resource.",
	ROCK_OBSIDIAN = "Now this is a tough nut to crack.",
	BOAT_ROW = "My vessel for marine research.",
	SAIL_PALMLEAF = "For wind-powered travel.",
	SAIL_STICK = "I can use this to my advantage in a storm.",
	SAND = "Sand always seems to find its way into my books.",
	SANDBAG = "Most absorbent.",
	SANDBAGSMALL = "Most absorbent.",
	SANDBAGSMALL_ITEM = "A flood prevention tactic.",
	SANDBAG_ITEM = "A flood prevention tactic.",
	SANDDUNE = "The dune's iconic shape is formed by the winds.",
	SANDCASTLE =
	{
		GENERIC = "I modeled it after a classic European castellum.",
		SAND = "I modeled it after a classic European castellum.",
	},
	SEAGULL = "A scavenger of the Laridae Birdus family.",
	SEAGULL_WATER = "A scavenger of the Laridae Birdus family.",
	SEASACK = "Keeps my books and provisions cool!",
	SEASHELL = "This was once the covering of a marine invertebrate.",
	SEASHELL_BEACHED = "Look what the tide brought in!",
	SEATRAP = "Place it near the creature's den.",
	SEAWEED = "I'll admit, I'm not much of a phycologist.",
	SEAWEED_COOKED = "Very high in protein.",
	SEAWEED_DRIED = "I've dried the algae.",
	SEAWEED_PLANTED = "Marine algae.",
	SHADOWSKITTISH_WATER = "Supernatural apparitions are beginning to take shape...",
	SHARKITTEN = "The offspring seem quite harmless. And cute.",
	SHARKITTENSPAWNER =
	{
		GENERIC = "I do wonder how deep the chamber goes.",
		INACTIVE = "Hibernation season.",
	},
	SHARK_FIN = "The dorsal fin functions as an aquatic stabilizer.",
	SHARK_GILLS = "Gills remove oxygen from the water. Wonderful biomechanics!",
	SHARK_TEETHHAT = "A crown of teeth.",
	SHARX = "Keep your voice down!",
	SHIPWRECKED_ENTRANCE = "A special ship for transcending worlds.",
	SHIPWRECKED_EXIT = "Is it time to depart from this tropical paradise?",
	SLOTMACHINE = "I'd wager the outcome is chancy.",
	SNAKE = "Stay back, serpent!",
	SNAKEDEN =
	{
		BURNT = "Charred matter.",
		CHOPPED = "The stems will grow with time.",
		GENERIC = "A scandent flora.",
	},
	SNAKEOIL = "The usefulness of this substance remains uncertain.",
	SNAKESKIN = "A layer of snake.",
	SNAKESKINHAT = "Rain repellent headwear!",
	SAIL_SNAKESKIN = "A sail of serpent hide.",
	SNAKE_FIRE = "It's hot!",
	SNAKE_POISON = "Beware its venomous bite.",
	SOLOFISH = "Canis fishus.",
	SPEARGUN = "I appreciate the advantage of a ranged gadget.",
	SPEARGUN_POISON = "I appreciate the advantage of a poisonous ranged gadget.",
	SPEAR_LAUNCHER = "I appreciate the advantage of a ranged gadget.",
	SPEAR_OBSIDIAN = "This tool generates its own heat.",
	SPEAR_POISON = "Now I can administer a toxic bite!",
	SPOILED_FISH = "That fish matter is becoming a biohazard.",
	STUNGRAY = "Look at that wingspan!",
	SUNKEN_BOAT =
	{
		ABANDONED = "It appears this boat did not fare well.",
		GENERIC = "What say you, Avifauna?",
	},
	SUNKEN_BOAT_BURNT = "Only blackened matter remains.",
	SUNKEN_BOAT_TRINKET_1 = "A device for taking measurements.",
	SUNKEN_BOAT_TRINKET_2 = "A lovely, tiny boat.",
	SUNKEN_BOAT_TRINKET_3 = "Appears well used.",
	SUNKEN_BOAT_TRINKET_4 = "Looks like a useful mechanical piece.",
	SUNKEN_BOAT_TRINKET_5 = "It is an old boot. I wonder where the other is?",
	SUPERTELESCOPE = "Uncovering new horizons!",
	SWEETPOTATOSOUFFLE = "Quite delicious.",
	SWEET_POTATO = "Kumara!",
	SWEET_POTATO_COOKED = "Grilled kumara.",
	SWEET_POTATO_PLANTED = "A root vegetable.",
	SWEET_POTATO_SEEDS = "To grow another root vegetable.",
	SWIMMINGHORROR = "Oh dear, I'm seeing things...",
	SWORDFISH = "Don't upset the broadbill!",
	TELEPORTATO_SW_BASE = "It is an invitation for restoration!",
	TELEPORTATO_SW_BOX = "What might this attach to?",
	TELEPORTATO_SW_CRANK = "A straw lever.",
	TELEPORTATO_SW_POTATO = "Perplexing hardware...",
	TELEPORTATO_SW_RING = "An organic nut to a bolt?",
	TELESCOPE = "It collects visible light to better my vision.",
	THATCHPACK = "I can store a few books in here.",
	TIDALPOOL = "Tidal pools are fascinating micro ecosystems!",
	TIDAL_PLANT = "A multicellular eukaryote.",
	TIGEREYE = "The ocular lens of a large creature.",
	TIGERSHARK = "Selachii Felidae. A very large one!",
	TOUCAN = "A species known for its brightly colored bill.",
	TRAWLNET = "For collecting debris at sea.",
	TRAWLNETDROPPED =
	{
		GENERIC = "Unpack the contents!",
		SOON = "It looks to be sinking.",
		SOONISH = "That net will be sunk within moments.",
	},
	TRIDENT = "A tool of ancient legend.",
	TRINKET_IA_13 = "A soda beverage can.",
	TRINKET_IA_14 = "A tribal artifact.",
	TRINKET_IA_15 = "How melodic.",
	TRINKET_IA_16 = "What does this inscription mean?",
	TRINKET_IA_17 = "It is an old boot. I wonder where the other is?",
	TRINKET_IA_18 = "It is adorned with markings.",
	TRINKET_IA_19 = "Curious...",
	TRINKET_IA_20 = "A device for taking measurements.",
	TRINKET_IA_21 = "A lovely, tiny boat.",
	TRINKET_IA_22 = "Appears well used.",
	TRINKET_IA_23 = "Don't step on it!",
	FISH_TROPICAL = "How colorful.",
	TUNACAN = "Preserved fish.",
	TURBINE_BLADES = "I'll have to research what I can do with these!",
	TURF_ASH = "The ground. You step on it.",
	TURF_BEACH = "The ground. You step on it.",
	TURF_JUNGLE = "The ground. You step on it.",
	TURF_MAGMAFIELD = "The ground. You step on it.",
	TURF_MEADOW = "The ground. You step on it.",
	TURF_SNAKESKIN = "The ground. You step on it.",
	TURF_SWAMP = "The ground. You step on it.",
	TURF_TIDALMARSH = "The ground. You step on it.",
	TURF_VOLCANO = "The ground. You step on it.",
	TWISTER = "A vortex of unyielding energy!",
	TWISTER_SEAL = "Now how did you cause all that trouble?",
	VENOMGLAND = "A useful substance for poison prevention.",
	VINE = "A common jungle vine.",
	VOLCANO = "Tectonic activity at its finest!",
	VOLCANOSTAFF = "I can feel it rumbling with volcanic pressure.",
	VOLCANO_ALTAR =
	{
		GENERIC = "A link to the volcano's core.",
		OPEN = "What shall I present it with?",
	},
	VOLCANO_ALTAR_BROKEN = "It appears permanently disabled.",
	VOLCANO_ALTAR_TOWER = "A grand structure.",
	VOLCANO_EXIT = "The return to more comfortable temperatures!",
	VOLCANO_SHRUB = "This tree has been scorched from the heat.",
	WALLYINTRO_DEBRIS = "Remains of a sea vessel.",
	WALL_LIMESTONE = "A bit of protection.",
	WALL_LIMESTONE_ITEM = "For limestone construction.",
	WATERYGRAVE = "I wonder how long it's been drifting at sea?",
	WHALE_BLUE = "I do love marine mammals!",
	WHALE_BUBBLES = "Something big lies beneath.",
	WHALE_CARCASS_BLUE = "Break down begins.",
	WHALE_CARCASS_WHITE = "There is a harpoon still stuck inside.",
	WHALE_TRACK = "Follow the path of this cetacean!",
	WILBUR_CROWN = "Who might this have belonged to?",
	WILBUR_UNLOCK = "Excuse me, monkey, do you require assistance?",
	WILDBORE = "Suidae swine is looking grim.",
	WILDBOREHEAD = "It appears a dissection took place here.",
	WILDBOREHOUSE = "A shelter for the bore.",
	WIND_CONCH = "With a song that moves atmospheric pressures.",
	BOAT_WOODLEGS = "A pirate ship.",
	WOODLEGSHAT = "It would better suit a pirate than I.",
	SAIL_WOODLEGS = "A pirate sail.",
	WOODLEGS_CAGE = "How did you get in there, scruffy sir?",
	WOODLEGS_KEY1 = "A skull key...",
	WOODLEGS_KEY2 = "Which lock does this activate?",
	WOODLEGS_KEY3 = "A key of great curiosity.",
	SHIPWRECK = "This ship got caught in a storm. Now it belongs to the sea.",
	CALIFORNIAROLL = "Delicious makizushi.",

	--- 5C DLC ------------------------------------------------------------------------------------------------
 
	BOAT_ENCRUSTED = "Large surface area and natural buoyancy make it an excellent vessel.",
	BABYOX = "Aren't you a handsome widdle gentleman!",
	BALLPHINHOUSE = "The den of a marine mammal pod.",
	DORSALFIN = "The dorsal fin of a friendly cetacean.",
	NUBBIN = "The base of a future coral bloom.",
	CORALLARVE = "The polyp of a marine invertebrate.",
	RAINBOWJELLYFISH = "A rather vibrant member of the Mudesozoa subphylum.",
	RAINBOWJELLYFISH_PLANTED = "I believe it feeds on the local bioluminescence.",
	RAINBOWJELLYFISH_DEAD = "A deceased Medusozoa.",
	RAINBOWJELLYFISH_COOKED = "A thoroughly cooked Medusozoa specimen.",
	RAINBOWJELLYJERKY = "A reliable source of desert island protein.",
	WALL_ENFORCEDLIMESTONE = "The seaweed is just decorative. Like a doily.",
	WALL_ENFORCEDLIMESTONE_ITEM = "Ready for placement.",
	CROCODOG = "You had best behave!",
	POISONCROCODOG = "Its saliva contains a nasty venom.",
	WATERCROCODOG = "I am wholly unfamiliar with the species.",
	QUACKENBEAK = "If that brute can't hold its mouth then I will.",
	QUACKERINGRAM = "Sometimes brute force is necessary.",

	--- DLC ------------------------------------------------------------------------------------------------    

	CAVIAR = "Differentiated from roe chiefly by the jar.",
	CORMORANT = "What a handsome Phalacrocoracidae!",

	PURPLE_GROUPER = "Part of the Epinephelinae family.",
	PIERROT_FISH = "Hmm... I can't seem to identify this species.",
	NEON_QUATTRO = "Closely related to Paracheirodon innesi.",

	PURPLE_GROUPER_COOKED = "Eating unprepared fish just wouldn't be safe.",
	PIERROT_FISH_COOKED = "Fish are host to all sorts of parasites, you know.",
	NEON_QUATTRO_COOKED = "A cousin of Paracheirodon innesi, ready for dinner.",

	FISH_FARM = 
	{
		EMPTY = "I must find roe if I'm to raise captive fish.",
		STOCKED = "The fish roe will mature soon.",
		ONEFISH = "Domestication was a success!",
		TWOFISH = "It seems to be doing quite well.",
		REDFISH = "My, what a yield!",
		BLUEFISH  = "How studious. They've formed a whole school.",
	},

	ROE = "The first stage in the fish life cycle.",
	ROE_COOKED = "The first and last stages of this life cycle.",
	
	SEA_YARD = 
	{
		ON = "It's at peak performance.",
		OFF = "I must procure a new fuel source.",
		LOWFUEL = "The fuel is running quite low.",
	},
	SEA_CHIMINEA =
	{
		EMBERS = "I risk losing my fire without more fuel.",
		GENERIC = "That should serve my purposes nicely.",
		HIGH = "Quite the blaze!",
		LOW = "It's getting a touch low.",
		NORMAL = "It's burning quite well.",
		OUT = "It will need to be relit.",
	}, 

	TAR = "Historically used for waterproofing ships.",
	TAR_EXTRACTOR =
	{
		ON = "I must remember to switch it off when done.",
		OFF = "I must switch it on to begin tar extraction.",
		LOWFUEL = "I'll need to refuel it if I want more tar.",
	},
	TAR_POOL = "It appears to be a natural tar well.",

	TARLAMP = "Tar ought to combust quite well in this.",
	TARSUIT = "Effective, but not very durable.",
	TAR_TRAP = "Well, anyone ensnared will preserve quite nicely.",

	TROPICALBOUILLABAISSE = "An inventive twist on a traditional Marseille dish.",

	SEA_LAB = "A dedicated scholar can study anywhere.",
	WATERCHEST = "A buoy I repurposed as a storage device.",
	QUACKENDRILL = "An implement of deepwater drilling.",
	HARPOON = "I do hope my throwing arm's not rusty.",
	MUSSEL_BED = "These mollusks will be sure to thrive once planted.",
},
}
