return {
ACTIONFAIL =
{
	REPAIRBOAT =
	{
		GENERIC = "Ugh, why would I do that now?",
	},
},
ANNOUNCE_MAGIC_FAIL = "Why won't it work!!",
ANNOUNCE_VOLCANO_ERUPT = "The fiery mountain speaks!",
ANNOUNCE_TREASURE = "\"X\" marks the spot!",
ANNOUNCE_CRAB_ESCAPE = "Shoot! It got away!",
ANNOUNCE_SHARX = "Hey! Stop splashing around out there!",
ANNOUNCE_MORETREASURE = "This day just got better.",
ANNOUNCE_OTHER_WORLD_TREASURE = "This doesn't look like a map of this place.",
ANNOUNCE_OTHER_WORLD_PLANT = "It won't grow. Maybe I should burn it instead.",
ANNOUNCE_MAPWRAP_WARN = "That fog looks pretty dense.",
ANNOUNCE_MAPWRAP_LOSECONTROL = "Uh oh. Which way was I going again?",
ANNOUNCE_MAPWRAP_RETURN = "I couldn't see a thing in there!",
ANNOUNCE_MESSAGEBOTTLE =
{
	"The message is faded. I can't read it.",
},
ANNOUNCE_BOAT_DAMAGED = "My boat is wounded!",
ANNOUNCE_BOAT_SINKING = "I'm going down!",
ANNOUNCE_BOAT_SINKING_IMMINENT = "Goodbye cruel world!",
ANNOUNCE_TRAWL_FULL = "My trawl is ready to reel in.",
ANNOUNCE_WAVE_BOOST = "Weeee!",
ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "Ooo, there's a big fishie nearby.",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Grr, I lost it!",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "The water's too rough to see!",

DESCRIBE = {
	-- PORTABLECOOKPOT_ITEM = "Just a dumb pot.",
	CHEFPACK = "A chef hat for a backpack!",
	-- PORTABLECOOKPOT = 
	-- {
        -- COOKING_LONG = "Don't tell Warly, but I'm gonna put things in the fire!",
		-- COOKING_SHORT = "The fire is doing its thing!",
		-- DONE = "Fire makes everything better. Mmm!",
		-- EMPTY = "All food must be cleansed with fire.",
    -- },
	-- WARLY = 
    -- {
        -- GENERIC = "Hi %s!",
        -- ATTACKER = "You're only fueling the fire, %s!",
        -- MURDERER = "Burn the murderer! And take his food!",
        -- REVIVER = "Who do ghosts call? %s! For a some good food!",
        -- GHOST = "Hey %s, I'll get you a heart if you let me use your crock pot!",
		-- FIRESTARTER = "Now that's how you start a cooking fire, %s!",
    -- },

	SEAWEED_STALK = "A bunch of soggy weeds.", --copied from the Wikia because I couldn't find it in the game files. -M

	LEIF_PALM = "I don't like you. You don't like me.", --"He looks flammable!",
	BIGFISHINGROD = "It's big.",
	INVENTORYGRAVE = "Not everyone has what it takes out here.",
	INVENTORYMOUND = "Not everyone has what it takes out here.",
	TROPICALFAN = "I dunno... it could put out some fires...",
	PALMLEAF_UMBRELLA = "It's so nice!",
	PALMTREE =
	{
		BURNING = "Wooow! So much fire!",
		BURNT = "A major improvement.",
		CHOPPED = "That took a few swings.",
		GENERIC = "You have a curious lack of branches.",
	},
	SOLOFISH_DEAD = "Time to chuck it in the fire!",
	FISH_MED_COOKED = "It actually looks kinda edible.",
	GHOST_SAILOR = "He'd probably be happier if he could make fire.",
	AERODYNAMICHAT = "Brisk movement snuffs fires.",
	ARMOR_LIFEJACKET = "But will it keep my lighter dry?",
	ARMOR_SNAKESKIN = "This coat makes me feel dangerous.",
	ARMOR_WINDBREAKER = "Wind is the enemy of fire.",
	ARMORLIMESTONE = "It's so... heavy.",
	ARMOROBSIDIAN = "Hit me and BURN!",
	ARMORSEASHELL = "Try me, baddies.",
	BOAT_ARMOURED = "Nothing's gonna take a bite out of this boat.",
	BABYOX = "You may be small, but you smell big.",
	BALLPHIN = "You don't look particularly flammable.",
	BALLPHINPOD = "A family of bouncy things.",
	BAMBOOTREE = "A stick-y shrub.",
	BERRYBUSH2_SNAKE = "Mmmmm. Berries.",--I don't think these should have diff name or examine text
	BERRYBUSH_SNAKE = "Mmmmm. Berries.",--I don't think these should have diff name or examine text
	BIOLUMINESCENCE = "It's a cold light. Not like a flame at all.",
	BLOWDART_POISON = "A sick kiss.",
	BOAT_LANTERN = "Light without a flame. I don't like it one bit.",
	BOTTLELANTERN = "The light is so cold and alien.",
	BURIEDTREASURE = "If I don't like the treasure I'll just set the chest on fire.",
	BUSH_VINE = "I bet these crackle and pop when they burn.",
	SNAKEDEN = "I bet these crackle and pop when they burn.",--I don't think these should have diff name or examine text
	CANNONSHOT = "Fire!",
	CAPTAINHAT = "I no longer have that sinking feeling.",
	BOAT_CARGO = "I can carry so many flammables on this.",
	CHIMINEA = "Do you like your house, fire? You're welcome.",
	CIRCLINGSEAGULL = "Fly into the sun, jerks.",
	SAIL_CLOTH = "Nice stitching.",
	COCONUT = "An edible tree thing.",
	COCONUT_SAPLING = "Hurry up and grow, I want the shade.",
	COCONUT_COOKED = "Mmmm, toasty.",
	COFFEE = "I suddenly feel motivated.",
	COFFEEBEANS = "These could use fire.",
	COFFEEBEANS_COOKED = "Ahhh, that aroma.",
	COFFEEBUSH = "This bush flourishes near the volcano's fire!",
	CORAL = "Pretty colors.",
	ROCK_CORAL = "I wish I had a snorkel.",
	CUTLASS = "This sword smells.",
	SWORDFISH_DEAD = "Ugh, fire would get rid of that smell.",
	DEPLETED_BAMBOOTREE = "Anymore bamboos? Helloooo?",
	DEPLETED_BUSH_VINE = "Come back!",
	DOYDOY = "There is no spark behind its eyes.",
	DOYDOYBABY = "You poor little dummy.",
	DOYDOYEGG = "Dumb egg.",
	DOYDOYEGG_COOKED = "Cooking this dumb egg was smart of me.",
	DOYDOYEGG_CRACKED = "The planet just got a little dumber.",
	DOYDOYFEATHER = "This would burn.",
	DOYDOYNEST = "A dummy is born every second.",
	DUBLOON = "Pirate monies!",
	DUG_BAMBOOTREE = "You need ground, fast.",
	DUG_BERRYBUSH2 = "Would you like to live again?",
	DUG_BUSH_VINE = "Would you like to go back into the ground?",
	DUG_COFFEEBUSH = "I know just what to do with you.",
	EARRING = "So shiny!",
	FABRIC = "Amazing what you can do with bamboo.",
	SAIL_FEATHER = "Gotta hand it to those dumdums... they make good sails!",
	FIRERAIN = "Let it rain!",
	FIRERAINSHADOW = "Here it comes!",
	FISHINHOLE = "Why here, fishies?",
	GASHAT = "I like not smelling smelly smells.",
	GOLDENMACHETE = "I don't want to scuff it up.",
	ICEMAKER = "It turns fire into ice. Boo.",
	IRONWIND = "Now we're gettin' somewhere.",
	JELLYFISH = "It's shriveling up.",
	JELLYFISH_DEAD = "Won't be stingin' anyone now.",
	JELLYFISH_COOKED = "It actually looks edible.",
	JELLYFISH_PLANTED = "I'll call you \"Jerald\".",
	JELLYJERKY = "Looks chewy.",
	JUNGLETREESEED = "A future forest fire.",
	JUNGLETREESEED_SAPLING = "A not-so-distant future forest fire.",
	LAVAPOOL = "What marvelous heat and fury!",
	LIMESTONENUGGET = "It's made of crushed, dead fishies.",
	LIMPETS = "A little lick of flame and you'll be tasty.",
	LIMPETS_COOKED = "Pretty good!",
	LOBSTERHOLE = "The happy lobster home.",
	BOAT_LOGRAFT = "Campfire wood has other uses, apparently!",
	MOSQUITO_POISON = "Shoo! Away!",
	MUSSEL = "Open up, fella.",
	MUSSEL_COOKED = "The fire opens their shells.",
	MUSSEL_STICK = "The mussels like this stick for some reason.",
	OBSIDIAN = "A fire rock!",
	OBSIDIAN_WORKBENCH = "Fire items can be forged here!",
	OBSIDIANAXE = "Such an axe! It cuts AND burns?!",
	OBSIDIANCOCONADE = "I get more \"boom\" for my buck with obsidian.",
	OBSIDIANFIREPIT =
	{
		EMBERS = "Uh oh. It's almost gone!",
		GENERIC = "I could watch it for hours.",
		HIGH = "BURN! BURN FASTER!",
		LOW = "This fire is small and boring.",
		NORMAL = "I feel so pampered!",
		OUT = "I should make the fire come back.",
	},
	OBSIDIANMACHETE = "A fire machete is a girl's best friend!",
	SPEAR_OBSIDIAN = "I poke. They burn!",
	OBSIDIANSPEARGUN = "I'll give it my best fiery shot!",
	PACKIM = "Friend or foe?",
	PACKIM_FISHBONE = "This looks meaningful.",
	PALMLEAF = "You'll burn.",
	PALMTREE_BURNT = "What a lovely smell.",
	PALMTREE_STUMP = "Another one bites the dust.",
	PARROT = "What a fiery color of red you are.",
	PIRATEHAT = "I feel so piratey.",
	PIRATIHATITATOR = "Cursed pirate magic?",
	POISONHOLE = "Nature is so gross.",
	BOAT_RAFT = "It would be unwise to light this on fire while at sea.",
	BOAT_ROW = "Rowing? Really?",
	SAIL_PALMLEAF = "It makes use of the wind.",
	SAND = "Big deal, it's sand.",
	SANDBAG = "A bag of sand.",
	SANDBAG_ITEM = "So I put this on the ground?",
	SANDDUNE = "Oh, look! It's some sand.",
	SEAGULL = "Does it fear fire? It should.",
	SEASACK = "I have to wear this soggy thing on my back?",
	SEASHELL = "Just some stupid seashell.",
	SEASHELL_BEACHED = "Just some stupid seashell.",
	SEATRAP = "C'mon, swim inside! It's cozy in there!",
	SEAWEED = "Soggy sea grass.",
	SEAWEED_COOKED = "Not bad once you add fire.",
	SEAWEED_DRIED = "Healthy jerky.",
	SEAWEED_PLANTED = "Soggy sea grass.",
	SHARX = "Jerks that swim.",
	SLOTMACHINE = "This seems like a waste of time.",
	SNAKE = "Jerks that slither.",
	SNAKE_FIRE = "We share similar interests, monster thing.",
	SNAKESKIN = "Leathery.",
	SNAKESKINHAT = "Water just runs right off it.",
	SPEAR_POISON = "I hope I don't jab myself.",
	SPEARGUN = "A handy tool upon the waves.",
	SPEARGUN_POISON = "This is almost too naughty.",
	STUNGRAY = "Now I've smelled everything.",
	SUPERTELESCOPE = "I can see to the ends of the earth.",
	SWORDFISH = "En garde!",
	TELESCOPE = "You can't hide from me now, islands!",
	TIGERSHARK = "My nightmares have come true!",
	TIGERSHARKSHADOW = "Not good! Not good!",
	TOUCAN = "I like your nose.",
	TRAWLNET = "I'll catch a bunch of wet stuff with this.",
	TRAWLNETDROPPED = "Everything is going to be wet in there.",
	TRIDENT = "This is all wet.",
	TRINKET_IA_13 = "Is this fire water? It's orange.",
	TRINKET_IA_14 = "I don't have any pins...",
	TRINKET_IA_15 = "Oh, this would burn.",
	TRINKET_IA_16 = "Litter is a terrible thing.",
	TRINKET_IA_17 = "Not my style.",
	TRINKET_IA_18 = "I wonder if this is worth anything?",
	TRINKET_IA_19 = "Brain cloud? Sounds tragic.",
	TURBINE_BLADES = "What do these do?",
	TURF_BEACH = "The ground is boring.",
	TURF_JUNGLE = "The ground is boring.",
	VENOMGLAND = "Gross! I wish I had gloves.",
	VINE = "I could use this for something. Or I could just burn it.",
	VOLCANO = "The biggest, fieriest fire in all the land!",
	VOLCANO_ALTAR = "Why would I wanna appease the volcano? Then it wouldn't shoot fire!",
	VOLCANO_ALTAR_BROKEN = "There's no way to quench the volcano's hunger now!",
	VOLCANO_EXIT = "I'd hate to leave this place...",
	VOLCANOSTAFF = "I am the goddess of fiery destruction!",
	WALL_LIMESTONE = "It's all bumpy.",
	WALL_LIMESTONE_ITEM = "You don't look like you would burn easily.",
	WHALE_BLUE = "I didn't know they even made fish that big.",
	WHALE_CARCASS_BLUE = "It's starting to spoil. Gross.",
	WHALE_CARCASS_WHITE = "Victory doesn't smell very good...",
	WHALE_WHITE = "I see fire in its eyes!",
	CRABHOLE = "Come out and play with me!",
	CRAB =
	{
		GENERIC = "Stop running away!",
		HIDDEN = "I'm pretty sure a crabbit is hiding there.",
	},
	BERMUDATRIANGLE = "I feel kinda dizzy looking at it.",
	BOATCANNON = "I wonder if I can start fires with this?",
	BOATREPAIRKIT = "This should patch up any little leaks.",
	MACHETE = "Or I could just burn my way through.",
	LUGGAGECHEST = "Ooo! I hope there are useful items inside.",
	DRAGOON = "If only I could figure out how to train one.",
	ANTIVENOM = "This'll help if I'm poisoned.",
	BAMBOO = "Looks flammable.",
	FROG_POISON = "Yuck! Stay away from me.",
	OX = "You look pretty sturdy.",
	PEACOCK = "Pretty!",
	SEAGULL_WATER = "\"Squawk\" yourself.",
	SNAKE_POISON = "Those are some pointy fangs.",
	SOLOFISH = "Doesn't seem very smart.",
	SPOILED_FISH = "Gross.",
	TWISTER = "Stay away from my precious flames!",
	SANDCASTLE =
	{
		GENERIC = "It's cute, I guess.",
		SAND = "It's a castle made of sand. A sandcastle.",
	},
	SNAKEOIL = "I'm not convinced.",
	LOBSTER = "Come here, you!",
	MESSAGEBOTTLE = "Bottled paper!",
	MESSAGEBOTTLEEMPTY = "It's a bottle.",
	SHARK_FIN = "The fin fell off.",
	VOLCANO_ALTAR =
	{
		GENERIC = "An altar to the sate the fire gods!",
		OPEN = "Ready to consume the fire!",
	},
	ELEPHANTCACTUS = "Don't rub up against me!",
	ELEPHANTCACTUS_ACTIVE = "Yowch!",
	ELEPHANTCACTUS_STUMP = "And stay down!",
	DOUBLE_UMBRELLAHAT = "If I bought this in a store I'd feel burned.",
	MUSSEL_FARM =
	{
		GENERIC = "Just out of reach.",
		STICKPLANTED = "You will be mine soon.",
	},
	WOODLEGS_CAGE = "He seems a little cagey.",

	 PIRATIHATITATOR =
	 {
		GENERIC = "This is just ridiculous.",
		BURNT = "Now it's more my style.",
	 },
	 COFFEEBUSH =
	 {
		BARREN = "It's dripped its last drop.",
		PICKED = "Aw, but I wanted another cup...",
		WITHERED = "It needs ash and love. Mostly just ash.",
		GENERIC = "Hot java from hot lava!",
	 },
	 DUG_ELEPHANTCACTUS = "I don't have to water you, right?",
	 WHALE_BUBBLES = "What's making those bubbles?",

	ARMORCACTUS = "This way I won't get burned by those cacti.",
	BAMBOOTREE =
	{
		BURNT = "Aww, can I burn it again?",
		CHOPPED = "It'll come back.",
		GENERIC = "Kindling!",
	},
	BLOWDART_FLUP = "This blows.",
	BLUBBER = "I bet this burns bright!",
	BLUBBERSUIT = "It squishes when I move...",
	BOAT = "Must. Not. Burn...!",
	BOAT_TORCH = "Strangely not for torching boats.",
	BRAINJELLYHAT = "I feel smarter, but also grosser...",
	BUOY = "Buoy, I'm glad I have this.",
	BUSH_VINE =
	{
		BURNT = "Those are fun to burn!",
		CHOPPED = "That's how you untangle them.",
		GENERIC = "I bet these crackle and pop when they burn.",
	},
	COCONADE =
	{
		BURNING = "Here we go...",
		GENERIC = "First it booms, then it burns.",
	},
	COCONUT_HALVED = "Aha! Now you're food!",
	COFFEEBOT = "It makes coffee!",
	CORAL_BRAIN = "I could learn to love the taste...",
	CORAL_BRAIN_ROCK = "Genius idea, hiding out with these dumb regular corals.",
	CRATE = "If I burn it, whatever's inside burns too...",
	DEPLETED_GRASS_WATER = "It's taking a little rest.",
	DRAGOONDEN = "A bunch of hotheads live there.",
	DRAGOONEGG = "I think this hot rock is actually a hot egg.",
	DRAGOONHEART = "Nothing like a hot meal.",
	DRAGOONSPIT = "A burning puddle of hork.",
	FISH_MED = "Needs fire!",
	FISH_SMALL = "I like sushi, but I prefer it flame-broiled.",
	FISH_SMALL_COOKED = "Fish and fire go well together.",
	FLAMEGEYSER = "Glorious...",
	FLOTSAM = "It's out there, but I'm over here.",
	FLUP = "Flup off!",
	-- FRESHFRUITCREPES = "Ooo la la.",
	GRASS_WATER = "This doesn't need to be watered.",
	HAIL_ICE = "Ugh, just melt already.",
	ICEMAKER =
	{
		HIGH = "It's fully fueled!",
		LOW = "It needs more fuel.",
		NORMAL = "Make that ice.",
		OUT = "It's out of fuel.",
		VERYLOW = "It's nearly out of fuel.",
	},
	JUNGLETREE =
	{
		BURNING = "Wow! So much fire!",
		BURNT = "A major improvement.",
		CHOPPED = "That took a few swings.",
		GENERIC = "That's a whole lot of tree to burn!",
	},
	KNIGHTBOAT = "Check out your boat, mate.",
	KRAKEN = "Kill it with fire!",
	KRAKENCHEST = "Don't mind if I do.",
	KRAKEN_TENTACLE = "Eww, stay away!",
	ROCK_LIMPET =
	{
		GENERIC = "That gross food is trying to eat that rock.",
		PICKED = "The rock won't be bothered by those suckers for a bit.",
	},
	LIVINGJUNGLETREE = "There's something odd about this tree.",
	LOBSTER_DEAD = "Edible in a pinch.",
	LOBSTER_DEAD_COOKED = "Lobster for dinner! Pinch me!",
	MAGIC_SEAL = "It's so glowy.",
	MAGMAROCK = "Magma-nificent!",
	MAGMAROCK_FULL = "Magma-nificent!",
	MAGMAROCK_GOLD = "Magma-nificent!",
	MAGMAROCK_GOLD_FULL = "Magma-nificent!",
	MANGROVETREE = "No need to water this guy.",
	MANGROVETREE_BURNT = "Burned right down to the, uh, water.",
	MARSH_PLANT_TROPICAL = "Plant-y.",
	MERMFISHER = "Ugh, bet you never get that fish smell out.",
	MERMHOUSE_FISHER = "Fish mongers.",
	MONKEYBALL = "I bet the monkeys would have a ball with this thing.",
	-- MONSTERTARTARE = "Gross!",
	MOSQUITOSACK_YELLOW = "Something disgusting dropped this.",
	MUSSELBOUILLABAISE = "Mmm, smells good!",
	MYSTERYMEAT = "Parenting is gross.",
	NEEDLESPEAR = "I could jabber on about this all day.",
	OCTOPUSCHEST = "It's filled with sea treats!",
	OCTOPUSKING = "He looks kinda dozy.",
	OXHAT = "Ox-cellent!",
	OX_FLUTE = "I hear a storm a-coming.",
	OX_HORN = "I could use an ox-tra one of these.",
	PALMLEAF_HUT = "Keeps the elements away, but it would burn so easy.",
	PARROT_PIRATE = "You're a skreechy scallywag.",
	PEG_LEG = "I haven't pegged down what this does yet.",
	PIKE_SKULL = "Nasty.",
	PIRATEGHOST = "What \"arrrr\" you?",
	PIRATEPACK = "Carrying this will build chest muscles.",
	PORTAL_SHIPWRECKED = "Time to get outta here.",
	PRIMEAPE = "Hey lil buddy, do you like to play with fire too?",
	PRIMEAPEBARREL = "What a monkey sty.",
	RAWLING = "He keeps me company.",
	BARREL_GUNPOWDER = "My favorite type of barrel!",
	ROCK_CHARCOAL = "It drops burned things!",
	ROCK_OBSIDIAN = "This rock makes me so excited, I just want to explode!",
	SAIL_STICK = "I'm the queen of this boooooat!",
	SANDBAGSMALL = "Keeps the home fires burning.",
	SANDBAGSMALL_ITEM = "Keeps the home fires burning.",
	SHADOWSKITTISH_WATER = "What's that??",
	SHARKITTEN = "Hey cutie, where's your mom?",
	SHARKITTENSPAWNER =
	{
		GENERIC = "My shark radar is burning.",
		INACTIVE = "Why is this sand dune here?",
	},
	SHARK_GILLS = "I guess it doesn't need to breathe with these anymore.",
	SHARK_TEETHHAT = "Wearing this gives me a toothy grin.",
	SHIPWRECKED_ENTRANCE = "Here goes!",
	SHIPWRECKED_EXIT = "I'm outta here.",
	SNAKEDEN =
	{
		BURNT = "Those were fun to burn!",
		CHOPPED = "That's how you untangle them.",
		GENERIC = "I bet these crackle and pop when they burn.",
	},
	SAIL_SNAKESKIN = "What a morbid sail.",
	SPEAR_LAUNCHER = "Only thing better than a spear is the gun that shoots them.",
	SUNKEN_BOAT =
	{
		ABANDONED = "Where'd they go?",
		GENERIC = "Someone out there is all wet.",
	},
	SUNKEN_BOAT_BURNT = "Double whammy.",
	SUNKEN_BOAT_TRINKET_1 = "I can't say that word!",
	SUNKEN_BOAT_TRINKET_2 = "I've put away childish things.",
	SUNKEN_BOAT_TRINKET_3 = "It wants to meet my lighter.",
	SUNKEN_BOAT_TRINKET_4 = "No idea what that is.",
	SUNKEN_BOAT_TRINKET_5 = "Not my size.",
	SWEETPOTATOSOUFFLE = "Cooked to perfection!",
	SWEET_POTATO = "A welcome change from red berries.",
	SWEET_POTATO_COOKED = "The flames definitely improved it.",
	SWEET_POTATO_PLANTED = "It would be cuter on fire!",
	SWEET_POTATO_SEEDS = "Seeds. Sweet.",
	SWIMMINGHORROR = "You can swim? Horrible!",
	TELEPORTATO_SW_BASE = "Seems like it's missing a thing or two.",
	TELEPORTATO_SW_BOX = "A part for something.",
	TELEPORTATO_SW_CRANK = "For cranking?",
	TELEPORTATO_SW_POTATO = "Wonder what it does?",
	TELEPORTATO_SW_RING = "This goes with something else, I think.",
	THATCHPACK = "Thatch you very much.",
	TIDALPOOL = "I wonder which way it would swirl if you flushed it?",
	TIDAL_PLANT = "It's a plant.",
	TIGEREYE = "Don't look at me like that!",
	TRAWLNETDROPPED =
	{
		GENERIC = "What's in the baaaag?",
		SOON = "It's going to sink soon!",
		SOONISH = "I believe that bag is sinking.",
	},
	TRINKET_IA_20 = "I can't say that word!",
	TRINKET_IA_21 = "I've put away childish things.",
	TRINKET_IA_22 = "It wants to meet my lighter.",
	TRINKET_IA_23 = "Broken what?",
	FISH_TROPICAL = "Such pretty colors.",
	TUNACAN = "Aw, but I like mine with Ballphin!",
	TURF_ASH = "Ashy.",
	TURF_MAGMAFIELD = "Explosive!",
	TURF_MEADOW = "Serene.",
	TURF_SNAKESKIN = "Gross.",
	TURF_TIDALMARSH = "Squelchy.",
	TURF_VOLCANO = "Hot footin'.",
	TWISTER_SEAL = "I've been burned by cute things before.",
	VOLCANO_ALTAR_TOWER = "A monument to fire!",
	VOLCANO_SHRUB = "You come pre-burnt!",
	WALLYINTRO_DEBRIS = "Did I do that?",
	WATERYGRAVE = "Something's fishy here.",
	WHALE_TRACK = "Where there's bubbles there's fire!",
	WILBUR_CROWN = "You'd have to have a tiny little head to fit this.",
	WILBUR_UNLOCK = "Fancy monkey.",
	WILDBORE = "Not wild about being close to this guy.",
	WILDBOREHEAD = "Blech!",
	WILDBOREHOUSE = "Add fire and you'd get BBQ!",
	WIND_CONCH = "Hope no fires get blown out.",
	BOAT_WOODLEGS = "A fine ship.",
	WOODLEGSHAT = "I don't think it was made for me.",
	SAIL_WOODLEGS = "This sail looks like it would be special to someone.",
	WOODLEGS_KEY1 = "A key to what?",
	WOODLEGS_KEY2 = "Something must be locked up somewhere.",
	WOODLEGS_KEY3 = "Another key.",
	SHIPWRECK = "Someone has regrets.",
	CALIFORNIAROLL = "Oh, goody. Fish rolled in seaweed.",
	-- BANANAPOP = "This is the opposite of burning.",
	BISQUE = "I guess I could eat that.",
	-- CEVICHE = "It's still slimy.",
	SEAFOODGUMBO = "Ew, what IS this?",
	SURFNTURF = "Ugh. This is old person food!",
	SHARKFINSOUP = "And I didn't even burn it!",
	LOBSTERDINNER = "Yummmmmmm!",
	LOBSTERBISQUE = "I'm gonna eat this entire thing!",
	JELLYOPOP = "I want twenty!",
	VOLCANO_SHRUB = "No fair! I didn't get to burn you!",
	ROCK_OBSIDIAN = "The... most... beautiful rock... I've ever... seen...",
	ROCK_CHARCOAL = "Charrific!",



	--- 5C DLC ------------------------------------------------------------------------------------------------

	BOAT_ENCRUSTED = "Crumbly.",
	BABYOX = "You stink.",
	BALLPHINHOUSE = "It's the castle of the bouncy things... A bouncy castle.",
	DORSALFIN = "It's, like... a fin, I guess?",
	NUBBIN = "Nice bald spot, rock.",
	CORALLARVE = "Haha, gross.",
	RAINBOWJELLYFISH = "Haha, it's squishy.",
	RAINBOWJELLYFISH_PLANTED = "Hey fancyfish, get over here!",
	RAINBOWJELLYFISH_DEAD = "It's still moving.",
	RAINBOWJELLYFISH_COOKED = "I wonder if the colors add flavor.",
	RAINBOWJELLYJERKY = "How is it STILL moving?!",
	WALL_ENFORCEDLIMESTONE = "I feel like this is not the most safe.",
	WALL_ENFORCEDLIMESTONE_ITEM = "I could put it down, I guess.",
	CROCODOG = "You don't look that tough.",
	POISONCROCODOG = "Back off!",
	WATERCROCODOG = "I'm watching you!",
	QUACKENBEAK = "Never stick your beak where is doesn't belong.",
	QUACKERINGRAM = "Can't stop me now!",

	--- DLC ------------------------------------------------------------------------------------------------    

	CAVIAR = "Fish eggs in a jar. Great.",
	CORMORANT = "It's got its butt in my water.",

	PURPLE_GROUPER = "You look kinda dumb.",
	PIERROT_FISH = "Found you!",
	NEON_QUATTRO = "Is living underwater as awful as it sounds?",

	PURPLE_GROUPER_COOKED = "Fire burned the grossest bits right off.",
	PIERROT_FISH_COOKED = "I burned it just right.",
	NEON_QUATTRO_COOKED = "The fire got rid of most of the fish smell.",

	FISH_FARM = 
	{
		EMPTY = "I gotta put something in there to grow fish.",
		STOCKED = "Still no fish yet.",
		ONEFISH = "Yesss! A fish!",
		TWOFISH = "Three fish are better than one.",
		REDFISH = "I feel like there could be more, though.",
		BLUEFISH  = "I'm swimming in fish!",
	},
	
	ROE = "Ughh! That's nasty!!",
	ROE_COOKED = "I cooked them, but they're still nasty.",
	
	SEA_YARD = 
	{
		ON = "It's a fixin' machine.",
		OFF = "Just a big hunka junk without fuel.",
		LOWFUEL = "Running low.",
	},
	SEA_CHIMINEA =
	{
		EMBERS = "That doesn't even count as a fire!",
		GENERIC = "Burn the sea!!",
		HIGH = "Yess!! Burn!!!",
		LOW = "That's barely even a fire!",
		NORMAL = "It's burning alright.",
		OUT = "Quick!! Relight it!",
	}, 

	TAR = "I bet that burns real good!",
	TAR_EXTRACTOR =
	{
		ON = "It's getting me fuel for burnin'! Heheheh.",
		OFF = "I guess I should turn it back on.",
		LOWFUEL = "That's gonna need more fuel.",
	},
	TAR_POOL = "There's something flammable down there.",

	TARLAMP = "I knew that goopy stuff'd burn good!",
	TARSUIT = "This might not be the safest thing to light fires in.",
	TAR_TRAP = "Would be better as a fire trap.",

	TROPICALBOUILLABAISSE = "Ughh, is there anything besides fish out here??",
	
	SEA_LAB = "Can things burn at sea?",
	WATERCHEST = "I keep all my best stuff in there.",
	QUACKENDRILL = "I can use this drill at sea.",
	HARPOON = "Just need something to throw it at.",
	MUSSEL_BED = "Guess I should chuck'em in the ocean.",
},
}
