--Putting this here and will update over time so it doesn't get corrupted again.
return {

ACTIONFAIL =
{
	REPAIRBOAT = 
	{
		GENERIC = "No further repairs needed.",
	},
	EMBARK = 
	{
		INUSE = "Ah, someone got to the dinghy before me.",
	},
	INSPECTBOAT = 
	{
		INUSE = GLOBAL.STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.STORE.INUSE
	},
},

ANNOUNCE_MAGIC_FAIL = "I don't get this magic stuff.",

ANNOUNCE_SHARX = "Something sounds wet and hungry out there.",

ANNOUNCE_TREASURE = "Buried treasure!",
ANNOUNCE_MORETREASURE = "I'm spoiled, more treasure!",
ANNOUNCE_OTHER_WORLD_TREASURE = "Doesn't look like anywhere I've been.",
ANNOUNCE_OTHER_WORLD_PLANT = "I thinks this needs a different kinda soil.",

ANNOUNCE_MESSAGEBOTTLE =
{
	"I thought *my* handwriting was bad. Ha.",
},
ANNOUNCE_VOLCANO_ERUPT = "Uh... that wasn't the antlion, was it?",
ANNOUNCE_MAPWRAP_WARN = "Lil' hazy over there.",
ANNOUNCE_MAPWRAP_LOSECONTROL = "I can't see where I'm going!",
ANNOUNCE_MAPWRAP_RETURN = "Where am I? Oh, still here.",
ANNOUNCE_CRAB_ESCAPE = "The crab buggered off.",
ANNOUNCE_TRAWL_FULL = "My net's full, time to collect!",
ANNOUNCE_BOAT_DAMAGED = "I should tape these holes up.",
ANNOUNCE_BOAT_SINKING = "I don't think tape will be enough now.",
ANNOUNCE_BOAT_SINKING_IMMINENT = "That's a lotta damage!",
ANNOUNCE_WAVE_BOOST = "Whoo nelly!",

ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "I see something blubbery over there!",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Drat. I lost the trail.",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "I can't see the bubbles over the waves.",


DESCRIBE = {
	 --SWC
	-- PORTABLECOOKPOT_ITEM = "I'm ready for some good cookin'!",
	CHEFPACK = "It'll keep all those fancy ingredients cool.",
	-- -- FRESHFRUITCREPES = "These are some fancy good eats, chef!",
	-- -- MONSTERTARTARE = "I have some complaints for the chef.",
	-- PORTABLECOOKPOT = 
	-- {
		-- COOKING_LONG = "Still got a bit of a wait.",
		-- COOKING_SHORT = "Get Warly! His cooking's almost ready!",
		-- DONE = "Soup's on!",
		-- EMPTY = "Good to have some extra hands cookin' around here.",
    -- },
	-- WARLY = 
    -- {
        -- GENERIC = "Hey there, %s. Cookin' anything good up?",
        -- ATTACKER = "%s's food must be going all to their head.",
        -- MURDERER = "Butcher! Get'em!",
        -- REVIVER = "You got a good head on your shoulders, chef.",
        -- GHOST = "Shake it off, %s, we got grub to eat!",
		-- FIRESTARTER = "Your cooking skills don't advance to forest fires, do they %s?",
    -- },
    --
	WILDBOREGUARD = "All I need's a red cape and I can have some fun. Ha!",
	SOLOFISH_DEAD = "Sorry, fella.",
	FISH_MED_COOKED = "Bone-free. I hope.",
	PURPLE_GROUPER = "What a stupid lookin' face.",
	PURPLE_GROUPER_COOKED = "Face-free.",

	GHOST_SAILOR = "Looks like that dog stayed salty. Ha!",

	FLOTSAM = "A cautionary tale of bad craftsmanship.",

	SUNKEN_BOAT = 
	{
		GENERIC = "You built this ship? No wonder it's sunk, ha!",
		ABANDONED = "Some things even I can't fix.",
	},
	SUNKEN_BOAT_BURNT = "There was nothing left for it anyway.",
	SUNKEN_BOAT_TRINKET_1 = "I don't know how to use this doohickey.", --sextant
	SUNKEN_BOAT_TRINKET_2 = "Looks like Willow's bear might get outta here.", --toy boat
	SUNKEN_BOAT_TRINKET_3 = "A light that won't light.", --candle
	SUNKEN_BOAT_TRINKET_4 = "I, uh, uhm... huh?", --sea worther
	SUNKEN_BOAT_TRINKET_5 = "A workboot with no worker attached.", --boot
	SUNKBOAT = "It's beyond my help.",
	-- BANANAPOP = "I'm used to eating bananas without sticks.",
	BISQUE = "Cold soup's on!",
	-- CEVICHE = "Delicious!",
	SEAFOODGUMBO = "Just like ma used to make.",
	SURFNTURF = "The steak's really chewy.",
	SHARKFINSOUP = "Waiter, there's a shark in my soup!",
	LOBSTERDINNER = "Pass the butter!",
	LOBSTERBISQUE = "Who knew lobster made a good soup?",
	JELLYOPOP = "The stinging's been cooked outta it.",

	BOAT_ENCRUSTED = "A naturally armored ship.",
	BABYOX = "I'm surprised it can stay above the water.",
	BALLPHINHOUSE = "I'd love to know how they built that.",
	DORSALFIN = "I hope nobody needed this.",
	NUBBIN = "It's a nub of a reef.",
	CORALLARVE = "So you're the one who built them rocks.",
	RAINBOWJELLYFISH = "Not a stinger, I guess.",
	RAINBOWJELLYFISH_PLANTED = "That guy had a bright idea. Ha!",
	RAINBOWJELLYFISH_DEAD = "Hope it's safe to eat.",
	RAINBOWJELLYFISH_COOKED = "Taste the rainbow.",
	RAINBOWJELLYJERKY = "No more glow-y stuff left.",
	WALL_ENFORCEDLIMESTONE = "I like where it is current-ly. Ha!",
	WALL_ENFORCEDLIMESTONE_ITEM = "Not as pretty as the reefs, but it's more useful.",
	CROCODOG = "Heheh. I can't take those squeaks seriously.",
	POISONCROCODOG = "Chew on this, ya mutt!",
	WATERCROCODOG = "You can't be that naturally wet.",
	QUACKENBEAK = "I've seen uglier chompers in the factory.",
	QUACKERINGRAM = "I wish I had this in city traffic!",

	CAVIAR = "I don't get the hubbub. They're just fish eggs.",
	CORMORANT = "Loud guy.",

	PURPLE_GROUPER = "What a stupid lookin' face.",
	PIERROT_FISH = "It's a flounder, isn't it?",
	NEON_QUATTRO = "Cool fish. No really, it's chilly.",

	PURPLE_GROUPER_COOKED = "Face-free.",
	PIERROT_FISH_COOKED = "It learned what a fire was.",
	NEON_QUATTRO_COOKED = "It's warmer than before.",

	FISH_FARM = 
	{
		EMPTY = "No farms work without fuel.",
		STOCKED = "The fish hasn't hatched yet.",
		ONEFISH = "Ooh, I see the little guy!",
		TWOFISH = "There's a few more!",
		REDFISH = "It's close to bursting!",
		BLUEFISH  = "It can't hold any more, time to harvest.",
	},

	ROE = "Bit small for eatin'.",
	ROE_COOKED = "Not the kinda fried eggs I'm used to.",
	
	SEA_YARD =
	{
		ON = "Now this is efficiency!",
		OFF = "Maybe I should build an automatic fueler too.",
		LOWFUEL = "I should top it off.",
	},

	SEA_CHIMINEA = 
	{
		EMBERS = "It's almost kaput.",
		GENERIC = "Keeps the fire nice and dry on the sea.",
		HIGH = "Roarin' high.",
		LOW = "It'll be out soon.",
		NORMAL = "It's nice to dry off by.",
		OUT = "I can always light it again.",
	}, 

	TAR = "Glad I'm handling this stuff with gloves.",
	TAR_EXTRACTOR =
	{
		ON = "Is there anything heavy machinery can't do?",
		OFF = "It's better to leave that thing runnin'.",
		LOWFUEL = "It needs a lil fuel.",
	},
	TAR_POOL = "The sea isn't supposed to be black, right?",

	TARLAMP = "That's a handy lil light.",
	TARSUIT = "I know it's water resistant, but come on.",
	TAR_TRAP = "Anyone have a sponge?",

	TROPICALBOUILLABAISSE = "It has different tastes each bite.",
	
	SEA_LAB = "Good thing water doesn't affect this doohickey.",
	WATERCHEST = "It looks like it's gonna sink any moment.",
	QUACKENDRILL = "Is there nothing engineering can't do?",
	HARPOON = "Looking sharp!",
	MUSSEL_BED = "These lil' workers need a new home.",
	ANTIVENOM = "Bleh, tastes like castor oil.",
	VENOMGLAND = "Haha, gross.",
	BLOWDART_POISON = "Best not breathe in while using this.",
	OBSIDIANMACHETE = "It's powered by hard work. My kind of tool.",
	SPEARGUN_POISON = "High velocity poisoning.",
	OBSIDIANSPEARGUN = "By definition, this is a flame-thrower now. Ha!",
	LUGGAGECHEST = "Could be some good loot in there.",
	PIRATIHATITATOR =
	{
		GENERIC = "That lever is STILL there...",
		BURNT = "I'll make this one over.",
	},
	COFFEEBEANS = "I should toss them over a fire.",
	COFFEE = "Essential for any hard worker!",
	COFFEEBEANS_COOKED = "Ah, the smell of coffee beans in the morning!",
	COFFEEBUSH =
	{
		BARREN = "Buddy needs some ash.",
		WITHERED = "What happened here?",
		GENERIC = "Oh, mama!",
		PICKED = "There's no beans left, aw man.",
	},
	COFFEEBOT = "The pinnacle of engineering.",
	MUSSEL = "The food's on the inside.",
	MUSSEL_FARM =
	{
		 GENERIC = "Looks like some shells from here.",
		 STICKPLANTED = "Work smarter, not harder."
	},

	MUSSEL_STICK = "Sticks can become mussels with enough work.",
	LOBSTER = "Don't get snappy with me.",
	LOBSTERHOLE = "Seems easy to make with those kinda claws.",
	SEATRAP = "It's a fancy dinner catcher.",
	SANDCASTLE =
	{
		SAND = "It definitely is a sand castle.",
		GENERIC = "Now isn't that cute."
	},
	BOATREPAIRKIT = "Who needs glue? My tape is sticky enough.",

	BALLPHIN = "Intelligent little guy.",
	BOATCANNON = "Excavation crew is here!",
	BOTTLELANTERN = "Where's the power source?",
	BURIEDTREASURE = "Today's my lucky day!",
	BUSH_VINE =
	{
		BURNING = "Oh. Welp.",
		BURNT = "Not much that crispy vines can do.",
		CHOPPED = "It's on break.",
		GENERIC = "It's real tangle-y.",
	},
	CAPTAINHAT = "Look at me, I am the captain now. Ha!",
	COCONADE =
	{
		BURNING = "Fire in the hole!",
		GENERIC = "It's definitely creative, I'll give it that.",
	},
	CORAL = "I never built with this stuff before.",
	ROCK_CORAL = "Yup, it's a colorful rock.",
	CRABHOLE = "Those crabs sure know a lot about burying themselves.",
	CUTLASS = "Clean cut on that huge schnoz.",
	
	DUBLOON = "It's not much, but at least I'm being paid.",
    FABRIC = "Glad I didn't have to tear my clothes for this.",
    FISHINHOLE = "A school of fish, getting them ready for work.",
    GOLDENMACHETE = "This just made my job easier.",
    JELLYFISH = "If you hit it, it hits back. That's the worker class!",
    JELLYFISH_DEAD = "This one won't be doing any work anymore.",
    JELLYFISH_COOKED = "Looks like a bunch of cut up onions now.",
    JELLYFISH_PLANTED = "Blob away, jelly!",
    JELLYJERKY = "Dried under the sun.",

    ROCK_LIMPET =
    {
        GENERIC = "It's full of the little grubs!",
        PICKED = "No one left to tell the story.",
    },
    BOAT_LOGRAFT = "I could do better...",
    MACHETE = "Hack and slash! Working's always fun.",
    MESSAGEBOTTLEEMPTY = "No more letters left for me.",
    MOSQUITO_POISON = "Can't afford getting bitten by this one.",
    OBSIDIANCOCONADE = "Too much fire can lead to accidents...",
    OBSIDIANFIREPIT =
    {
        EMBERS = "On its last legs.",
        GENERIC = "Like a factory furnace.",
        HIGH = "Properly roaring.",
        LOW = "It's gonna go out soon.",
        NORMAL = "About as cozy as it gets out here.",
        OUT = "My sister was afraid of the dark.",
    },-------------------------------------left off-------------------------------------
	OX = "These creatures seem reasonable.",
	PIRATEHAT = "Fit for a cutthroat scallywag. Or me.",
	BOAT_RAFT = "This looks adequate.",
	BOAT_ROW = "It runs on elbow grease.",
	SAIL_PALMLEAF = "This should really transform my boating experience.",
	SANDBAG_ITEM = "Sand technology, on the go.",
	SANDBAG = "Keeps the water at bay.",
	SEASACK = "I hate when food has that not-so-fresh taste.",
	SEASHELL_BEACHED = "Sea refuse.",
	SEAWEED = "A weed. Of the sea.",

	SEAWEED_PLANTED = "Is that what passes for food around here?",
	SLOTMACHINE = "I suppose I could linger for a moment or two.",
	SNAKE_POISON = "Even worse than a regular snake!",
	SNAKESKIN = "I'm intrigued AND repelled.",
	SNAKESKINHAT = "It should repel the rain from my hair.",
	SOLOFISH = "It has that wet-dog smell.",
	SPEARGUN = "Requires extra assembly.",--done
	SPOILED_FISH = "I'm not terribly curious about the smell.",
	SWORDFISH = "And I thought my landlord's nose was big. Ha!",--done
	TRIDENT = "I wonder how old this artifact is?",
	TRINKET_IA_13 = "What is this substance?",
	TRINKET_IA_14 = "This thing gives me the creeps...",
	TRINKET_IA_15 = "Incredible! This guitar has undergone shrinkification!",
	TRINKET_IA_16 = "How did this get all the way out here?",
	TRINKET_IA_17 = "Where's the other one?",
	TRINKET_IA_18 = "A relic of a bygone era!",
	TRINKET_IA_19 = "Clouding of the brain. Never heard of it...",
	TURBINE_BLADES = "Perhaps this powered that beastly storm?",
	TURF_BEACH = "Sandy ground.",
	TURF_JUNGLE = "Very gnarled ground.",
	VOLCANO_ALTAR =
	{
		GENERIC = "It appears to be closed.",
		OPEN = "The altar is open and ready to accept offerings!",
	},
	VOLCANO_ALTAR_BROKEN = "Er, that won't be a problem, will it?",
	WHALE_BLUE = "That whale has emotional issues.",
	WHALE_CARCASS_BLUE = "Gross. I think the bloating has begun.",
	WHALE_CARCASS_WHITE = "Gross. I think the bloating has begun.",

	ARMOR_SNAKESKIN = "How fashionable!",
	SAIL_CLOTH = "That wind isn't getting away now!",
	DUG_COFFEEBUSH = "This belongs in the ground!",
	LAVAPOOL = "A bit hot for my tastes.",
	BAMBOO = "Maybe I can bamboozle my enemies with this?",
	AERODYNAMICHAT = "It really cuts through the air!",
	POISONHOLE = "I think I'll stay away from that.",
	BOAT_LANTERN = "This will do wonders for my night vision!",
	SWORDFISH_DEAD = "I better not run with this.",
	LIMPETS = "Maybe starving wouldn't be so bad.",
	OBSIDIANAXE = "A winning combination!",
	COCONUT = "It requires a large nut hacker.",
	COCONUT_SAPLING = "It doesn't need my help to grow anymore.",
	COCONUT_COOKED = "Now I just need a cake.",
	BERMUDATRIANGLE = "Gives me an uneasy feeling.",
	SNAKE = "I wonder if it'll sell me some oil?",
	SNAKEOIL = "The label says \"Jay's Wondrous Snake Oil!\"",
	ARMORSEASHELL = "Arts and crafts!",
	SNAKE_FIRE = "Is that snake smoldering?",
	MUSSEL_COOKED = "I cook a mean mussel.",

	PACKIM_FISHBONE = "This seems like something I should carry around.",
	PACKIM = "I bet I could pack'im full of stuff.",

	ARMORLIMESTONE = "I'm sure this will hold up great!",
	TIGERSHARK = "Well that's terrifying.",
	WOODLEGS_KEY1 = "Something, somewhere must be locked.",
	WOODLEGS_KEY2 = "This key probably unlocks something.",
	WOODLEGS_KEY3 = "That's a key.",
	WOODLEGS_CAGE = "That seems like an excessive amount of locks.",
	OBSIDIAN_WORKBENCH = "I feel inspired.",

	NEEDLESPEAR = "I'm glad I didn't step on this.",
	LIMESTONENUGGET = "Could be a useful building material.",
	DRAGOON = "You're a quick one, aren't you?",

	ICEMAKER = 
	{
		OUT = "It needs more fuel.",
		VERYLOW = "I can hear it sputtering.",
		LOW = "It seems to be slowing down.",
		NORMAL = "It's putting along.",
		HIGH = "It's running great!",
	},

	DUG_BAMBOOTREE = "I need to plant this.",
	BAMBOOTREE =
	{
		BURNING = "Bye bye, bamboo.",
		BURNT = "I feel like I could have prevented that.",
		CHOPPED = "Take that, nature!",
		GENERIC = "Golly, it's even floatier than wood!", --"Looks pretty sturdy.", -Mob
	},
	
	JUNGLETREE =
	{
		BURNING = "What a waste of wood.",
		BURNT = "I feel like I could have prevented that.",
		CHOPPED = "Take that, nature!",
		GENERIC = "That tree needs a hair cut.",
	},
	SHARK_GILLS = "I wish I had gills.",
	LEIF_PALM = "Someone gimme a hand with this palm!",
	OBSIDIAN = "It's a fire rock.",
	BABYOX = "It's a tiny meat beast.",
	STUNGRAY = "I think I'll keep my distance.",
	SHARK_FIN = "A sleek fin.",
	FROG_POISON = "It looks meaner than usual.",
	BOAT_ARMOURED = "That is one durable boat.",
	ARMOROBSIDIAN = "I'm the fire hazard!",--done
	BIOLUMINESCENCE = "These make a soothing glow.",
	SPEAR_POISON = "Now it's extra deadly.",
	SPEAR_OBSIDIAN = "This will leave a mark.",
	SNAKEDEN =
	{
		BURNING = "Whoops.",
		BURNT = "I feel like I could have prevented that.",
		CHOPPED = "Take that, nature!",
		GENERIC = "It's all viney!",
	},
	TOUCAN = "I tou-can't catch him.",
	MESSAGEBOTTLE = "Someone wrote me a note!",
	SAND = "A handy pile of pocket sand.",
	SANDDUNE = "You better stay out of my shoes.",
	PEACOCK = "Nothing more than a dressed up thief.",
	VINE = "Maybe I can tie stuff up with this.",
	SUPERTELESCOPE = "I can see forever!",
	SEAGULL = "Shoo! Find some other land!",
	SEAGULL_WATER = "Shoo! Find some other water!",
	PARROT = "I find myself fresh out of crackers.",
	ARMOR_LIFEJACKET = "Keeps me afloat, without my boat!",
	WHALE_BUBBLES = "Something's underwater here.",
	EARRING = "The fewer holes in my body, the better.",
	ARMOR_WINDBREAKER = "The wind doesn't stand a chance!",
	SEAWEED_COOKED = "Crispy.",
	BOAT_CARGO = "It has room for all my stuff!",
	GASHAT = "Sucks all the stink out.",
	ELEPHANTCACTUS = "Yikes! I could poke an eye out!",
	DUG_ELEPHANTCACTUS = "A portable poker plant.",
	ELEPHANTCACTUS_ACTIVE = "That cactus seems abnormally pokey.",
	ELEPHANTCACTUS_STUMP = "It'll sprout pokers again eventually.",
	SAIL_FEATHER = "It's feather-light!",
	WALL_LIMESTONE_ITEM = "These would do more good if I placed them.",
	JUNGLETREESEED = "I can hear the hissing of tiny snakes.",
	JUNGLETREESEED_SAPLING = "It will grow into a nice jungle tree.",
	VOLCANO = "My scientific know-how tells me that's a perfectly safe mountain!",
	IRONWIND = "This is how a scientist should travel.",
	SEAWEED_DRIED = "Salty!",
	TELESCOPE = "I spy with my little eye...",
	
	DOYDOY = "I feel oddly protective of this dumb bird.",
	DOYDOYBABY = "What a cute little, uh, thing.",
	DOYDOYEGG = "Maybe I should have let it hatch.",
	DOYDOYEGG_CRACKED = "Oh well. I'm sure there are lots more!",
	DOYDOYFEATHER = "Soft AND endangered!",

	PALMTREE =
	{
		BURNING = "What a waste of wood.",
		BURNT = "I feel like I could have prevented that.",
		CHOPPED = "Take that, nature!",
		GENERIC = "How tropical.",
	},
	PALMLEAF = "I'm fond of these fronds.",
	CHIMINEA = "Keeps the fires from gettin' winded. Ha!",--done
	DOUBLE_UMBRELLAHAT = "The second umbrella keeps the first umbrella dry.",
	CRAB = 
	{
		GENERIC = "Don't get snappy with me, mister.",
		HIDDEN = "I wonder where that crabbit went?",
	},
	TRAWLNET = "Nothing but net.",
	TRAWLNETDROPPED = 
	{
		SOON = "It is definitely sinking.",
		SOONISH = "I think it's sinking.",
		GENERIC = "It's bulging with potential!",
	},
	VOLCANO_EXIT = "There's a cool breeze blowing in from outside.",
	SHARX = "These things sure are persistent.",
	SEASHELL = "Maybe I could sell these.",
	WHALE_BUBBLES = "Something down there has bad breath.",
	MAGMAROCK = "I can dig it.",
	MAGMAROCK_GOLD = "I see a golden opportunity.",
	CORAL_BRAIN_ROCK = "I wonder what it's plotting...",
	CORAL_BRAIN = "Food for thought.",
	SHARKITTEN = "You've got to be kitten me!",
	SHARKITTENSPAWNER = 
	{
		GENERIC = "Is that sand pile purring?",
		INACTIVE = "That is a rather large pile of sand.",
	},
	LIVINGJUNGLETREE = "Just like any other tree.",
	WALLYINTRO_DEBRIS = "Part of a wrecked ship.",
	MERMFISHER = "You better not try anything fishy.",
	PRIMEAPE = "Those things are going to be the end of me.",
	PRIMEAPEBARREL = "Here be evil.",
	BARREL_GUNPOWDER = "How original.",
	PORTAL_SHIPWRECKED = "It's broken.",
	MARSH_PLANT_TROPICAL = "Planty.",
	TELEPORTATO_SW_POTATO = "Seems like it was made with a purpose in mind.",
	PIKE_SKULL = "Ouch.",
	PALMLEAF_HUT = "Shade, sweet shade.",
	FISH_SMALL_COOKED = "A small bit of cooked fish.",
	LOBSTER_DEAD = "You should cook up nicely.",
	MERMHOUSE_FISHER = "Doesn't smell very good.",
	WILDBORE = "Looks aggressive.",
	PIRATEPACK = "I can keep my booty in here.",
	TUNACAN = "Where did this can come from?",
	MOSQUITOSACK_YELLOW = "Part of a yellow mosquito.",
	SANDBAGSMALL = "This should keep the water out.",
	FLUP = "Leave me alone!",
	OCTOPUSKING = "I'm a sucker for this guy.",
	OCTOPUSCHEST = "I hope that thing is waterproof.",
	GRASS_WATER = "I hope you're thirsty, grass.",
	WILDBOREHOUSE = "What a bore-ing house.",
	FISH_SMALL = "A small bit of fish.",
	TURF_SWAMP = "Swampy turf.",
	FLAMEGEYSER = "Maybe I should stand back.",
	KNIGHTBOAT = "Get off the waterway, you maniac!",
	MANGROVETREE_BURNT = "I wonder how that happened.",
	TIDAL_PLANT = "Look. A plant.",
	WALL_LIMESTONE = "Sturdy.",
	FISH_MED = "A chunk of fish meat.",
	LOBSTER_DEAD_COOKED = "I can't wait to eat you.",
	BLUBBERSUIT = "Well, it's something.",
	BLOWDART_FLUP = "Eye see.",
	TURF_MEADOW = "Meadow-y turf.",
	TURF_VOLCANO = "Volcano-y turf.",
	SWEET_POTATO = "Looks yammy!",
	SWEET_POTATO_COOKED = "Looks even yammier!",
	SWEET_POTATO_PLANTED = "That's an odd looking carrot.",
	SWEET_POTATO_SEEDS = "My very own plant eggs.",
	BLUBBER = "Squishy.",
	TELEPORTATO_SW_RING = "Looks like I could use this.",
	TELEPORTATO_SW_BOX = "It looks like a part for something.",
	TELEPORTATO_SW_CRANK = "I wonder what this is used for.",
	TELEPORTATO_SW_BASE = "I think it's missing some parts.",
	VOLCANOSTAFF = "The label says \"Keep out of reach of children.\"",
	THATCHPACK = "I call it a thatchel.",
	SHARK_TEETHHAT = "What a dangerous looking hat.",
	TURF_ASH = "Ashy turf.",
	BOAT_TORCH = "This'll keep my hands free.",
	MANGROVETREE = "I wonder if it's getting enough water?",
	HAIL_ICE = "Chilling.",
	FISH_TROPICAL = "What a tropical looking fish.",
	TIDALPOOL = "A pool, left by the tides.",
	WHALE_WHITE = "Looks like a fighter.",
	VOLCANO_SHRUB = "You look ashen.",
	ROCK_OBSIDIAN = "Blast it! It won't be mined!",
	ROCK_CHARCOAL = "Would need an awfully big stocking for that.",
	DRAGOONDEN = "Even goons gotta sleep.",
	WILBUR_UNLOCK = "He looks kind of regal.",
	WILBUR_CROWN = "It's oddly monkey-sized.",
	TWISTER = "I thought it was strangely windy around here.",
	TWISTER_SEAL = "D'awww.",
	MAGIC_SEAL = "This is a powerful artifact.",
	SAIL_STICK = "There must be a scientific explanation for this.",
	WIND_CONCH = "I can hear the wind trapped within.",
	DRAGOONEGG = "Do I hear cracking?",
	BUOY = "Awww yaaaaa buoy!", 
	TURF_SNAKESKIN = "Sssstylish ssssstatement.",
	DOYDOYNEST = "It's for doydoy eggs, dummy.",
	ARMORCACTUS = "The best defense is a good offense.",
	BIGFISHINGROD = "To catch a big fish, you need a big rod.",
	BRAINJELLYHAT = "Two brains means double the ideas!",
	COCONUT_HALVED = "When I click them together, they make horsey sounds.",
	CRATE = "There must be a way to open it.",
	DEPLETED_BAMBOOTREE = "Will it grow again?",
	DEPLETED_BUSH_VINE = "One day it may return.",
	DEPLETED_GRASS_WATER = "Farewell, sweet plant.",
	DOYDOYEGG_COOKED = "A controlled chemical reaction has made this egg matter more nutritious.",
	DRAGOONHEART = "Where the dragoon once stored its feelings.",
	DRAGOONSPIT = "It's SPITacularly disgusting!",
	DUG_BUSH_VINE = "I suppose I should pick it up.",
	KRAKEN = "Now's not the time for me to be Quacken wise!",
	KRAKENCHEST = "To the victor, the spoils.",
	KRAKEN_TENTACLE = "A beast that never sleeps.",
	MAGMAROCK_FULL = "I can dig it.",
	MAGMAROCK_GOLD_FULL = "I see a golden opportunity.",
	MONKEYBALL = "I have a strange desire to name it after myself.",
	MUSSELBOUILLABAISE = "Imagine the experiments I could run on it!",
	MYSTERYMEAT = "I'm not dissecting that.",
	OXHAT = "Nice and dry. This helmet will protect me from the elements.",
	OX_FLUTE = "Is it dripping...?",
	OX_HORN = "I grabbed the ox by the horn.",
	PARROT_PIRATE = "I try not to eat anything with a name.",
	PEG_LEG = "I can perform amputations if anyone'd like to wear it for real.",
	PIRATEGHOST = "He met a terrible end. I will too if I don't get out of here.",
	SANDBAGSMALL_ITEM = "A bag full of sand. Does science know no bounds?",
	SHADOWSKITTISH_WATER = "Yikes!",
	SHIPWRECKED_ENTRANCE = "Ahoy!",
	SHIPWRECKED_EXIT = "And so, I sail away into the horizon!",
	SAIL_SNAKESKIN = "Scale it and sail it!",
	SPEAR_LAUNCHER = "Science takes care of me.",
	SWEETPOTATOSOUFFLE = "Sweet potato souffles are a rising trend.",
	SWIMMINGHORROR = "Yikes! Get me back to land!",
	TIGEREYE = "More eyes means better sight... right?",
	TRINKET_IA_20 = "I'm not sure what it is, but it makes me feel smarter!",
	TRINKET_IA_21 = "I ought to measure it to ensure it's to scale.",
	TRINKET_IA_22 = "I'm sure someone would like this.",
	TURF_MAGMAFIELD = "Lava-y floor.",
	TURF_TIDALMARSH = "Marsh-y floor.",
	VOLCANO_ALTAR_TOWER = "How scary!",
	WATERYGRAVE = "Sure, I could fish it out of there. But should I?",
	WHALE_TRACK = "Whale, ho!",
	WILDBOREHEAD = "It smells as bad as it looks.",
	BOAT_WOODLEGS = "A vessel fit for a scallywag.",
	WOODLEGSHAT = "Not too keen on being a pirate.", --SWC
	SAIL_WOODLEGS = "The quintessential pirate sail.",
	SHIPWRECK = "Poor little boat.",
	INVENTORYGRAVE = "There was someone here before me!",
	INVENTORYMOUND = "There was someone here before me!",
	LIMPETS_COOKED = "Escargotcha!",
	RAWLING = "It's my buddy!",
	CALIFORNIAROLL = "But I don't have chopsticks.",
},
}
