return {
ACTIONFAIL = {
	REPAIRBOAT =
	{
		GENERIC = "Small boat has no damages to repair! Wolfgang could punch it?",
	},
},
ANNOUNCE_OTHER_WORLD_PLANT = "Not mighty enough to grow here! Unlike Wolfgang!",
ANNOUNCE_MAGIC_FAIL = "Is not making the magics now. Why?",
ANNOUNCE_BOAT_DAMAGED = "Ship is weak! Needs fixingtimes.",
ANNOUNCE_BOAT_SINKING = "I will fight sea!",
ANNOUNCE_BOAT_SINKING_IMMINENT = "Wolfgang will punch death!",
ANNOUNCE_CRAB_ESCAPE = "Crabbit has fled. I do not blame it.",
ANNOUNCE_MAPWRAP_LOSECONTROL = "Boat not listen to mighty Wolfgang!",
ANNOUNCE_MAPWRAP_RETURN = "Wolfgang cannot be stopped!",
ANNOUNCE_MAPWRAP_WARN = "Is getting scary!",
ANNOUNCE_MORETREASURE = "Wolfgang find more shinies!",
ANNOUNCE_OTHER_WORLD_TREASURE = "Treasure does not look close by.",
ANNOUNCE_SHARX = "Wolfgang has made new friends!",
ANNOUNCE_TRAWL_FULL = "Net is fat with treasures!",
ANNOUNCE_TREASURE = "Wolfgang sees presents!",
ANNOUNCE_VOLCANO_ERUPT = "Ha ha! Time to fight MOUNTAIN!",
ANNOUNCE_WAVE_BOOST = "I am mighty!",
ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "Wolfgang will find you, big fishie!",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Argh! Big fishie outsmart Wolfgang!",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "Wolfgang cannot follow big fishie!",
ANNOUNCE_MESSAGEBOTTLE =
{
	"Eh... Wolfgang can not read.",
},


DESCRIBE = {
	-- PORTABLECOOKPOT_ITEM = "Chef will cook good meal for friends, meal like home!",
	CHEFPACK = "Is funny chef hat.",
	-- PORTABLECOOKPOT = 
	-- {
 		-- COOKING_LONG = "This take long time.",
		-- COOKING_SHORT = "Is almost cook!",
		-- DONE = "Is time to eat!",
		-- EMPTY = "Chef man cooks good meals for friends, meals like home!",
    -- },
	-- WARLY = 
    -- {
        -- GENERIC = "Is tiny chef man, %s! Hello!",
        -- ATTACKER = "Ha ha! %s should not pick fight with dumb food!",
        -- MURDERER = "%s is killer!",
        -- REVIVER = "%s is nice, cooks good grub for Wolfgang.",
        -- GHOST = "Do not hurt, chef man. Wolfgang get heart!",
		-- FIRESTARTER = "Please keep burny fires in pot!",
    -- },

	SEAWEED_STALK = "Squishy.", --copied from the Wikia because I couldn't find it in the game files. -M

	LEIF_PALM = "Wood man! Fight me!",
	BABYOX = "He will grow very strong. Or she?",
	BIGFISHINGROD = "Is catching big fish?",
	BLOWDART_POISON = "Is like many tiny punches!",
	COFFEEBOT = "Is hard worker.",
	DEPLETED_GRASS_WATER = "Maybe grass just need to eat.",
	DEPLETED_BAMBOOTREE = "Bush is done for.",
	DEPLETED_BUSH_VINE = "Vine bush is look pathetic!",
	MUSSELBOUILLABAISE = "It belongs in Wolfgang's mouth.",
	OBSIDIANSPEARGUN = "Not as fun as punches, but still very good!",
	SPEARGUN_POISON = "My sickness shooter!",
	SUPERTELESCOPE = "Make eyes strong!",
	SWEETPOTATOSOUFFLE = "Wolfgang will eat!",
	BOAT_WOODLEGS = "Is very bad boat.",
	WOODLEGSHAT = "Is head clothes.",
	SAIL_WOODLEGS = "Is scary sail!",
	TROPICALFAN = "Ha! Is as big as head!",
	SOLOFISH_DEAD = "Is dead.",
	FISH_MED_COOKED = "Meat from water still make Wolfgang strong.",
	GHOST_SAILOR = "Eeeeeeeeeeee!",
	WOODLEGS_CAGE = "Is locked.",
	AERODYNAMICHAT = "Keeps mighty legs free to run!",
	ANTIVENOM = "Wolfgang will flex poison out of veins!",
	ARMORCACTUS = "Hah! Try hit Wolfgang now.",
	ARMORLIMESTONE = "This mighty armor will protect me!",
	ARMOROBSIDIAN = "Is cheap trick, but Wolfgang like!",
	ARMORSEASHELL = "Try your dirty tricks now, poison creatures.",
	ARMOR_LIFEJACKET = "Big seawater will not take Wolfgang now!",
	ARMOR_SNAKESKIN = "Is made to show my mighty muscles.",
	ARMOR_WINDBREAKER = "Wolfgang master of breaking wind!",
	BOAT_ARMOURED = "You are mighty, just like me.",
	BALLPHIN = "Come and fight with me, sea-friends!", 
	BAMBOO = "Very mighty building material!",
	BAMBOOTREE =
	{
		BURNT = "Is not very mighty now.",
		CHOPPED = "I hope is fast growing.",
		GENERIC = "I will harvest you soon, mighty plant!",
	},
	BERMUDATRIANGLE = "Is give me uneasy feelings.",
	BIOLUMINESCENCE = "Pretty sea-lights!",
	BLOWDART_FLUP = "Is workout for my powerful lungs!",
	BLUBBER = "Is not muscle.",
	BLUBBERSUIT = "Would rather wear a muscle suit!",
	BOAT = "Mighty vessel fights the waters.",
	BOATCANNON = "Is the mightiest weapon!",
	BOATREPAIRKIT = "Restore my mighty vessel!",
	BOAT_LANTERN = "Is safer light.",
	BOAT_TORCH = "Flame on boat is good idea!",
	BOTTLELANTERN = "Is good way to keep darkness back.",
	BRAINJELLYHAT = "Agh! Is making Wolfgang think!",
	BUOY = "Ahhh, is marking something.",
	BURIEDTREASURE = "Is mine!",
	BUSH_VINE =
	{
		BURNT = "Ash.",
		CHOPPED = "I won. You lost.",
		GENERIC = "This is bush. Of vines.",
	},
	CAPTAINHAT = "Look at Wolfgang! He is captain now!",
	BOAT_CARGO = "What a mighty storage hold!",
	CHIMINEA = "Be safe from wind, little fire.",
	SAIL_CLOTH = "I will capture you, wind!",
	COCONADE =
	{
		BURNING = "Is burning up quickly.",
		GENERIC = "So much power!",
	},
	COCONUT = "Wolfgang will crush with bare hands.",
	COCONUT_SAPLING = "Is tiny tree! Very small!",
	COCONUT_COOKED = "Coconut is cooked.",
	COCONUT_HALVED = "Wolfgang had no problem smacking hard shell apart.",
	COFFEE = "Strong, like Wolfgang!",
	COFFEEBEANS = "Tiny beans give Wolfgang strength!",
	COFFEEBEANS_COOKED = "Is bitter beans!",
	COFFEEBUSH =
	{
		BARREN = "Where did all tasty beans go?",
		GENERIC = "Coffee bush is proud, strong.",
		PICKED = "Rest now, friend.",
		WITHERED = "Is on death's door.",
	},
	CORAL = "Is very pretty! Will it crush?",
	ROCK_CORAL = "Is so fragile!",
	CORAL_BRAIN = "Heh heh. It squish under Wolfgang's touch.",
	CORAL_BRAIN_ROCK = "Wolfgang's brain will punch this brain.",
	CRAB =
	{
		GENERIC = "If I punch it, it will be food.",
		HIDDEN = "Dun be shellfish.",
	},
	CRABHOLE = "Crabbit is coward.",
	CRATE = "I could smash.",
	CUTLASS = "Wolfgang is ready for battle!",
	SWORDFISH_DEAD = "It was a good fight.",
	DOUBLE_UMBRELLAHAT = "Two umbrellas is better than one.",
	DOYDOY = "Small dumb bird!",
	DOYDOYBABY = "Protect dumb friend, love dumb friend.",
	DOYDOYEGG = "Eat raw, good for mighty muscles!",
	DOYDOYEGG_COOKED = "Stupidly tasty protein.",
	DOYDOYEGG_CRACKED = "I should eat fast before stupid bird comes out.",
	DOYDOYFEATHER = "To remember nice bird by.",
	DOYDOYNEST = "Where dumb friends sleep.",
	DRAGOON = "Is time for flexing contest?",
	DRAGOONDEN = "Wolfgang approves.",
	DRAGOONEGG = "Hatch so we might fight!",
	DRAGOONHEART = "Is mush in my hand.",
	DRAGOONSPIT = "Ha! Wolfgang spit much farther.",
	DUBLOON = "It dents when crushed between Wolfgang's powerful jaws!",
	DUG_BAMBOOTREE = "I will take it with me.",
	DUG_BUSH_VINE = "I will take it with me.",
	DUG_COFFEEBUSH = "It will grow no strong beans like this.",
	DUG_ELEPHANTCACTUS = "I will pick it up with bare hands.",
	EARRING = "Someone drop this, maybe?",
	ELEPHANTCACTUS = "Ouch! Is still sharp.",
	ELEPHANTCACTUS_ACTIVE = "Puny cactus wants to fight me!",
	ELEPHANTCACTUS_STUMP = "It is not dead, only sleeping.",
	FABRIC = "Flimsy cloth-stuffs.",
	SAIL_FEATHER = "Wolfgang is master of sea!",
	FISHINHOLE = "Is good place to fish for... fish.",
	FISH_MED = "Lump of stinky protein.",
	FISH_SMALL = "Fish lump for eating.",
	FISH_SMALL_COOKED = "Looks better now.",
	FLAMEGEYSER = "Watch Wolfgang walk over this!",
	FLOTSAM = "Is not a mighty ship.",
	FLUP = "Flup off!",
	-- FRESHFRUITCREPES = "Manly midmorning brunch.",
	FROG_POISON = "Coward frog!",
	GASHAT = "Little hat is very colorful.",
	GOLDENMACHETE = "Hoighty toighty knife!",
	GRASS_WATER = "Is thirsty grass.",
	HAIL_ICE = "Is cold.",
	ICEMAKER =
	{
		HIGH = "Machine is doing very good job!",
		LOW = "Little machine looks tired.",
		NORMAL = "Thank you for good ice, machine.",
		OUT = "Small machine is out of juice.",
		VERYLOW = "Machine will not last much longer.",
	},
	INVENTORYGRAVE = "A tiny man came through here.",
	INVENTORYMOUND = "A tiny man came through here.",
	IRONWIND = "Spinny sail!",
	JELLYFISH = "If I punch jelly, it will become jam.",
	JELLYFISH_COOKED = "Jelly looks tasty now.",
	JELLYFISH_DEAD = "It stood no chance against Wolfgang.",
	JELLYFISH_PLANTED = "Can it arm wrestle?",
	JELLYJERKY = "Jerky is tough, like Wolfgang!",
	JUNGLETREE =
	{
		BURNING = "I broke it.",
		BURNT = "Is small and broken now.",
		CHOPPED = "Ha! I win!",
		GENERIC = "Tree is strong and magnificent.",
	},
	JUNGLETREESEED = "It might become tree.",
	JUNGLETREESEED_SAPLING = "It has better chance of being tree now.",
	KNIGHTBOAT = "Let us fight!",
	KRAKEN = "Crummy breadeater!",
	KRAKENCHEST = "It dropped something.",
	KRAKEN_TENTACLE = "You have many arms!",
	LAVAPOOL = "Sad. I forget swim trunks.",
	LIMESTONENUGGET = "Corals were crushed to make tiny rock.",
	ROCK_LIMPET =
	{
		GENERIC = "Looks like tiny snails for eating!",
		PICKED = "Tiny snails are gone for now.",
	},
	LIMPETS = "Is snail? Maybe.",
	LIMPETS_COOKED = "It is slimy going down.",
	LIVINGJUNGLETREE = "Looks like ordinary tree.",
	LOBSTER = "Wolfgang respects shellbeast's powerful claws.",
	LOBSTERHOLE = "Is home for shellbeasts.",
	LOBSTER_DEAD = "Wolfgang wish he had fearsome hand claws!",
	LOBSTER_DEAD_COOKED = "Is ready to eat now.",
	BOAT_LOGRAFT = "This raft is... not so mighty.",
	LUGGAGECHEST = "Wolfgang will smash and get treasures!",
	MACHETE = "Ah! Very good!",
	MAGIC_SEAL = "Why is sticky?",
	MAGMAROCK = "Is rock left by angry volcano.",
	MAGMAROCK_FULL = "Is rock left by angry volcano.",
	MAGMAROCK_GOLD = "Is shiny volcano rock.",
	MAGMAROCK_GOLD_FULL = "Is shiny volcano rock.",
	MANGROVETREE = "Is very thirsty.",
	MANGROVETREE_BURNT = "Could not withstanding even small heat!",
	MARSH_PLANT_TROPICAL = "Puny shrub.",
	MERMFISHER = "Let us fight!",
	MERMHOUSE_FISHER = "Ugly house!",
	MESSAGEBOTTLE = "Wolfgang can't fit meaty hands inside.",
	MESSAGEBOTTLEEMPTY = "Is just a bottle.",
	MONKEYBALL = "Ha ha! Stupid monkey men.",
	MOSQUITOSACK_YELLOW = "Is yellow punching bag.",
	MOSQUITO_POISON = "Fight like real man!",
	MUSSEL = "My muscles are much bigger!",
	MUSSEL_COOKED = "Mussels become protein for muscles!",
	MUSSEL_FARM =
	{
		GENERIC = "Strangely named. They have no muscles.",
		STICKPLANTED = "Pathetic creatures, conquered by my stick!",
	},
	MUSSEL_STICK = "Mussels love little stick.",
	MYSTERYMEAT = "My mighty stomach can handle it!",
	NEEDLESPEAR = "The weapon of a mighty plant!",
	OBSIDIAN = "There is strong fire in this stone.",
	OBSIDIANAXE = "The mightiest of axes!",
	OBSIDIANCOCONADE = "Even more might!",
	OBSIDIANFIREPIT =
	{
		EMBERS = "The darkness is coming!",
		GENERIC = "Wolfgang did good job!",
		HIGH = "Is too much fire!",
		LOW = "The fire is not hot enough.",
		NORMAL = "Hearty fire warms Wolfgang's bones.",
		OUT = "Uh oh. It turned off.",
	},
	OBSIDIANMACHETE = "Is so sharp!",
	OBSIDIAN_WORKBENCH = "Is fire table.",
	OCTOPUSCHEST = "Give Wolfgang your treasures!",
	OCTOPUSKING = "Strong creature! Give Wolfgang many good things!",
	OX = "What a mighty beast!",
	OXHAT = "I have become more mighty!",
	OX_FLUTE = "Wolfgang will play lusty tune.",
	OX_HORN = "Horn of strong ox!",
	PACKIM = "Hello, robust friend!",
	PACKIM_FISHBONE = "Is bone. I like it.",
	PALMLEAF = "Big green leaf.",
	PALMLEAF_HUT = "The great Wolfgang deserves comfort.",
	PALMTREE =
	{
		BURNING = "I broke it.",
		BURNT = "Is small and broken now.",
		CHOPPED = "Ha! I win!",
		GENERIC = "Such jovial tree.",
	},
	PARROT = "Chatty bird!",
	PARROT_PIRATE = "It could maybe be friend?",
	PEACOCK = "Bird is showing off.",
	PEG_LEG = "Is best battle trophy!",
	PIKE_SKULL = "Wolfgang not afraid!",
	PIRATEGHOST = "Aaaaaaaaaaahrrrr!!",
	PIRATEHAT = "Ha ha! I like!",
	PIRATEPACK = "Sounds like jingles.",
	PIRATIHATITATOR =
	{
		BURNT = "It does nothing.",
		GENERIC = "Strange contraption.",
	},
	POISONHOLE = "Cowardly hole!",
	PORTAL_SHIPWRECKED = "Where do you go?",
	PRIMEAPE = "Does not look like even match for me.",
	PRIMEAPEBARREL = "Home of tiny monkey men.",
	BOAT_RAFT = "How will tiny plank support Wolfgang?",
	RAWLING = "Wolfgang plays ball!",
	BARREL_GUNPOWDER = "Do not poke barrel.",
	ROCK_CHARCOAL = "Wolfgang rubs it under eyes to scare foes!",
	ROCK_OBSIDIAN = "Very strong rock. Wolfgang would like to have it.",
	BOAT_ROW = "I will row with powerful arms!",
	SAIL_PALMLEAF = "Wolfgang will take to the seas.",
	SAIL_STICK = "Stick makes good sailing!",
	SAND = "When Wolfgang holds it it slips through his large, strong hands.",
	SANDBAG = "Bag soaks up waters.",
	SANDBAGSMALL = "Little bag soaks up waters.",
	SANDBAGSMALL_ITEM = "Is big bag of dirt.",
	SANDBAG_ITEM = "Bag is full of dirt.",
	SANDDUNE = "Tiny, crushable hill.",
	SANDCASTLE =
	{
		GENERIC = "Good for stomping!",
		SAND = "Is more sand than castle.",
	},
	SEAGULL = "It has large mouth. Like me!",
	SEAGULL_WATER = "Resting after good fights, friend?",
	SEASACK = "Wolfgang can carry even more things!",
	SEASHELL = "Tiny shell would crush easily.",
	SEASHELL_BEACHED = "Wolfgang keep bowl of these on table at home.",
	SEATRAP = "Little pincher does not stand a chance.",
	SEAWEED = "A weed, from the sea.",
	SEAWEED_COOKED = "Wolfgang's strong stomach will destroy this!",
	SEAWEED_DRIED = "Is edible.",
	SEAWEED_PLANTED = "Strange leaves from sea.",
	SHADOWSKITTISH_WATER = "I do not like it!",
	SHARKITTEN = "Wolfgang is dog person.",
	SHARKITTENSPAWNER =
	{
		GENERIC = "Is time for cat nap?",
		INACTIVE = "Is just sand.",
	},
	SHARK_FIN = "I lost rest of shark.",
	SHARK_GILLS = "Maybe now Wolfgang breathe underwater? Maybe not.",
	SHARK_TEETHHAT = "Wolfgang's favorite hat!",
	SHARX = "I do not trust these sea-doggies.",
	SHIPWRECKED_ENTRANCE = "Is magical portal. Very sandy...",
	SHIPWRECKED_EXIT = "Is magical portal. Very grassy...",
	SLOTMACHINE = "Wolfgang is gambling man!",
	SNAKE = "I am ready to fight!",
	SNAKEDEN =
	{
		BURNT = "Ash.",
		CHOPPED = "I won. You lost.",
		GENERIC = "This is bush. Of vines.",
	},
	SNAKEOIL = "Good for shining Wolfgang's muscles!",
	SNAKESKIN = "I will use as bandana.",
	SNAKESKINHAT = "Very good.",
	SAIL_SNAKESKIN = "Skin of dead snake will help me sail.",
	SNAKE_FIRE = "You are slippery snake!",
	SNAKE_POISON = "Poison is weapon of cowards!",
	SOLOFISH = "Face me, fish!",
	SPEARGUN = "Spears will shoot now!",
	SPEAR_LAUNCHER = "Punch from a great distance!",
	SPEAR_OBSIDIAN = "Very strong, warm spear.",
	SPEAR_POISON = "Is not cowardly if I use it.",
	SPOILED_FISH = "Is good no more.",
	STUNGRAY = "Looks smooth. I will pet it!",
	SUNKEN_BOAT =
	{
		ABANDONED = "No one home.",
		GENERIC = "Where is captain?",
	},
	SUNKEN_BOAT_BURNT = "Pile of burnt wood.",
	SUNKEN_BOAT_TRINKET_1 = "Wolfgang loves these!",
	SUNKEN_BOAT_TRINKET_2 = "Wolfgang will not fit!",
	SUNKEN_BOAT_TRINKET_3 = "It is the perfect amount of dampness.",
	SUNKEN_BOAT_TRINKET_4 = "Metal doodad is fun for playtimes.",
	SUNKEN_BOAT_TRINKET_5 = "Tough leather is hard to chew.",
	-- BANANAPOP = "Wolfgang can eat in one bite!",
	BISQUE = "It will fuel powerful punches!",
	-- CEVICHE = "It will be better in Wolfgang's belly!",
	SEAFOODGUMBO = "This will make very strong Wolfgang!",
	SURFNTURF = "Very good.",
	SHARKFINSOUP = "Is small shark inside?",
	-- MONSTERTARTARE = "Blech!",
	LOBSTERDINNER = "A meal fit for Wolfgang!",
	LOBSTERBISQUE = "Seems fancy.",
	JELLYOPOP = "Looks like candy, but tastes like meat!",
	SWEET_POTATO = "Very sweet!",
	SWEET_POTATO_COOKED = "Is ready to eat!",
	SWEET_POTATO_PLANTED = "Potato is strange color inside.",
	SWEET_POTATO_SEEDS = "Seeds would taste better if they were a potato.",
	SWIMMINGHORROR = "If it's a fight you want, Wolfgang will oblige!",
	SWORDFISH = "Wolfgang challenges you to duel!",
	TELEPORTATO_SW_BASE = "Wolfgang must fix it.",
	TELEPORTATO_SW_BOX = "What use is tiny box? Wolfgang would like to know.",
	TELEPORTATO_SW_CRANK = "Wolfgang will hold on to this.",
	TELEPORTATO_SW_POTATO = "Hello, spuddy.",
	TELEPORTATO_SW_RING = "I will carry you.",
	TELESCOPE = "I see far!",
	THATCHPACK = "Wolfgang can carry more on powerful shoulders!",
	TIDALPOOL = "Fishies nibble toes when I stick them in.",
	TIDAL_PLANT = "Is plant.",
	TIGEREYE = "Is giving me dirty look.",
	TIGERSHARK = "I will take you to POUND!",
	TOUCAN = "Bird flees at the sight of Wolfgang.",
	TRAWLNET = "Wolfgang will trap you in his net!",
	TRAWLNETDROPPED =
	{
		GENERIC = "What fishes will I find?",
		SOON = "Is really sinking.",
		SOONISH = "Is sinking.",
	},
	TRIDENT = "I feel like king of sea.",
	TRINKET_IA_13 = "Wolfgang would not like to drink.",
	TRINKET_IA_14 = "Wolfgang does not like that.",
	TRINKET_IA_15 = "It does not fit in Wolfgang's big hands.",
	TRINKET_IA_16 = "I do not know what this is.",
	TRINKET_IA_17 = "Tough leather is hard to chew.",
	TRINKET_IA_18 = "Is broken.",
	TRINKET_IA_19 = "Wolfgang is not eat loose pills.",
	TRINKET_IA_20 = "Wolfgang loves these!",
	TRINKET_IA_21 = "Wolfgang will not fit!",
	TRINKET_IA_22 = "Looks much too dry.",
	TRINKET_IA_23 = "Is very broken.",
	FISH_TROPICAL = "Is yummy looking.",
	TUNACAN = "I will open with bare hands!",
	TURBINE_BLADES = "Blade that does not cut.",
	TURF_ASH = "Step stones.",
	TURF_BEACH = "Step stones.",
	TURF_JUNGLE = "Step stones.",
	TURF_MAGMAFIELD = "Step stones.",
	TURF_MEADOW = "Step stones.",
	TURF_SNAKESKIN = "Step stones.",
	TURF_SWAMP = "Step stones.",
	TURF_TIDALMARSH = "Step stones.",
	TURF_VOLCANO = "Step stones.",
	TWISTER = "What might!",
	TWISTER_SEAL = "Ha ha! Is good friend.",
	VENOMGLAND = "Is weapon of cowards.",
	VINE = "For string enemies together.",
	VOLCANO = "Is calling me to fight!",
	VOLCANOSTAFF = "Power of fire mountain is in Wolfgang's hands!",
	VOLCANO_ALTAR =
	{
		GENERIC = "Is not wanting anything right now.",
		OPEN = "Wolfgang is afraid to use.",
	},
	VOLCANO_ALTAR_BROKEN = "This is no more.",
	VOLCANO_ALTAR_TOWER = "Is scary looking.",
	VOLCANO_EXIT = "Goodbye!",
	VOLCANO_SHRUB = "Tree was too weak. Dead now.",
	WALLYINTRO_DEBRIS = "It's lost its battle.",
	WALL_LIMESTONE = "Good, sturdy wall.",
	WALL_LIMESTONE_ITEM = "I will make strong wall.",
	WATERYGRAVE = "I do not like this. Is creepy.",
	WHALE_BLUE = "I will eat you!",
	WHALE_BUBBLES = "Large fishie is underneath.",
	WHALE_CARCASS_BLUE = "Well fought, large fish!",
	WHALE_CARCASS_WHITE = "Not-so-great white.",
	WHALE_TRACK = "Massive fish cannot escape me!",
	WHALE_WHITE = "Great white! Fight Wolfgang!",
	WILBUR_CROWN = "Crown is falling apart!",
	WILBUR_UNLOCK = "Welcome, friend! Ha ha!",
	WILDBORE = "I will wrestle you.",
	WILDBOREHEAD = "Very gross!",
	WILDBOREHOUSE = "Puny house could not hold me.",
	WIND_CONCH = "Shell makes scary sounds!",
	WOODLEGS_KEY1 = "Spooky key!",
	WOODLEGS_KEY2 = "Pretty key!",
	WOODLEGS_KEY3 = "Boring key!",
	SHIPWRECK = "Not mighty enough to float.",
	CALIFORNIAROLL = "Get in Wolfgang's stomach!",

	--- 5C DLC ------------------------------------------------------------------------------------------------

	BOAT_ENCRUSTED = "Tiny boat will hold all of Wolfgang?",
	BABYOX = "He will grow very strong! Or is she?",
	BALLPHINHOUSE = "Friends of Wolfgang live inside.",
	DORSALFIN = "Where is rest of fish?",
	NUBBIN = "Haha. Rock is bald.",
	CORALLARVE = "Is small and harmless.",
	RAINBOWJELLYFISH = "Ah! Is pretty jelly!",
	RAINBOWJELLYFISH_PLANTED = "Very pretty jelly!",
	RAINBOWJELLYFISH_DEAD = "Good looking jelly is no look so good.",
	RAINBOWJELLYFISH_COOKED = "Food is many pretty colors!",
	RAINBOWJELLYJERKY = "Tough food makes Wolfgang tough!",
	WALL_ENFORCEDLIMESTONE = "Is sea wall now!",
	WALL_ENFORCEDLIMESTONE_ITEM = "Wolfgang will build sea wall!",
	CROCODOG = "Hairless puppy!",
	POISONCROCODOG = "Hairless puppy is yellow!",
	WATERCROCODOG = "Hairless puppy is blue!",
	QUACKENBEAK = "Wolfgang is very proud of bird souvenir!",
	QUACKERINGRAM = "SMASH!",

	--- DLC ------------------------------------------------------------------------------------------------    

	CAVIAR = "Little eggs make Wolfgang feel like big, important man.",
	CORMORANT = "Bird smells like fish eggs.",

	PURPLE_GROUPER = "Wolfgang wish he swim like fish.",
	PIERROT_FISH = "Little fish is very dry!",
	NEON_QUATTRO = "Ha ha! Scales is chilly!",

	PURPLE_GROUPER_COOKED = "Wolfgang will eat tasty fish!",
	PIERROT_FISH_COOKED = "Little fish will make Wolfgang mighty!",
	NEON_QUATTRO_COOKED = "Toasty fish is good muscle fuel.",

	FISH_FARM = 
	{
		EMPTY = "Need little fishie eggs!",
		STOCKED = "Fishes is growing.",
		ONEFISH = "Wolfgang has fish!",
		TWOFISH = "More fishes for Wolfgang!",
		REDFISH = "Many fishes means fancy fish soup!",
		BLUEFISH  = "Wolfgang will eat ALL fishes!",
	},
	
	ROE = "Is eggy.",
	ROE_COOKED = "Little eggs is stink less now.",
	
	SEA_YARD = 
	{
		ON = "Will make boats mighty again!",
		OFF = "Is not working.",
		LOWFUEL = "Need fuel for running.",
	},
	SEA_CHIMINEA =
	{
		EMBERS = "Fire is sick, maybe?",
		GENERIC = "Wolfgang will make fire at sea.",
		HIGH = "Mighty fire for mighty Wolfgang!",
		LOW = "Little sea fire is look wimpy.",
		NORMAL = "Fire is okay.",
		OUT = "Wolfgang needs new fire.",
	}, 

	TAR = "Icky sticky black goo!",
	TAR_EXTRACTOR =
	{
		ON = "Machine is run strong.",
		OFF = "Is need on-switching.",
		LOWFUEL = "Floaty machine needs food.",
											
											 
	},
	TAR_POOL = "Is bubbling.",

	TARLAMP = "Lamp is so little, dainty.",
	TARSUIT = "Water not get Wolfgang now.",
	TAR_TRAP = "Goo cannot stop mighty Wolfgang feet!",
	
	TROPICALBOUILLABAISSE = "Wolfgang does not know what to call this.",
	
	SEA_LAB = "Wolfgang will learn many splishy splashy things!",
	WATERCHEST = "Is for holding seastuff!",
	QUACKENDRILL = "Wolfgang will punch bottom of ocean!",
	HARPOON = "Even Wolfgang's throws is mighty!",
	MUSSEL_BED = "Tiny mussels should be in water!",
},
}
