return {
ACTIONFAIL = {
	REPAIRBOAT =
	{
		GENERIC = "I'm afraid I can't.",
	},
},
ANNOUNCE_MAGIC_FAIL = "That won't work here, eh.",
ANNOUNCE_OTHER_WORLD_PLANT = "Wrong kind of soil for this, eh?",
ANNOUNCE_BOAT_DAMAGED = "My boat's pretty banged up, eh?",
ANNOUNCE_BOAT_SINKING = "I'm aboot to sink!",
ANNOUNCE_BOAT_SINKING_IMMINENT = "We're goin' down!",
ANNOUNCE_CRAB_ESCAPE = "It got away.",
ANNOUNCE_MAPWRAP_LOSECONTROL = "Into waters unknown!",
ANNOUNCE_MAPWRAP_RETURN = "That was unwise!",
ANNOUNCE_MAPWRAP_WARN = "I'm leaving charted waters...",
ANNOUNCE_MESSAGEBOTTLE =
{
	"The sea has washed away the message.",
},
ANNOUNCE_MORETREASURE = "There's more gold to be had!",
ANNOUNCE_OTHER_WORLD_TREASURE = "I don't believe I can find this here.",
ANNOUNCE_SHARX = "There's a fish nearby... and it's hungry!",
ANNOUNCE_TRAWL_FULL = "It's time to reel it in!",
ANNOUNCE_TREASURE = "Here comes the gold rush!",
ANNOUNCE_VOLCANO_ERUPT = "Ooh, that's some bad weather, eh?",
ANNOUNCE_WAVE_BOOST = "For the North!",
ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "I was born to track beasts!",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "I lost the trail. Sorry!",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "Where did the whale go?!",

DESCRIBE = {
	-- PORTABLECOOKPOT_ITEM = "Sure makes the camp smell nice.",
	CHEFPACK = "Good for long hikes.",
	-- PORTABLECOOKPOT = 
	-- {
		-- COOKING_LONG = "Warly says not to watch a boiling pot, eh?",
		-- COOKING_SHORT = "Oh boy! I smell supper!",
		-- DONE = "Time for supper!",
		-- EMPTY = "Someone get the chef to cook us up some grub.",
    -- },
	-- WARLY = 
    -- {
        -- GENERIC = "%s! How ya doin', buddy?",
        -- ATTACKER = "%s could learn some manners...",
        -- MURDERER = "This is gonna be a clear cut!",
        -- REVIVER = "%s, you're an alright guy.",
        -- GHOST = "With a heart you'll be tip-top in no time, %s.",
		-- FIRESTARTER = "I'm no expert but that is not how you start cooking.",
    -- },

	SEAWEED_STALK = "Should plant this somewhere.", --copied from the Wikia because I couldn't find it in the game files. -M

	LEIF_PALM = "I've angered the beach!", -- "I'm sorry aboot all of those trees!",
	TROPICALFAN = "I'm not used to the heat in this place!",
	PALMLEAF_UMBRELLA = "I think I did a pretty good job on this 'breller.",
	SOLOFISH_DEAD = "It wants to be dinner.",
	FISH_MED_COOKED = "I wish I had some chips.",
	GHOST_SAILOR = "Not a bad beard for a dead guy.",
	-- BANANAPOP = "I'd prefer maple taffy...",
	BISQUE = "Hearty.",
	-- CEVICHE = "I'd be loonie not to eat this.",
	SEAFOODGUMBO = "We don't have this back home.",
	SURFNTURF = "Good eating, that.",
	SHARKFINSOUP = "He'll swim in my stomach from now on.",
	LOBSTERDINNER = "I'd prefer salmon.",
	LOBSTERBISQUE = "Looks pretty good for desert island food.",
	JELLYOPOP = "I guess this is a dessert island, eh?",
	WOODLEGS_CAGE = "Are you okay in there, buddy?",

	TWISTER = "Mother Nature's throwing a tantrum!",
	WIND_CONCH = "I can hear the chime of twenty-nine bells.",

	AERODYNAMICHAT = "It's a speed toque.",
	ANTIVENOM = "Tastes awful, but it works!",
	ARMORCACTUS = "Pretty prickly protection, eh?",
	ARMORLIMESTONE = "Makes me feel sorta tough.",
	ARMOROBSIDIAN = "Hot stuff, eh?",
	ARMORSEASHELL = "This doesn't seem very hardy.",
	ARMOR_LIFEJACKET = "A lil reassurance.",
	ARMOR_SNAKESKIN = "I feel suave in it.",
	ARMOR_WINDBREAKER = "I feel right at home in this, eh.",
	BOAT_ARMOURED = "That's aboot as safe as it gets on the sea.",
	BABYOX = "Hey, little buddy!",
	BALLPHIN = "Hey buddy, you know any tricks?",
	BAMBOO = "It's like diet wood, eh?",
	BAMBOOTREE =
	{
		BURNT = "Burnt like bacon, eh?",
		CHOPPED = "That was some good chopping!",
		GENERIC = "Lucy's got too much kick for this.",
	},
	BERMUDATRIANGLE = "Kinda spooky, eh?",
	BIGFISHINGROD = "Walk tall and carry a big rod.",
	BIOLUMINESCENCE = "Just like the Northern Lights.",
	BLOWDART_FLUP = "Eye'll get you!",
	BLOWDART_POISON = "Aim for a main vein, eh?",
	BLUBBER = "Quit your blubbering.",
	BLUBBERSUIT = "It's not very flattering.",
	BOATCANNON = "This'll blow'em up real good!",
	BOATREPAIRKIT = "Patch'er up, eh?",
	BOAT_LANTERN = "It's a boat light.",
	BOAT_TORCH = "I can go night fishing.",
	BOTTLELANTERN = "You okay in there, glowing buddies?",
	BRAINJELLYHAT = "I feel like a keener when I put it on.",
	BUOY = "Floating through life. Got the right idea there.",
	BURIEDTREASURE = "Time to get digging!",
	BUSH_VINE =
	{
		BURNT = "Welp, that's not coming back.",
		CHOPPED = "Not as fun as a tree, but it was good chopping nonetheless.",
		GENERIC = "It's just asking to be chopped.",
	},
	CAPTAINHAT = "I hope I don't have to go down with the ship.",
	BOAT_CARGO = "I'd prefer cargo shorts.",
	CHIMINEA = "It's like armor for fire.",
	SAIL_CLOTH = "This should help me get around.",
	COCONADE =
	{
		BURNING = "Time to run!",
		GENERIC = "I'm gonna do some serious damage with this.",
	},
	COCONUT = "It's just a coconut.",
	COCONUT_SAPLING = "Now it's a tiny palm tree.",
	COCONUT_COOKED = "Ready to eat.",
	COCONUT_HALVED = "One for me and one for Lucy.",
	COFFEE = "Good old joe.",
	COFFEEBEANS = "I should cook these up.",
	COFFEEBEANS_COOKED = "Canadians love their coffee.",
	COFFEEBOT = "Makes coffee, don't it.",
	COFFEEBUSH =
	{
		BARREN = "You look a little down, bud.",
		GENERIC = "Coffee beans!",
		PICKED = "I wish it had more beans.",
		WITHERED = "It could use good cuppa joe.",
	},
	CORAL = "Maybe I could crush it down to make something new.",
	ROCK_CORAL = "Ripe for the picking.",
	CORAL_BRAIN = "How brainy.",
	CORAL_BRAIN_ROCK = "What're you, some sort of keener?",
	CRAB =
	{
		GENERIC = "Maybe we could be buds?",
		HIDDEN = "Can't hide forever, bud.",
	},
	CRABHOLE = "That's where my crabbit buddies live.",
	CRATE = "That there's a box.",
	CUTLASS = "That's a pretty neat little cutter, eh?",
	SWORDFISH_DEAD = "Sorry, guy.",
	DEPLETED_BAMBOOTREE = "Grow so I can chop you down again!",
	DEPLETED_BUSH_VINE = "I guess it'll regrow.",
	DEPLETED_GRASS_WATER = "I don't like waiting.",
	DEVTOOL_NODEV = "What a curious thing.",
	DOUBLE_UMBRELLAHAT = "Double the protection!",
	DOYDOY = "Not too sure how this awful thing survives.",
	DOYDOYBABY = "It's filthy.",
	DOYDOYEGG = "Looks like good eating to me.",
	DOYDOYEGG_COOKED = "Could use a side of Canadian bacon.",
	DOYDOYEGG_CRACKED = "Well, can't do nothing aboot it now.",
	DOYDOYFEATHER = "It's nothing like the plumage of the proud Canadian goose.",
	DOYDOYNEST = "Those filthy birds breed here.",
	DRAGOON = "Seems a little hot under the toque!",
	DRAGOONDEN = "That doesn't look like a beaver dam.",
	DRAGOONEGG = "That looks a little suspicious to me.",
	DRAGOONHEART = "The heart of the beast.",
	DRAGOONSPIT = "Rude.",
	DUBLOON = "I've struck gold!",
	DUG_BAMBOOTREE = "You're coming with me!",
	DUG_BUSH_VINE = "Are you ready to go on a little trip?",
	DUG_COFFEEBUSH = "I'm going to take you everywhere with me.",
	DUG_ELEPHANTCACTUS = "Are you headed my way?",
	EARRING = "Shouldn't there be two?",
	ELEPHANTCACTUS = "It's prickly, eh?",
	ELEPHANTCACTUS_ACTIVE = "Watch out! That plant's gonna give'r!",
	ELEPHANTCACTUS_STUMP = "This cactus gave'r. Now it's tired.",
	FABRIC = "How do I dye it plaid?",
	SAIL_FEATHER = "I guess touching all those gross feathers was worth it.",
	FISHINHOLE = "If only it were a little colder, would be perfect for ice fishin'!",
	FISH_MED = "I'd prefer salmon.",
	FISH_SMALL = "I hope I don't attract bears.",
	FISH_SMALL_COOKED = "Looks good to me.",
	FLAMEGEYSER = "Woah, cool it!",
	FLOTSAM = "Justa bunch of junk.",
	FLUP = "Gross.",
	-- FRESHFRUITCREPES = "I can get maple syrup on that?",
	FROG_POISON = "Keep your poison spit to yourself, eh!",
	GASHAT = "Nothin' stinks when I got this on.",
	GOLDENMACHETE = "It chops AND sparkles!",
	GRASS_WATER = "A bit damp, eh?",
	HAIL_ICE = "You think this is cold? How cute.",
	HOUNDFIRE = "It burns so mightily!",
	ICEMAKER =
	{
		HIGH = "Furiously icy! Reminds me of home.",
		LOW = "Gettin' low.",
		NORMAL = "It's pumping along nicely.",
		OUT = "It's hooped.",
		VERYLOW = "It'll give out any second.",
	},
	INVENTORYGRAVE = "Someone was here. Not anymore.",
	INVENTORYMOUND = "Someone was here. Not anymore.",
	IRONWIND = "Looks speedy.",
	JELLYFISH = "That's a jellyfish, don'tcha know.",
	JELLYFISH_COOKED = "I think this is as edible as it gets.",
	JELLYFISH_DEAD = "The life's all but drained out of it, eh?",
	JELLYFISH_PLANTED = "A little jellyfish buddy.",
	JELLYJERKY = "Jerky! The food of my people.",
	JUNGLETREE =
	{
		BURNING = "Waste of a good chopping stump.",
		BURNT = "What a waste.",
		CHOPPED = "Those were good times.",
		GENERIC = "The tree's call fills my ears!",
	},
	JUNGLETREESEED = "This could grow into a good chopping tree.",
	JUNGLETREESEED_SAPLING = "Now we wait.",
	KNIGHTBOAT = "That guy's got an attitude problem!",
	KRAKEN = "For Lucy!",
	KRAKENCHEST = "Show me the loot!",
	KRAKEN_TENTACLE = "A bit grabby, don'tcha think?",
	LAVAPOOL = "I'm breaking a sweat just looking at it.",
	LIMESTONENUGGET = "I crushed up that pretty coral to make this.",
	ROCK_LIMPET =
	{
		GENERIC = "I could make a snack out of those.",
		PICKED = "Just a big rock, eh?",
	},
	LIMPETS = "Some sort of water-dwelling snail.",
	LIMPETS_COOKED = "Dinner's on.",
	LIVINGJUNGLETREE = "It wants me to cut it down, I can tell.",
	LOBSTER = "A little melted butter and it'd be delicious.",
	LOBSTERHOLE = "Come on out, little guy.",
	LOBSTER_DEAD = "He's thoroughly hooped.",
	LOBSTER_DEAD_COOKED = "Good eats!",
	BOAT_LOGRAFT = "My specialty!",
	LUGGAGECHEST = "Anything good inside?",
	MACHETE = "Ooh, that's a thing for chopping.",
	MAGIC_SEAL = "It's pulsing with power.",
	MAGMAROCK = "A little rearranging and it'd make a nice inukshuk.",
	MAGMAROCK_FULL = "A little rearranging and it'd make a nice inukshuk.",
	MAGMAROCK_GOLD = "That looks worth digging into.",
	MAGMAROCK_GOLD_FULL = "That looks worth digging into.",
	MANGROVETREE = "Looks tasty!",
	MANGROVETREE_BURNT = "Hurts my hoser heart to look at.",
	MARSH_PLANT_TROPICAL = "That's a little plant.",
	MERMFISHER = "I don't know aboot that guy.",
	MERMHOUSE_FISHER = "I'd prefer a log cabin.",
	MESSAGEBOTTLE = "Is someone trying to talk to me?",
	MESSAGEBOTTLEEMPTY = "What was in it?",
	MONKEYBALL = "What're you smiling at?",
	-- MONSTERTARTARE = "Isn't there anything else to eat?",
	MOSQUITOSACK_YELLOW = "It smells a little sour.",
	MOSQUITO_POISON = "It's dripping with disease.",
	MUSSEL = "Those look like good eating.",
	MUSSELBOUILLABAISE = "Best meal I've seen in awhile, eh?",
	MUSSEL_COOKED = "These look tasty.",
	MUSSEL_FARM =
	{
		GENERIC = "They want to be food.",
		STICKPLANTED = "I predict a mussel dinner in my future.",
	},
	MUSSEL_STICK = "The mussels can't get enough of this thing.",
	MYSTERYMEAT = "What on earth is that!",
	NEEDLESPEAR = "Hoo-boy. That's sharp.",
	OBSIDIAN = "It's a little toasty.",
	OBSIDIANAXE = "Watch out Lucy, you've got competition! (Just kidding!)",
	OBSIDIANCOCONADE = "It packs a major punch.",
	OBSIDIANFIREPIT =
	{
		EMBERS = "I should go chop some wood for that, eh?",
		GENERIC = "Looks like the perfect place to light a fire.",
		HIGH = "I'm using too much wood too fast!",
		LOW = "There should be some wood around here somewhere.",
		NORMAL = "Mmmm. Smells woody.",
		OUT = "If only I had some wood.",
	},
	OBSIDIANMACHETE = "It singes everything it touches.",
	OBSIDIANSPEARGUN = "It lights stuff on fire, eh.",
	OBSIDIAN_WORKBENCH = "I can make some fiery tools here.",
	OCTOPUSCHEST = "Thanks for the stuff, guy!",
	OCTOPUSKING = "How you holding up out here, guy?",
	OX = "Poor guy's the butt of every yoke.",
	OXHAT = "This is a hat befitting a Northerner.",
	OX_FLUTE = "I'm more of a guitar player.",
	OX_HORN = "It used to be attached to an ox.",
	PACKIM = "I can tolerate him.",
	PACKIM_FISHBONE = "This better not attract any feathered vermin.",
	PALMLEAF = "I use it for fanning myself.",
	PALMLEAF_HUT = "The best shelter a woodcutter could ask for.",
	PALMTREE =
	{
		BURNING = "Waste of a good chopping stump.",
		BURNT = "What a waste.",
		CHOPPED = "Those were good times.",
		GENERIC = "Makes me pine for the lumber yards.",
	},
	PARROT = "Shoo, filthy featherbag!",
	PARROT_PIRATE = "I'd rather not smalltalk with a birdbrain.",
	PEACOCK = "What a ridiculous thing. Bah!",
	PEG_LEG = "Can I chop this?",
	PIKE_SKULL = "Well that there's a tacky decoration.",
	PIRATEGHOST = "Maybe he's friendly?",
	PIRATEHAT = "It's the pirate's life for me now.",
	PIRATEPACK = "A bag for my booty.",
	PIRATIHATITATOR =
	{
		BURNT = "Not so funny anymore.",
		GENERIC = "That's a funny lookin' contraption.",
	},
	POISONHOLE = "I think I'll give that a wide berth.",
	PORTAL_SHIPWRECKED = "Looks hooped to me.",
	PRIMEAPE = "This guy's a bit of a keener.",
	PRIMEAPEBARREL = "Where the keeners sleep.",
	BOAT_RAFT = "Pitiful little boat.",
	RAWLING = "What a nutter!",
	BARREL_GUNPOWDER = "That looks dangerous.",
	ROCK_CHARCOAL = "It makes my hands all sooty.",
	ROCK_OBSIDIAN = "There's a fire burning within it.",
	BOAT_ROW = "Powered by elbow grease.",
	SAIL_PALMLEAF = "I've got the wind in my sails.",
	SAIL_STICK = "The Northern winds are at my disposal.",
	SAND = "Sandy.",
	SANDBAG = "Building dams is my specialty.",
	SANDBAGSMALL = "Building dams is my specialty.",
	SANDBAGSMALL_ITEM = "A tiny, portable dam.",
	SANDBAG_ITEM = "A portable dam.",
	SANDDUNE = "It's a big pile of sand.",
	SANDCASTLE =
	{
		GENERIC = "Who knew sand could look so good.",
		SAND = "Looks good.",
	},
	SEAGULL = "Vermin of the sky.",
	SEAGULL_WATER = "Vermin of the sea.",
	SEASACK = "It's for holding my treasures.",
	SEASHELL = "It makes me want to get back into arts and crafts.",
	SEASHELL_BEACHED = "A pretty shell.",
	SEATRAP = "I'm looking forward to a wobster dinner.",
	SEAWEED = "It's slimy.",
	SEAWEED_COOKED = "It has a weird texture.",
	SEAWEED_DRIED = "It sort of sticks to my tongue.",
	SEAWEED_PLANTED = "That's some seaweed, eh?",
	SHADOWSKITTISH_WATER = "Hoo-boy!",
	SHARKITTEN = "Just a big sweet kitty cat.",
	SHARKITTENSPAWNER =
	{
		GENERIC = "I think I hear meowing...?",
		INACTIVE = "Looks like just a bunch of sand to me, eh?",
	},
	SHARK_FIN = "I'm sure the shark won't miss this.",
	SHARK_GILLS = "Fish lungs.",
	SHARK_TEETHHAT = "It's a hat made of teeth.",
	SHARX = "Not gonna make a buddy of that one, that's for sure.",
	SHIPWRECKED_ENTRANCE = "I'm ready for adventure, eh!",
	SHIPWRECKED_EXIT = "See ya later, bud.",
	SLOTMACHINE = "The spirit of the North guides my fate.",
	SNAKE = "It's an alright sort, as far as snakes go.",
	SNAKEDEN =
	{
		BURNT = "Welp, that's not coming back.",
		CHOPPED = "Not as fun as a tree, but it was good chopping nonetheless.",
		GENERIC = "It's just asking to be chopped.",
	},
	SNAKEOIL = "I'm not falling for this.",
	SNAKESKIN = "I'm sure the snake didn't need this.",
	SNAKESKINHAT = "Now would this be a \"touque\" or a \"tuque\"?",
	SAIL_SNAKESKIN = "Sailin' in style.",
	SNAKE_FIRE = "It's looking a little heated.",
	SNAKE_POISON = "I'd rather not get bitten by that.",
	SOLOFISH = "Nice doggy.",
	SPEARGUN = "This is one skookum weapon!",
	SPEARGUN_POISON = "This skookum weapon poisons my enemies!",
	SPEAR_LAUNCHER = "This is one skookum weapon!",
	SPEAR_OBSIDIAN = "This is one fiery spear.",
	SPEAR_POISON = "This spear has a little extra bite.",
	SPOILED_FISH = "I think it's time to throw this out.",
	STUNGRAY = "Smells worse than a waterlogged moose!",
	SUNKEN_BOAT =
	{
		ABANDONED = "Waste of good wood.",
		GENERIC = "Hey buddy.",
	},
	SUNKEN_BOAT_BURNT = "That there won't float no more.",
	SUNKEN_BOAT_TRINKET_1 = "That's a little too fancy for my liking.",
	SUNKEN_BOAT_TRINKET_2 = "That boat seems a little on the small side.",
	SUNKEN_BOAT_TRINKET_3 = "I can't imagine this having a use.",
	SUNKEN_BOAT_TRINKET_4 = "A toy for a keener.",
	SUNKEN_BOAT_TRINKET_5 = "Not my size, that.",
	SUPERTELESCOPE = "As easy as looking over the plains of Alberta.",
	SWEETPOTATOSOUFFLE = "Pretty extravagant!",
	SWEET_POTATO = "I'll cook this up good.",
	SWEET_POTATO_COOKED = "Could use some marshmallows.",
	SWEET_POTATO_PLANTED = "Looks like some sorta fancy potato.",
	SWEET_POTATO_SEEDS = "These would be of more use to me planted.",
	SWIMMINGHORROR = "I don't want nothin' to do with that, eh!",
	SWORDFISH = "That there's one pointy fish.",
	TELEPORTATO_SW_BASE = "Nothing some duct tape wouldn't fix.",
	TELEPORTATO_SW_BOX = "There must be a use for this, eh?",
	TELEPORTATO_SW_CRANK = "I should keep a hold of this.",
	TELEPORTATO_SW_POTATO = "Doesn't look anything like a potato. And I know potatoes.",
	TELEPORTATO_SW_RING = "Some sort of ring?",
	TELESCOPE = "Helps my eyesight, eh?",
	THATCHPACK = "Now I can carry more delicious wood.",
	TIDALPOOL = "Seems like a popular hangout spot for fishes.",
	TIDAL_PLANT = "No wood to be had from that thing.",
	TIGEREYE = "Don'tcha know it's rude to stare?",
	TIGERSHARK = "Might be cute if it didn't want to eat me.",
	TOUCAN = "That thing looks shifty.",
	TRAWLNET = "The fishes should swim right into this.",
	TRAWLNETDROPPED =
	{
		GENERIC = "Come to me, fishes!",
		SOON = "Nearly there!",
		SOONISH = "It's on its way down.",
	},
	TRIDENT = "Get a load of this massive fork, eh?!",
	TRINKET_IA_13 = "Is this safe for consumption?",
	TRINKET_IA_14 = "Is that my face?",
	TRINKET_IA_15 = "This guitar is tiny!",
	TRINKET_IA_16 = "It's just a little sheet of metal, eh?",
	TRINKET_IA_17 = "Not my size.",
	TRINKET_IA_18 = "It's broken.",
	TRINKET_IA_19 = "Who knows what this does?",
	TRINKET_IA_20 = "That's a little too fancy for my liking.",
	TRINKET_IA_21 = "That boat seems a little on the small side.",
	TRINKET_IA_22 = "Not very useful looking.",
	TRINKET_IA_23 = "I got no idea what that is.",
	FISH_TROPICAL = "Are you ready to become fish'n'chips?",
	TUNACAN = "Lucy'll open'er up.",
	TURBINE_BLADES = "Makes my head spin.",
	TURF_ASH = "Just some ground, eh?",
	TURF_BEACH = "Just some ground, eh?",
	TURF_JUNGLE = "Just some ground, eh?",
	TURF_MAGMAFIELD = "Just some ground, eh?",
	TURF_MEADOW = "Just some ground, eh?",
	TURF_SNAKESKIN = "Just some ground, eh?",
	TURF_SWAMP = "Just some ground, eh?",
	TURF_TIDALMARSH = "Just some ground, eh?",
	TURF_VOLCANO = "Just some ground, eh?",
	TWISTER_SEAL = "Cute little fella.",
	VENOMGLAND = "It smells kind of funny.",
	VINE = "Sigh. Not a tree.",
	VOLCANO = "That's a doozy!",
	VOLCANOSTAFF = "The power of the volcano is in my hand.",
	VOLCANO_ALTAR =
	{
		GENERIC = "Nothing to do aboot that.",
		OPEN = "I feel like it wants something from me.",
	},
	VOLCANO_ALTAR_BROKEN = "Thoroughly broke, that.",
	VOLCANO_ALTAR_TOWER = "That's a creepy-lookin' hunk of rock, that.",
	VOLCANO_EXIT = "Time to scoot.",
	VOLCANO_SHRUB = "Well, it's definitely not an evergreen.",
	WALLYINTRO_DEBRIS = "Where am I?",
	WALL_LIMESTONE = "That's a wall.",
	WALL_LIMESTONE_ITEM = "Why build walls when we could build bridges?",
	WATERYGRAVE = "I hope to never end up in one of those.",
	WHALE_BLUE = "Give'r!",
	WHALE_BUBBLES = "I know you're down there, buddy.",
	WHALE_CARCASS_BLUE = "That's a big guy, eh.",
	WHALE_CARCASS_WHITE = "Well, he's dead now.",
	WHALE_TRACK = "I'm hot on the trail.",
	WHALE_WHITE = "It's strong, and very free.",
	WILBUR_CROWN = "Luxurious.",
	WILBUR_UNLOCK = "I made a new buddy.",
	WILDBORE = "Looks like a total hoser.",
	WILDBOREHEAD = "Tough luck, buddy.",
	WILDBOREHOUSE = "Looks like a house fulla hosers.",
	BOAT_WOODLEGS = "Fancy, but it seems a little slow.",
	WOODLEGSHAT = "Could do with a pair of woolly earflaps.",
	SAIL_WOODLEGS = "Pretty stylish sail, that.",
	WOODLEGS_KEY1 = "What might this open?",
	WOODLEGS_KEY2 = "Key to what?",
	WOODLEGS_KEY3 = "I should hold on to this, eh?",
	SHIPWRECK = "A waste of good wood.",
	CALIFORNIAROLL = "I feel like a regular Vancouverite.",

	--- 5C DLC ------------------------------------------------------------------------------------------------

	BOAT_ENCRUSTED = "More \"crusty\" than \"encrusted\".",
	BABYOX = "He's all beard.",
	BALLPHINHOUSE = "Not quite as nice as a seaside cabin, but it'll do.",
	DORSALFIN = "Definitely not ballphin-free.",
	NUBBIN = "Uncomfortably smooth.",
	CORALLARVE = "What a tiny little hoser.",
	RAINBOWJELLYFISH = "Are you edible, little buddy?",
	RAINBOWJELLYFISH_PLANTED = "Floating along.",
	RAINBOWJELLYFISH_DEAD = "I don't think my little buddy's getting up anytime soon.",
	RAINBOWJELLYFISH_COOKED = "As good of eating as anything around here.",
	RAINBOWJELLYJERKY = "Wish it was salmon jerky.",
	WALL_ENFORCEDLIMESTONE = "Good looking sea wall.",
	WALL_ENFORCEDLIMESTONE_ITEM = "Just plop'r down wherever.",
	CROCODOG = "Those're some nasty chompers.",
	POISONCROCODOG = "Woah now, buddy.",
	WATERCROCODOG = "Really has that \"wet dog\" smell.",
	QUACKENBEAK = "A nightmare made real.",
	QUACKERINGRAM = "I've turned the seabird's evil against it!",

	--- DLC ------------------------------------------------------------------------------------------------    

	CAVIAR = "Whew, that's salty.",
	CORMORANT = "Filthy scoundrel.",

	PURPLE_GROUPER = "Looks like dinner.",
	PIERROT_FISH = "Always did like fishing.",
	NEON_QUATTRO = "Nice colours on that one.",

	PURPLE_GROUPER_COOKED = "Caught and cooked it myself.",
	PIERROT_FISH_COOKED = "Mmm, roast fish.",
	NEON_QUATTRO_COOKED = "Looks like I'll be eating for a day.",

	FISH_FARM = 
	{
		EMPTY = "Need to get ahold of fish eggs for that.",
		STOCKED = "Now we wait, eh, Lucy?",
		ONEFISH = "Hey Lucy, look. We've got a fish.",
		TWOFISH = "Those oughta cook up real good.",
		REDFISH = "More of 'em, eh?",
		BLUEFISH  = "Can't even count'em all anymore.",
	},
	
	ROE = "A handful of future fish, eh?",
	ROE_COOKED = "Better eat'em before they go bad.",
	
	SEA_YARD = 
	{
		ON = "Open for business.",
		OFF = "It's run clean dry, eh?",
		LOWFUEL = "Needs topping up.",
	},
	SEA_CHIMINEA =
	{
		EMBERS = "It's aboot to go right out.",
		GENERIC = "Lil water never stopped a woodsman.",
		HIGH = "Burning like mad!",
		LOW = "Gettin' a touch low.",
		NORMAL = "Steady going.",
		OUT = "Needs a good log.",
	}, 

	TAR = "Stickier than tree sap, that.",
	TAR_EXTRACTOR =
	{
		ON = "It's running like a dream.",
										
		OFF = "It's off.",
		LOWFUEL = "Fuel's low.",
								   
	},
	TAR_POOL = "Yep. There's tar down there.",

	TARLAMP = "Simple little light, that.",
	TARSUIT = "You do what you gotta to survive.",
	TAR_TRAP = "Slower going than Toronto traffic.",

	TROPICALBOUILLABAISSE = "It's a bit fishy.",
	
	SEA_LAB = "Doesn't seem like the best place, but here I am.",
	WATERCHEST = "How's it stay afloat when it's full?",
	QUACKENDRILL = "Could loosen some good tar with that right there.",
	HARPOON = "You could throw an axe just as good, hey?",
	MUSSEL_BED = "Not doin' me any good unplanted.",
},
}
