return {

ACTIONFAIL = {
	REPAIRBOAT =
	{
		GENERIC = "Nope. Can't fix ",
	},
	EMBARK =
	{
		INUSE = "Nope. Friends float now",
	},
	INSPECTBOAT =
	{
		INUSE = GLOBAL.STRINGS.CHARACTERS.WORMWOOD and GLOBAL.STRINGS.CHARACTERS.WORMWOOD.ACTIONFAIL.STORE.INUSE
	},
},

ANNOUNCE_MAGIC_FAIL = "Magic won't work",

ANNOUNCE_VOLCANO_ERUPT = "Woah. Earth Blood moving",
ANNOUNCE_TREASURE = "Hidden stuff nearby",
ANNOUNCE_CRAB_ESCAPE = "Run, Pinchy, run!",
ANNOUNCE_SHARX = "Swimmy Fins near!",
ANNOUNCE_MORETREASURE = "More hidden stuff near!",
ANNOUNCE_OTHER_WORLD_TREASURE = "Not from here",
ANNOUNCE_OTHER_WORLD_PLANT = "Won't grow here",
ANNOUNCE_MAPWRAP_WARN = "Oh. Can't see",
ANNOUNCE_MAPWRAP_LOSECONTROL = "Lost",
ANNOUNCE_MAPWRAP_RETURN = "Back again",

ANNOUNCE_MESSAGEBOTTLE =
{
	"Can't read",
},
ANNOUNCE_BOAT_DAMAGED = "Oh. Floater is wobbly",
ANNOUNCE_BOAT_SINKING = "Why sinking, Floater?",
ANNOUNCE_BOAT_SINKING_IMMINENT = "Sunk",
ANNOUNCE_TRAWL_FULL = "Full",
ANNOUNCE_WAVE_BOOST = "Whee!",
ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "Bubbles!",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Can't see bubbles",
ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "Can't see bubbles",


DESCRIBE = {

	SEAWEED_STALK = "Needs sea", --copied from the Wikia because I couldn't find it in the game files. -M

	POISONBALM = "Takes away sick",

	--some stray lines I found -M
	BIGFISHINGROD = "Stick for Glub Glubs",
	TROPICALFAN = "Makes wind",
	GHOST_SAILOR = "Floaty man!",
	PALMLEAF_UMBRELLA = "Rain Taker made of friend hair",
	PALMTREE =
	{
		BURNING = "Friend needs help!",
		BURNT = "Nooo!",
		CHOPPED = "Didn't want to",
		GENERIC = "Nice hair!",
	},
	SOLOFISH_DEAD = "Hello, Glub Glub",
	FISH_MED_COOKED = "For belly",
	SUNKBOAT = "Broken",
	--the big bulk of lines -M
	AERODYNAMICHAT = "Zoomie head thing",
	ARMOR_LIFEJACKET = "Water saver",
	ARMOR_SNAKESKIN = "Poor Squirmy",
	ARMOR_WINDBREAKER = "Cozy",
	ARMORLIMESTONE = "Heavy",
	ARMOROBSIDIAN = "Fire clothes",
	ARMORSEASHELL = "Sea clothes",
	BOAT_ARMOURED = "Lots of rocks",
	BABYOX = "Cute ear branches",
	BALLPHIN = "EEE! EEE!",
	BALLPHINPOD = "EEEs!",
	BAMBOOTREE = "Green sticks",
	BERRYBUSH2_SNAKE = "Something hiding?",--I don't think these should have diff name or examine text
	BERRYBUSH_SNAKE = "Something hiding?",--I don't think these should have diff name or examine text
	BIOLUMINESCENCE = "Wet lights",
	BLOWDART_POISON = "Patoo!",
	BOAT_LANTERN = "Floaty light",
	BOTTLELANTERN = "Light home",
	BURIEDTREASURE = "Stuff!",
	CANNONSHOT = "Pa-KOW!!",
	CAPTAINHAT = "Ahoy!",
	BOAT_CARGO = "Big Floater of friends",
	CHIMINEA = "Makes water fires",
	CIRCLINGSEAGULL = "Sea Tweeter",
	SAIL_CLOTH = "Woosh!",
	COCONUT =
	{
		GENERIC = "Ball of belly stuff",
		PLANTED = "Grow up strong!",
	},
	COCONUT_COOKED = "Warm",
	COFFEE = "Wheee!!!",
	COFFEEBEANS = "Zoomberries!",
	COFFEEBEANS_COOKED = "Smells good",
	COFFEEBUSH = "Zoomberry friend",
	CORAL = "Water rocks",
	ROCK_CORAL = "Rock party",
	CUTLASS = "Swooshy Stick",
	SWORDFISH_DEAD = "(sob)",
	DEPLETED_BAMBOOTREE = "Hurt?",
	DEPLETED_BUSH_VINE = "Hurt?",
	DOYDOY = "Odd Tweeter",
	DOYDOYBABY = "Odd Tweeter baby",
	DOYDOYEGG = "Odd Tweeter inside?",
	DOYDOYEGG_COOKED = "Fired egg",
	DOYDOYEGG_CRACKED = "Hatching?",
	DOYDOYFEATHER = "Odd Tweeter clothes",
	DOYDOYNEST = "Hello sticks!",
	DUBLOON = "Belly stuff? Nope",
	DUG_BAMBOOTREE = "Needs dirt",
	DUG_BERRYBUSH2 = "Needs dirt",
	DUG_BUSH_VINE = "Needs dirt",
	DUG_COFFEEBUSH = "Needs dirt",
	EARRING = "Doesn't fit",
	FABRIC = "Soft. Made from friends",
	SAIL_FEATHER = "Wind nabber",
	FIRERAIN = "Not good! Not good!",
	FIRERAINSHADOW = "Fire coming",
	FISHINHOLE = "Hello Glub Glubs!",
	GASHAT = "Head thing full of air",
	GOLDENMACHETE = "Pretty Slicer",
	ICEMAKER = "Cold Spitter",
	IRONWIND = "Air Machine",
	JELLYFISH = "Glub Glub Blob",
	JELLYFISH_DEAD = "Poor Blob",
	JELLYFISH_COOKED = "Blob hoops",
	JELLYFISH_PLANTED = "Glub Glub Blob",
	JELLYJERKY = "Hmm... bit chewy",
	JUNGLETREESEED =
	{
		GENERIC = "Cute little guy",
		PLANTED = "Grow well",
	},
	LAVAPOOL = "Fire water. Stay back!",
	LIMESTONENUGGET = "Where pretty parts go?",
	LIMPETS = "Rock Glub Glubs",
	LIMPETS_COOKED = "Goes in belly",
	LOBSTERHOLE = "Wet nest",
	BOAT_LOGRAFT = "Friend ship",
	MOSQUITO_POISON = "Bzzt that makes sick",
	MUSSEL = "Hiding",
	MUSSEL_COOKED = "Fire made it open",
	MUSSEL_STICK = "Stick is swimming!",
	OBSIDIAN = "Fire trapped in rock",
	OBSIDIAN_WORKBENCH = "Makes hard things",
	OBSIDIANAXE = "Hard Chopper",
	OBSIDIANCOCONADE = "Big Fireboomer!",
	OBSIDIANFIREPIT =
	{
		EMBERS = "Dying",
		GENERIC = "Not too close",
		HIGH = "Too high!",
		LOW = "Stay back",
		NORMAL = "Not too close",
		OUT = "Whew!",
	},
	OBSIDIANMACHETE = "Hard Slicer",
	SPEAR_OBSIDIAN = "Makes fire!",
	OBSIDIANSPEARGUN = "Hard Flying Stick",
	PACKIM = "Friend Tweeter",
	PACKIM_FISHBONE = "Friend Tweeter likes you!",
	PALMLEAF = "Wig from friend hair",
	PALMTREE_BURNT = "NOO!",
	PALMTREE_STUMP = "Sorry. Didn't want to",
	PARROT = "Pretty Tweeter!",
	PIRATEHAT = "Yo ho head thing",
	PIRATIHATITATOR = "Makes the Yo Ho magic",
	POISONHOLE = "Dirt is burping",
	BOAT_RAFT = "Greenstick ship",
	BOAT_ROW = "Push Pull Floater",
	SAIL_PALM = "Wind Nabber",
	SAND = "Dirt",
	SANDBAG = "Full of dirt",
	SANDBAG_ITEM = "Full of dirt",
	SANDDUNE = "Pile of dirt",
	SEAGULL = "Sea Tweeter",
	SEASACK = "Keeps belly stuff fresh",
	SEASHELL = "Head thing? Nope",
	SEASHELL_BEACHED = "No friends inside",
	SEATRAP = "Wet trap",
	SEAWEED = "Yum",
	SEAWEED_COOKED = "Ball of Sea Yum",
	SEAWEED_DRIED = "No more sea in Sea Yum",
	SEAWEED_PLANTED = "Nice day for a swim?",
	SHARX = "Fins?",
	SLOTMACHINE = "Luck Box",
	SNAKE = "Squirmy",
	SNAKE_FIRE = "Burny Squirmy",
	SNAKESKIN = "Squirmy clothes",
	SNAKESKINHAT = "Snazzy Squirmy head thing",
	SPEAR_POISON = "Sick Stick",
	SPEARGUN = "Patoo Machine",
	SPEARGUN_POISON = "Machine for Sick Patoo",
	STUNGRAY = "Smelly Glub Glub",
	SUPERTELESCOPE = "Can see home?",
	SWORDFISH = "Sharpnose Glub Glub",
	TELESCOPE = "Looky look",
	TIGERSHARK = "Mow Fin",
	TIGERSHARKSHADOW = "Hello? You hiding?",
	TOUCAN = "Big Nose Tweeter",
	TRAWLNET = "Glub Glub Snagger",
	TRAWLNETDROPPED = "Snagging...",
	TREEGUARD = "How doing, friend?",
	TRIDENT = "Three Stick Stick",
	TRINKET_IA_13 = "Psht",
	TRINKET_IA_14 = "Hello!... Hello?",
	TRINKET_IA_15 = "Plink Plink",
	TRINKET_IA_16 = "Name?",
	TRINKET_IA_17 = "(sniff, sniff) Whew-wee!",
	TRINKET_IA_18 = "Oh. Broken",
	TRINKET_IA_19 = "Hmm...",
	TURBINE_BLADES = "Wooshy",
	TURF_BEACH = "Sand",
	TURF_JUNGLE = "Dirt",
	VENOMGLAND = "For sickness",
	VINE = "String branches",
	VOLCANO = "Ka-BOOMER!",
	VOLCANO_ALTAR = "Hot water!",
	VOLCANO_ALTAR_BROKEN = "Broken",
	VOLCANO_EXIT = "Out",
	VOLCANOSTAFF = "Fire Rain Stick",
	WALL_LIMESTONE = "Big strong wall",
	WALL_LIMESTONE_ITEM = "Should put this somewhere",
	WHALE_BLUE = "Barrooooo!",
	WHALE_CARCASS_BLUE = "(sniff sniff) Smells good",
	WHALE_CARCASS_WHITE = "(sniff) Smells good",
	WHALE_WHITE = "Pale Barrooooo",
	CRABHOLE = "Anyone home?",
	CRAB =
	{
		GENERIC = "Pinchy",
		HIDDEN = "Come out and play?",
	},
	BERMUDATRIANGLE = "Zzzt Zoomer",
	BOATCANNON = "BOOM! BOOM! for Floater",
	BOATREPAIRKIT = "Fix it stuff",
	MACHETE = "Slicer. For friend haircuts",
	LUGGAGECHEST = "Stuff!",
	DRAGOON = "Hot Patuey!",
	ANTIVENOM = "Sick Fixer",
	BAMBOO = "Greenstick",
	FROG_POISON = "Sick Ribbit",
	OX = "Water Buddy",
	PEACOCK = "Lovely Tweeter",
	SEAGULL_WATER = "How's the water?",
	SNAKE_POISON = "Sick Squirmy",
	SOLOFISH = "Glub Glub Woofer",
	SPOILED_FISH = "Smells good. Mmmmm...",
	TWISTER = "Wooshy Wooshy",
	SAND_CASTLE =
	{
		GENERIC = "Made that",
		SAND = "Dirt",
	},
	SNAKEOIL = "Hmmm...",
	LOBSTER = "Snappy Glub Glub",
	MESSAGEBOTTLE = "Says something...",
	MESSAGEBOTTLEEMPTY = "Aw. Nothing inside",
	SHARK_FIN = "Water Slicer",
	VOLCANO_ALTAR =
	{
		GENERIC = "Hello?",
		OPEN = "Needs stuff for belly",
	},
	ELEPHANTCACTUS = "Pokey friend",
	ELEPHANTCACTUS_ACTIVE = "Friend? Ouch!",
	ELEPHANTCACTUS_STUMP = "Sorry!  (sob)",
	DOUBLE_UMBRELLAHAT = "Two Times Rain Taker",
	MUSSEL_FARM =
	{
		GENERIC = "Why you hiding?",
		STICKPLANTED = "Swimming stick",
	},
	WOODLEGS_CAGE = "Very locked",
	PIRATIHATITATOR =
	{
		GENERIC = "Makes magic stuff",
		BURNT = "Oh dear",
	},
	COFFEEBUSH =
	{
		BARREN = "Are you sick?",
		PICKED = "They'll grow back",
		WITHERED = "Needs ashes!",
		GENERIC = "Zoomberry friend",
	},
	DUG_ELEPHANTCACTUS = "Needs dirt",
	WHALE_BUBBLES = "Glub Glub or Barrooooo?",
	ARMORCACTUS = "Friend clothes",
	BAMBOOTREE =
	{
		BURNT = "NOOO!",
		CHOPPED = "Nice haircut!",
		GENERIC = "Greenstick friend",
	},
	BLOWDART_FLUP = "Eye patuey",
	BLUBBER = "Squishy",
	BLUBBERSUIT = "Still warm",
	BOAT = "Floater",
	BOAT_TORCH = "For dark times on floater",
	BRAINJELLYHAT = "Smart head thing",
	BUOY = "Water light",
	BUSH_VINE =
	{
		BURNT = "NOOOO!",
		CHOPPED = "Keep growing",
		GENERIC = "Hello Rope friend!",
	},
	COCONADE =
	{
		BURNING = "Burning!!!",
		GENERIC = "BOOMER!",
	},
	COCONUT_HALVED = "Stuff for belly",
	COFFEEBOT = "Zoomberry machine",
	CORAL_BRAIN = "Thinking...",
	CORAL_BRAIN_ROCK = "Thinky rock",
	CRATE = "Wood friends made a box!",
	DEPLETED_GRASS_WATER = "Sick",
	DRAGOONDEN = "Home of Fire Patuey",
	DRAGOONEGG = "Something inside...",
	DRAGOONHEART = "Still beating. Ba-dump Ba-dump",
	DRAGOONSPIT = "Patuey",
	FISH_MED = "Glub Glub",
	FISH_SMALL = "Wee Glub Glub",
	FISH_SMALL_COOKED = "Cute little belly stuff",
	FLAMEGEYSER = "Hot! Too hot!",
	FLOTSAM = "Swim, friends! Swim!",
	FLUP = "Peeper Glub Glub",
	-- FRESHFRUITCREPES = "Sweet belly stuff",
	GRASS_WATER = "How's the water?",
	HAIL_ICE = "Cold. Wet",
	HOME = "Hello? Anyone?",
	ICEMAKER =
	{
		HIGH = "Making lots of cold rocks",
		LOW = "Slow",
		NORMAL = "Cold Rock machine",
		OUT = "Needs food",
		VERYLOW = "It's getting hungry",
	},
	JUNGLETREE =
	{
		BURNING = "NOOO!!",
		BURNT = "(sob)",
		CHOPPED = "Oh. So sorry",
		GENERIC = "Sleeping friend",
	},
	KNIGHTBOAT = "Floating Neigh",
	KRAKEN = "Angry Beaker",
	KRAKENCHEST = "Stuff from the Beaker!",
	KRAKEN_TENTACLE = "Ocean arms!",
	LIMPETROCK =
	{
		GENERIC = "Rocks that grow stuff",
		PICKED = "Belly stuff already gone",
	},
	LIVINGJUNGLETREE = "Are you Friend?",
	LOBSTER_DEAD = "Oh. Belly stuff now",
	LOBSTER_DEAD_COOKED = "Why changed color?",
	MAGIC_SEAL = "Hello? Hello? Not talking",
	MAGMAROCK = "Hello, rocks!",
	MAGMAROCK_FULL = "Hello, rocks!",
	MAGMAROCK_GOLD = "Pretty rock inside",
	MAGMAROCK_GOLD_FULL = "Pretty rock inside",
	MANGROVETREE = "Hello! Friend?",
	MANGROVETREE_BURNT = "Fire kills everything",
	MARSH_PLANT_TROPICAL = "Little friend. Hello!",
	MERMFISHER = "Glub Glub Man",
	MERMHOUSE_FISHER = "Glub Glub Man home",
	MONKEYBALL = "Hee hee. Fun!",
	-- MONSTERTARTARE = "Nope",
	MOSQUITOSACK_YELLOW = "Bzzt bum",
	MUSSELBOUILLABAISE = "They look comfortable",
	MYSTERYMEAT = "Hmm...What is it?",
	NEEDLESPEAR = "Pokey friend bits",
	OCTOPUSCHEST = "Stuff from Big Arms guy!",
	OCTOPUSKING = "Big Arms guy",
	OXHAT = "Ear branches?",
	OX_FLUTE = "Toot! Toot!",
	OX_HORN = "Branches?",
	PALMLEAF_HUT = "Home made of friends",
	PARROT_PIRATE = "Arrg Tweeter",
	PEG_LEG = "Friend?",
	PIGTENT = "(sniff, sniff) Has Twirly Tail smell",
	PIKE_SKULL = "That poor stick",
	PIRATEGHOST = "Floaty man",
	PIRATEPACK = "Stuff!",
	PORTAL_SHIPWRECKED = "Oh. Broken",
	PRIMEAPE = "Big Cheeky",
	PRIMEAPEBARREL = "Cheeky home",
	RAWLING = "New fun friend!",
	REDBARREL = "BOOM Barrel",
	ROCK_CHARCOAL = "Burnt rock",
	ROCK_OBSIDIAN = "Hard",
	SAIL_STICK = "Blow Stick",
	SANDBAGSMALL = "Dirt Bag",
	SANDBAGSMALL_ITEM = "Dirt Bag",
	SHADOWSKITTISH_WATER = "Dark Creeper",
	SHARKITTEN = "Mow Glub Glub",
	SHARKITTENSPAWNER =
	{
		GENERIC = "Full",
		INACTIVE = "Mow?... Mow?",
	},
	SHARK_GILLS = "Glub Glub breather",
	SHARK_TEETHHAT = "Bitey Head Thing.",
	SHIPWRECKED_ENTRANCE = "Where to?",
	SHIPWRECKED_EXIT = "Goes where?",
	SNAKEDEN =
	{
		BURNT = "NOOOO!",
		CHOPPED = "You'll grow back soon!",
		GENERIC = "Hello Rope friend",
	},
	SAIL_SNAKESKIN = "Squirmy Wind Nabber",
	SPEAR_LAUNCHER = "Pokey Stick launcher",
	SUNKEN_BOAT =
	{
		ABANDONED = "Poor wood...",
		GENERIC = "Wood is drowning!",
	},
	SUNKEN_BOAT_BURNT = "(sob)",
	SUNKEN_BOAT_TRINKET_1 = "Pretty machine",
	SUNKEN_BOAT_TRINKET_2 = "Baby floater",
	SUNKEN_BOAT_TRINKET_3 = "Hmm...",
	SUNKEN_BOAT_TRINKET_4 = "Beep bwoop",
	SUNKEN_BOAT_TRINKET_5 = "(sniff, sniff) Whoo-wee!",
	SWEETPOTATOSOUFFLE = "Belly stuff",
	SWEET_POTATO = "Sweet belly stuff",
	SWEET_POTATO_COOKED = "Mmmm...",
	SWEET_POTATO_PLANTED = "Needs to grow",
	SWEET_POTATO_SEEDS = "Grows sweet belly stuff",
	SWIMMINGHORROR = "Yeep!",
	TELEPORTATO_SW_BASE = "Wood",
	TELEPORTATO_SW_BOX = "Box",
	TELEPORTATO_SW_CRANK = "Crank",
	TELEPORTATO_SW_POTATO = "Thing",
	TELEPORTATO_SW_RING = "Ring",
	THATCHPACK = "Keeps stuff",
	TIDALPOOL = "Home for Glub Glub",
	TIDAL_PLANT = "Looking good!",
	TIGEREYE = "(poke)",
	TRAWLNETDROPPED =
	{
		GENERIC = "Water stuff",
		SOON = "Have to wait",
		SOONISH = "Have to wait more",
	},
	TREASURECHEST_TRAP = "Hmm...",
	TRINKET_IA_20 = "Pretty machine",
	TRINKET_IA_21 = "Baby floater",
	TRINKET_IA_22 = "Hmm...",
	TRINKET_IA_23 = "Green stick glass",
	FISH_TROPICAL = "Pretty Glub Glub",
	TUNACAN = "Glub Glub inside?",
	TURF_ASH = "Burnt",
	TURF_MAGMAFIELD = "Burnt",
	TURF_MEADOW = "Dirt",
	TURF_SNAKESKIN = "Not dirt",
	TURF_TIDALMARSH = "Dirt!",
	TURF_VOLCANO = "Dirt",
	TWISTER_SEAL = "Those peepers...",
	VOLCANO_ALTAR_TOWER = "Big boomer!",
	VOLCANO_SHRUB = "Burnt (sob)",
	WALLYINTRO_DEBRIS = "Hello, wood!",
	WATERYGRAVE = "Wood drowning!",
	WHALE_TRACK = "Barrooooo?",
	WILBUR_CROWN = "Won't fit",
	WILBUR_UNLOCK = "Cheeky boss",
	WILDBORE = "Scary Twirly Tail",
	WILDBOREHEAD = "Yeep!",
	WILDBOREHOUSE = "Anyone home?",
	WIND_CONCH = "Blow rock",
	BOAT_WOODLEGS = "Arrg Floater",
	WOODLEGSHAT = "Arrg Head Thing",
	SAIL_WOODLEGS = "Arrg Wind Nabber",
	WOODLEGS_KEY1 = "Key",
	WOODLEGS_KEY2 = "Key. What for?",
	WOODLEGS_KEY3 = "Opens something",
	WRECK = "Save the wood!",
	CALIFORNIAROLL = "Belly stuff",
	-- BANANAPOP = "Frozen friend hair",
	BISQUE = "Swimmy belly stuff",
	-- CEVICHE = "Belly goop",
	SEAFOODGUMBO = "Mmm...",
	SURFNTURF = "Fills belly right up",
	SHARKFINSOUP = "Still swimming",
	LOBSTERDINNER = "Fancy belly stuff",
	LOBSTERBISQUE = "Still snappy?",
	JELLYOPOP = "Cold Glub Glub Blob",
	VOLCANO_SHRUB = "Oh, fire. Why?!",
	ROCK_OBSIDIAN = "Hard rock",
	ROCK_CHARCOAL = "Burnt rock",

	MUSSEL_BED = "Needs sea",
	SEAWEED_STALK = "Needs sea",
	HARPOON = "Throwy stick",

	BOAT_ENCRUSTED = "Heavy Floater",
	BABYOX = "Ear branches. Cute!",
	BALLPHINHOUSE = "EEE! Home",
	DORSALFIN = "EEE?... EEE?...",
	NUBBIN = "Cute baby Wet Rock",
	CORALLARVE = "Needs rock",
	RAINBOWJELLYFISH = "Pretty Glub Glub Blob",
	RAINBOWJELLYFISH_PLANTED = "Hello! Found you!",
	RAINBOWJELLYFISH_DEAD = "Not poofy anymore",
	RAINBOWJELLYFISH_COOKED = "Pretty rings",
	RAINBOWJELLYJERKY = "More chewy now",
	WALL_ENFORCEDLIMESTONE = "Wall. Strong wall",
	WALL_ENFORCEDLIMESTONE_ITEM = "Wall. Strong wall",
	CROCODOG = "GRRawr!",
	POISONCROCODOG = "Yellow GRRawr!",
	WATERCROCODOG = "Wet GRRawr!",
	QUACKENBEAK = "Beaky nose",
	QUACKERINGRAM = "Floater nose",
	CAVIAR = "Glub Glub babies trapped?",
	CORMORANT = "Floating Tweeter",
	PURPLE_GROUPER = "Purple Glub Glub",
	PIERROT_FISH = "Yellow Glub Glub",
	NEON_QUATTRO = "Big Lip Glub Glub",
	PURPLE_GROUPER_COOKED = "No more swimming",
	PIERROT_FISH_COOKED = "Glub Glub for belly",
	NEON_QUATTRO_COOKED = "Fins are yummy",
	FISH_FARM =
	{
		EMPTY = "Where glub glubs?",
		STOCKED = "Hello glub glubs!",
		ONEFISH = "Glub",
		TWOFISH = "Glub Glub",
		REDFISH = "Splishy",
		BLUEFISH  = "Splashy",
	},
	ROE = "Baby Glub Glubs",
	ROE_COOKED = "Tidy rows",
	SEA_YARD =
	{
		ON = "Fixing",
		OFF = "Not fixing",
		LOWFUEL = "Hungry?",
	},
	SEA_CHIMINEA =
	{
		EMBERS = "Dying",
		GENERIC = "Not too close",
		HIGH = "Too high!",
		LOW = "Stay back",
		NORMAL = "Not too close",
		OUT = "Whew",
	},
	TAR = "Dark Gloop",
	TAR_EXTRACTOR =
	{
		ON = "Getting Gloop",
		OFF = "Not getting Gloop",
		LOWFUEL = "Hungry?",
	},
	TAR_POOL = "Gloopy Puddle",
	TARLAMP = "Gloopy Light",
	TARSUIT = "Feelin' gloopy",
	TAR_TRAP = "Stuck",
	TROPICALBOUILLABAISSE = "Glub Glubs?",
	SEA_LAB = "Water things maker",
	WATERCHEST = "Swimming stuff!",
},

}
