
local IA_CONFIG = GLOBAL.rawget(GLOBAL, "IA_CONFIG")

if not IA_CONFIG then
	IA_CONFIG = {tuningmodifiers=true,bossbalance=true}
end

local multiplayer_armor_durability_modifier = IA_CONFIG.tuningmodifiers and .7 or 1
-- local TUNING = GLOBAL.TUNING
local seg_time = TUNING.SEG_TIME
local day_time = TUNING.DAY_SEGS_DEFAULT * seg_time
local dusk_time = TUNING.DUSK_SEGS_DEFAULT * seg_time
local night_time = TUNING.NIGHT_SEGS_DEFAULT * seg_time
local total_day_time = TUNING.TOTAL_DAY_TIME
local wilson_attack = TUNING.SPEAR_DAMAGE
local wilson_health = TUNING.WILSON_HEALTH

-- This excludes compulsory islands
-- SW uses 18 - 26 random islands
TUNING.MIN_ISLANDS = {
    tiny = 0,
    small = 2,
    medium = 3,
    default = 4,
    large = 5,
    huge = 6,
}
TUNING.MAX_ISLANDS = {
    tiny = 0,
    small = 3,
    medium = 5,
    default = 6,
    large = 8,
    huge = 10,
}
TUNING.MIN_ISLANDLINKS = {
    tiny = 1,
    small = 1,
    medium = 2,
    default = 3,
    large = 4,
    huge = 5,
}
TUNING.MAX_ISLANDLINKS = {
    tiny = 2,
    small = 2,
    medium = 3,
    default = 5,
    large = 6,
    huge = 7,
}

TUNING.WATERGEN =
{
	--Google 'Perlin noise' to see what is making, they are like cloud textures.
	--one noise map is made for coral, one for shipgraves and another for all other water
	noise_octave_water = 20,
	noise_octave_coral = 4,
	noise_octave_grave = 4,
	noise_persistence_water = 0.5,
	noise_persistance_coral = 0.5,
	noise_persistance_grave = 0.2,
	--high scale means more, smaller 'patches'
	noise_scale_water = 3,
	noise_scale_coral = 6,
	noise_scale_grave = 18,
	--noise maps will make values 0.0-1.0
	init_level_coral = 0.65, --greater then this = coral - increase to lower coral
	init_level_medium = 0.55, --greater than this = medium, increase for less medium 
	init_level_grave = 0.65, --greater then this = shipgraves - increase to lower shipgraves

	--after everything above is done it will take that and blur it

	--this is basically the blur strength
	sigma = 4.0,

	--before blurring, an elevation map is made from tiles using these values
	--1.0 = white (high), 0.0 = black (deep)
	ellevels =
	{
		[GROUND.OCEAN_CORAL] = 1.6, -- make shallow and medium around coral more likely
		[GROUND.MANGROVE] = 1.0,
		[GROUND.BEACH] = 1.0,
		[GROUND.OCEAN_SHALLOW] = 0.9,
		[GROUND.OCEAN_MEDIUM] = 0.4,
		[GROUND.OCEAN_DEEP] = 0.0,
		[GROUND.OCEAN_SHIPGRAVEYARD] = 0.0,
		[GROUND.IMPASSABLE] = 0.0,
	},

	--after blur, the current tiles get adjusted if they cross these elevation thresholds
	final_level_shallow = 0.35, --greater than this = shallow
	final_level_medium = 0.05, -- greater than this = medium, otherwise deep
}

TUNING.BERMUDA_AMOUNT = 12 --12 triangles make 6 pairs

TUNING.SAND_REGROW_TIME = total_day_time * 2
TUNING.SAND_REGROW_VARIANCE = total_day_time
TUNING.SAND_DEPLETE_CHANCE = 0.25

TUNING.SEASHELL_REGEN_TIME = total_day_time * 2 --So small for temp testing

TUNING.CORAL_MIN = 8

TUNING.BARREL_GUNPOWDER_RANGE = 6
TUNING.BARREL_GUNPOWDER_DAMAGE = 400

TUNING.SEAWEED_REGROW_TIME = total_day_time * 3
TUNING.SEAWEED_REGROW_VARIANCE = total_day_time * 2

TUNING.CRAB_RUN_SPEED = 5
TUNING.CRAB_WALK_SPEED = 2
TUNING.CRAB_HEALTH = 75
-- TUNING.CRAB_PERISH_TIME = total_day_time * 3 --unused and no idea what it is supposed to mean -M
TUNING.CRAB_RESPAWN_TIME = day_time*4
TUNING.MIN_CRAB_DEN_TRANSITION_TIME = day_time*1
TUNING.MAX_CRAB_DEN_TRANSITION_TIME = day_time*3

TUNING.MUSSEL_CATCH_TIME = {
    {base=1*total_day_time, random=0.5*total_day_time},   --tall to short
    {base=1*total_day_time, random=0.5*total_day_time},   --tall to short
    {base=1*total_day_time, random=0.5*total_day_time},   --tall to short
    {base=1*total_day_time, random=0.5*total_day_time},   --tall to short
    {base=1*total_day_time, random=0.5*total_day_time},   --tall to short
    {base=1*total_day_time, random=0.5*total_day_time},   --tall to short
}

TUNING.MUSSEL_CATCH_SMALL = 1
TUNING.MUSSEL_CATCH_MED = 3
TUNING.MUSSEL_CATCH_LARGE = 6

TUNING.LIMPET_REGROW_TIME =  total_day_time*3

TUNING.FISH_SCHOOL_MIN = 6
TUNING.FISH_SCHOOL_MAX = 10

-- TUNING.FISH_SCHOOL_ACTIVE_PERIOD = total_day_time --could make these a table,
-- TUNING.FISH_SCHOOL_INACTIVE_PERIOD = total_day_time --but as of now, the periods are calculated directly
TUNING.FISH_SCHOOL_RESPAWN = total_day_time / 2

TUNING.CORAL_BRAIN_REGROW = total_day_time * 20

TUNING.KNIGHTBOAT_HEALTH = IA_CONFIG.tuningmodifiers and 1500 or 500
TUNING.KNIGHTBOAT_WALKSPEED = 4 --runspeed 8 in SW
TUNING.KNIGHTBOAT_RANGE = 20 --can shoot about one tile farther if target leaves range
TUNING.KNIGHTBOAT_RADIUS = 1.5
TUNING.KNIGHTBOAT_DAMAGE = 50

TUNING.JELLYFISH_HEALTH = IA_CONFIG.tuningmodifiers and 70 or 50
TUNING.JELLYFISH_WALKSPEED = 2
TUNING.JELLYFISH_DAMAGE = 8

TUNING.RAINBOWJELLYFISH_WALKSPEED = 3
TUNING.RAINBOWJELLYFISH_LIGHT_RADIUS = 3
TUNING.RAINBOWJELLYFISH_LIGHT_DURATION = 90

TUNING.ELEPHANTCACTUS_DAMAGE = 20
TUNING.ELEPHANTCACTUS_HEALTH = 400
TUNING.ELEPHANTCACTUS_RANGE = 5
TUNING.ELEPHANTCACTUS_REGROW_PERIOD = 2

TUNING.TWISTER_CALM_WALK_SPEED = 5
TUNING.TWISTER_ANGRY_WALK_SPEED = 8
TUNING.TWISTER_RUN_SPEED = 13
TUNING.TWISTER_HEALTH = IA_CONFIG.tuningmodifiers and 6000 or 3000
TUNING.TWISTER_DAMAGE = 150
TUNING.TWISTER_VACUUM_DAMAGE = 500
TUNING.TWISTER_VACUUM_SANITY_HIT = -33
TUNING.TWISTER_VACUUM_DISTANCE = 15
TUNING.TWISTER_PLAYER_VACUUM_DISTANCE = 30
TUNING.TWISTER_ATTACK_PERIOD = 3
TUNING.TWISTER_MELEE_RANGE = 6
TUNING.TWISTER_ATTACK_RANGE = 6
TUNING.TWISTER_VACUUM_COOLDOWN = 20
TUNING.TWISTER_CHARGE_COOLDOWN = 10
TUNING.TWISTER_DAMAGE_PLAYER_PERCENT = IA_CONFIG.tuningmodifiers and .5 or 1

TUNING.TWISTER_VACUUM_ANTIC_TIME = 5
TUNING.TWISTER_VACUUM_TIME = 5

TUNING.TWISTER_WAVES_ANTIC_TIME = 7
TUNING.TWISTER_WAVES_TIME = 5

TUNING.TWISTER_SEAL_HEALTH = 10

TUNING.QUACKEN_HEALTH = IA_CONFIG.tuningmodifiers and 20000 or 1000
TUNING.QUACKEN_RANGE = 40 --can shoot two and half tiles farther if target leaves range
TUNING.QUACKEN_INK_DAMAGE = 50
TUNING.QUACKEN_INK_LINGERTIME = 30
TUNING.QUACKEN_MAXTENTACLES = 45
TUNING.QUACKEN_TENTACLE_DIST_MOD = 35 --how far away the tentacles are from the head
TUNING.QUACKEN_TENTACLE_HEALTH = 90
TUNING.QUACKEN_TENTACLE_DAMAGE = 50
TUNING.QUACKEN_TENTACLE_ATTACK_PERIOD = 6
TUNING.QUACKEN_TENTACLE_HIT_RANGE = 4
TUNING.QUACKEN_DAMAGE_PLAYER_PERCENT = IA_CONFIG.tuningmodifiers and .5 or 1

TUNING.FLUP_JUMPATTACK_RANGE = 4
TUNING.FLUP_MELEEATTACK_RANGE = 2
TUNING.FLUP_HIT_RANGE = 1.75
TUNING.FLUP_HEALTH = 100
TUNING.FLUP_ATTACK_PERIOD = 2
TUNING.FLUP_DAMAGE = 25
TUNING.FLUP_WALKSPEED = 4
TUNING.FLUP_RUNSPEED = 6.5

TUNING.MERM_FISHER_HEALTH = IA_CONFIG.tuningmodifiers and 300 or 150

TUNING.FISH_FARM_CYCLE_TIME_MIN = seg_time * 8
TUNING.FISH_FARM_CYCLE_TIME_MAX = seg_time * 12
TUNING.FISH_FARM_LURE_TEST_TIME = seg_time * 7

TUNING.PRIMEAPE_MELEE_DAMAGE = 20
TUNING.PRIMEAPE_HEALTH = 125
TUNING.PRIMEAPE_ATTACK_PERIOD = 2
TUNING.PRIMEAPE_MELEE_RANGE = 3
TUNING.PRIMEAPE_RANGED_RANGE = 17
TUNING.PRIMEAPE_MOVE_SPEED = 7
TUNING.PRIMEAPE_NIGHTMARE_CHASE_DIST = 40
TUNING.PRIMEAPE_LOYALTY_MAXTIME = 2.5*total_day_time
TUNING.PRIMEAPE_LOYALTY_PER_HUNGER = total_day_time/25
TUNING.PRIMEAPE_THROW_COOLDOWN = seg_time * 2
TUNING.PRIMEAPE_GOHOME_DELAY = seg_time * 9

TUNING.PRIMEAPE_POOP_PERIOD_MIN = 200
TUNING.PRIMEAPE_POOP_PERIOD_MAX = 400

TUNING.MONKEYBALL_USES = 10
TUNING.MONKEYBALL_PASS_TO_PLAYER_CHANCE = 0.5

TUNING.OX_HEALTH = IA_CONFIG.tuningmodifiers and 1000 or 500
TUNING.OX_DAMAGE = 34
TUNING.OX_MATING_SEASON_LENGTH = 3
TUNING.OX_MATING_SEASON_WAIT = 20
TUNING.OX_MATING_SEASON_BABYDELAY = total_day_time*0.5
TUNING.OX_MATING_SEASON_BABYDELAY_VARIANCE = total_day_time*0.5
TUNING.OX_TARGET_DIST = 5
TUNING.OX_CHASE_DIST = 30
TUNING.OX_FOLLOW_TIME = 30
TUNING.OX_WALK_SPEED = 1.5
TUNING.OX_RUN_SPEED = 7

TUNING.OX_POOP_PERIOD_MIN = 40
TUNING.OX_POOP_PERIOD_MAX = 60

TUNING.BABYOX_HEALTH = 300
TUNING.BABYOX_GROW_TIME = {base=3*day_time, random=2*day_time}

TUNING.OXHERD_RANGE = 40
TUNING.OXHERD_MAX_IN_RANGE = 20

-- Global doydoy controls
TUNING.DOYDOY_MAX_POPULATION = 20
TUNING.DOYDOY_SPAWN_TIMER = total_day_time * 2 -- try to mate some doydoy's after this amount of time + random variance
TUNING.DOYDOY_SPAWN_VARIANCE = total_day_time
TUNING.DOYDOY_MATING_RANGE = 15
TUNING.DOYDOY_MATING_DANCE_TIME = 3 -- how long should they dance?
TUNING.DOYDOY_MATING_DANCE_DIST = 3 -- how far away should they dance?
TUNING.DOYDOY_MATING_FEATHER_CHANCE = 0.2 -- feather drop chance after mating

-- doesn't really matter much for the herds
TUNING.DOYDOY_HERD_SIZE = 20
TUNING.DOYDOY_HERD_GATHER_RANGE = 40

TUNING.DOYDOY_EGG_HATCH_TIMER = total_day_time * 2
TUNING.DOYDOY_EGG_HATCH_VARIANCE = total_day_time/2

TUNING.DOYDOY_HEALTH = 100
TUNING.DOYDOY_WALK_SPEED = 2

TUNING.DOYDOY_BABY_HEALTH = 25
TUNING.DOYDOY_BABY_WALK_SPEED = 5
TUNING.DOYDOY_BABY_GROW_TIME = total_day_time * 2 --time to grow up

TUNING.DOYDOY_TEEN_HEALTH = 75
TUNING.DOYDOY_TEEN_WALK_SPEED = 1.5
TUNING.DOYDOY_TEEN_SCALE = 0.8
TUNING.DOYDOY_TEEN_GROW_TIME = total_day_time * 1 --time to grow up

-- When you kill doydoys
TUNING.DOYDOY_INNOCENCE_REALLY_BAD = 50 -- less than 2 doydoy's left, you get krampus
TUNING.DOYDOY_INNOCENCE_BAD = 10 -- less than or equal to 4 doydoy's left, that's BAD
TUNING.DOYDOY_INNOCENCE_LITTLE_BAD = 4 -- less than or equal to 10 doydoy's left, that's a LITTLE BAD
TUNING.DOYDOY_INNOCENCE_OK = 1 -- there are more than 10 doydoy's so that's OK

TUNING.PARROT_PIRATE_CHANCE = 0.1
TUNING.CORMORANT_CHANCE = 0.4

TUNING.LOBSTER_HEALTH = 25
TUNING.LOBSTER_WALK_SPEED = 1.5
TUNING.LOBSTER_RUN_SPEED = 4
TUNING.LOBSTER_RESPAWN_TIME = day_time*4
TUNING.LOBSTER_PERISH_TIME = total_day_time*2
TUNING.MIN_LOBSTER_HOME_TRANSITION_TIME = day_time*.5
TUNING.MAX_LOBSTER_HOME_TRANSITION_TIME = day_time*2

-- whale hunt stuff
TUNING.WHALEHUNT_ALTERNATE_BEAST_CHANCE_MIN = 0.05
TUNING.WHALEHUNT_ALTERNATE_BEAST_CHANCE_MAX = 0.33
TUNING.WHALEHUNT_SPAWN_DIST = 40
TUNING.WHALEHUNT_COOLDOWN = total_day_time*1.2
TUNING.WHALEHUNT_COOLDOWNDEVIATION = total_day_time*.3
TUNING.WHALEHUNT_MIN_TRACKS = 5
TUNING.WHALEHUNT_MAX_TRACKS = 7
TUNING.WHALEHUNT_RESET_TIME = 5

TUNING.WHALEHUNT_TRACK_ANGLE_DEVIATION = 160
TUNING.MIN_WHALEHUNT_DISTANCE = 300 -- you can't find a new beast without being at least this far from the last one --unused -M
TUNING.MAX_WHALEHUNT_DISTANCE = 200 -- if you get this far away from your dirt pile, you lose this hunt and get a new one
-- end whale hunt

TUNING.WHALE_BLUE_HEALTH = IA_CONFIG.tuningmodifiers and 1300 or 650
TUNING.WHALE_BLUE_DAMAGE = 50
TUNING.WHALE_BLUE_TARGET_DIST = 10
TUNING.WHALE_BLUE_CHASE_DIST = 30
TUNING.WHALE_BLUE_FOLLOW_TIME = 60
TUNING.WHALE_BLUE_SPEED = 4
TUNING.WHALE_BLUE_EXPLOSION_HACKS = 3
TUNING.WHALE_BLUE_EXPLOSION_DAMAGE = 25

TUNING.WHALE_WHITE_HEALTH = IA_CONFIG.tuningmodifiers and 1600 or 800
TUNING.WHALE_WHITE_DAMAGE = 75
TUNING.WHALE_WHITE_TARGET_DIST = 15
TUNING.WHALE_WHITE_CHASE_DIST = 40
TUNING.WHALE_WHITE_FOLLOW_TIME = 90
TUNING.WHALE_WHITE_SPEED = 5
TUNING.WHALE_WHITE_EXPLOSION_HACKS = 3
TUNING.WHALE_WHITE_EXPLOSION_DAMAGE = 50

TUNING.WHALE_ROT_TIME = {
    {base=2*day_time, random=0.5*day_time}, -- bloat1
    {base=2*day_time, random=0.5*day_time}, -- bloat2
    {base=1*day_time, random=0.5*day_time}, -- bloat3
}

TUNING.PALMTREEGUARD_MELEE = 5

TUNING.PALMTREEGUARD_HEALTH = IA_CONFIG.tuningmodifiers and 1000 or 750
TUNING.PALMTREEGUARD_DAMAGE = 150
TUNING.PALMTREEGUARD_COCONUT_DAMAGE = 50
TUNING.PALMTREEGUARD_ATTACK_PERIOD = 3
TUNING.PALMTREEGUARD_FLAMMABILITY = .333
TUNING.PALMTREEGUARD_DAMAGE_PLAYER_PERCENT = .33

TUNING.PALMTREEGUARD_MIN_DAY = 3
TUNING.PALMTREEGUARD_PERCENT_CHANCE = 1/75
TUNING.PALMTREEGUARD_MAXSPAWNDIST = 30

TUNING.PALMTREEGUARD_PINECONE_CHILL_CHANCE_CLOSE = .33 --unused, those are emitted by the pinecone -M
TUNING.PALMTREEGUARD_PINECONE_CHILL_CHANCE_FAR = .15 --unused, those are emitted by the pinecone -M
TUNING.PALMTREEGUARD_PINECONE_CHILL_CLOSE_RADIUS = 5 --unused, those are emitted by the pinecone -M
TUNING.PALMTREEGUARD_PINECONE_CHILL_RADIUS = 16 --unused, those are emitted by the pinecone -M
TUNING.PALMTREEGUARD_REAWAKEN_RADIUS = 20

TUNING.PALMTREEGUARD_BURN_TIME = 10
TUNING.PALMTREEGUARD_BURN_DAMAGE_PERCENT = 1/8

TUNING.JUNGLETREEGUARD_MELEE = 5

TUNING.JUNGLETREEGUARD_HEALTH = 750
TUNING.JUNGLETREEGUARD_DAMAGE = 150
TUNING.JUNGLETREEGUARD_ATTACK_PERIOD = 7
TUNING.JUNGLETREEGUARD_RANGED_ATTACK_PERIOD = 4
TUNING.JUNGLETREEGUARD_RANGED_ATTACK_CHANCE = 0.5
TUNING.JUNGLETREEGUARD_FLAMMABILITY = .333

-- cumulative on top of snake chance: X chance to throw snake, then Y chance for that snake to be poisonous
TUNING.JUNGLETREEGUARD_SNAKE_POISON_CHANCE = 0.25

TUNING.JUNGLETREEGUARD_MIN_DAY = 3
TUNING.JUNGLETREEGUARD_PERCENT_CHANCE = 1/75
TUNING.JUNGLETREEGUARD_MAXSPAWNDIST = 30

TUNING.JUNGLETREEGUARD_PINECONE_CHILL_CHANCE_CLOSE = .33
TUNING.JUNGLETREEGUARD_PINECONE_CHILL_CHANCE_FAR = .15
TUNING.JUNGLETREEGUARD_PINECONE_CHILL_CLOSE_RADIUS = 5
TUNING.JUNGLETREEGUARD_PINECONE_CHILL_RADIUS = 16
TUNING.JUNGLETREEGUARD_REAWAKEN_RADIUS = 20

TUNING.JUNGLETREEGUARD_BURN_TIME = 10
TUNING.JUNGLETREEGUARD_BURN_DAMAGE_PERCENT = 1/8

TUNING.SNAKE_SPEED = 3
TUNING.SNAKE_TARGET_DIST = 8
TUNING.SNAKE_KEEP_TARGET_DIST= 15
TUNING.SNAKE_HEALTH = 100
TUNING.SNAKE_DAMAGE = 10
TUNING.SNAKE_ATTACK_PERIOD = 3
TUNING.SNAKE_POISON_CHANCE = 0.25
TUNING.SNAKE_POISON_START_DAY = 3 -- the day that poison snakes have a chance to show up
TUNING.SNAKEDEN_REGEN_TIME = 3*seg_time
TUNING.SNAKEDEN_RELEASE_TIME = 5
TUNING.SNAKE_JUNGLETREE_CHANCE = 0.5 -- chance of a normal snake
TUNING.SNAKE_JUNGLETREE_POISON_CHANCE = 0.25 -- chance of a poison snake
TUNING.SNAKE_JUNGLETREE_AMOUNT_TALL = 2 -- num of times to try and spawn a snake from a tall tree
TUNING.SNAKE_JUNGLETREE_AMOUNT_MED = 1 -- num of times to try and spawn a snake from a normal tree
TUNING.SNAKE_JUNGLETREE_AMOUNT_SMALL = 1 -- num of times to try and spawn a snake from a small tree
TUNING.SNAKEDEN_MAX_SNAKES = 3
TUNING.SNAKEDEN_CHECK_DIST = 20
TUNING.SNAKEDEN_TRAP_DIST = 2

TUNING.STINKRAY_DAMAGE = 3
TUNING.STINKRAY_HEALTH = 50
TUNING.STINKRAY_ATTACK_PERIOD = 1
TUNING.STINKRAY_ATTACK_DIST = 1.5
TUNING.STINKRAY_TARGET_DIST = 6
TUNING.STINKRAY_WALK_SPEED = 8
TUNING.STINKRAY_CHASE_TIME = 3
TUNING.STINKRAY_CHASE_DIST = 10
TUNING.STINKRAY_SCALE_FLYING = 1.05
TUNING.STINKRAY_SCALE_WATER = 1.00

TUNING.SOLOFISH_WALK_SPEED = 5
TUNING.SOLOFISH_RUN_SPEED = 8
TUNING.SOLOFISH_HEALTH = 100
TUNING.SOLOFISH_WANDER_DIST = 10

TUNING.SWORDFISH_WALK_SPEED = 5
TUNING.SWORDFISH_RUN_SPEED = 8
TUNING.SWORDFISH_HEALTH = IA_CONFIG.tuningmodifiers and 500 or 200
TUNING.SWORDFISH_WANDER_DIST = 10
TUNING.SWORDFISH_TARGET_DIST =12
TUNING.SWORDFISH_DAMAGE = 30
TUNING.SWORDFISH_ATTACK_PERIOD = 2

TUNING.TIGERSHARK_WALK_SPEED = 8
TUNING.TIGERSHARK_RUN_SPEED = 12
TUNING.TIGERSHARK_HEALTH = IA_CONFIG.tuningmodifiers and 5000 or 2500
TUNING.TIGERSHARK_DAMAGE = 100
TUNING.TIGERSHARK_ATTACK_PERIOD = 3
TUNING.TIGERSHARK_ATTACK_RANGE = IA_CONFIG.bossbalance and 6 or 4
TUNING.TIGERSHARK_SPLASH_RADIUS = IA_CONFIG.bossbalance and 8 or 5
TUNING.TIGERSHARK_SPLASH_DAMAGE = 125
TUNING.TIGERSHARK_DAMAGE_PLAYER_PERCENT = IA_CONFIG.tuningmodifiers and .5 or 1

TUNING.SHARKITTEN_REGEN_PERIOD = total_day_time * 5
TUNING.SHARKITTEN_SPAWN_PERIOD = seg_time
TUNING.SHARKITTEN_SPEED = 10
TUNING.SHARKITTEN_HEALTH = IA_CONFIG.tuningmodifiers and 300 or 150

TUNING.SHARX_HEALTH = 150
TUNING.SHARX_DAMAGE = 20
TUNING.SHARX_ATTACK_PERIOD = 1.5
TUNING.SHARX_TARGET_DIST = 20
TUNING.SHARX_SPEED = 10

TUNING.BALLPHIN_TARGET_DIST = 8
TUNING.BALLPHIN_KEEP_TARGET_DIST = 15
TUNING.BALLPHIN_FRIEND_CHANCE = 0.01 -- chance that ballphins will spawn to assist you during a crocodog attack
TUNING.BALLPHIN_LOYALTY_PER_HUNGER = total_day_time/12
TUNING.BALLPHIN_LOYALTY_MAX_TIME = total_day_time * 3
TUNING.BALLPHIN_MIN_POOP_PERIOD = seg_time * .5
TUNING.BALLPHIN_DROWN_RESCUE_CHANCE = .8
TUNING.BALLPHIN_HEALTH = 200
TUNING.BALLPHIN_DAMAGE = 25
TUNING.BALLPHIN_ATTACK_PERIOD = 3

TUNING.DRAGOON_TARGET_DIST = 8
TUNING.DRAGOON_KEEP_TARGET_DIST = 10
TUNING.DRAGOON_WALK_SPEED = 3
TUNING.DRAGOON_RUN_SPEED = 15
TUNING.DRAGOON_HEALTH = IA_CONFIG.tuningmodifiers and 600 or 300
TUNING.DRAGOON_DAMAGE = 25
TUNING.DRAGOON_ATTACK_PERIOD = 1
TUNING.DRAGOON_CHASE_TIME = 3
TUNING.DRAGOONEGG_HATCH_TIMER = 120
TUNING.DRAGOONFIRE_FUEL_MAX = (night_time+dusk_time)
TUNING.DRAGOONFIRE_FUEL = 2

TUNING.PACKIM_DAMAGE = 33
TUNING.PACKIM_ATTACK_PERIOD = 3
TUNING.PACKIM_MAX_HUNGER = 150
TUNING.PACKIM_TRANSFORM_HUNGER = 120
TUNING.PACKIM_HUNGER_DRAIN = 0.1
TUNING.PACKIM_FIRE_DELAY_MIN = 5
TUNING.PACKIM_FIRE_DELAY_MAX = 10
TUNING.PACKIM_RESPAWN_TIME = total_day_time * 1
TUNING.PACKIM_WALKSPEED = 10

TUNING.WILDBOAR_ANNOYANCE_THRESHOLD = 4

TUNING.FLAMEGEYSER_SPAWN_CHANCE = 0.5
TUNING.FLAMEGEYSER_FUEL_MAX = seg_time*0.5
TUNING.FLAMEGEYSER_FUEL_START = seg_time*0.5
TUNING.FLAMEGEYSER_REIGNITE_TIME = seg_time
TUNING.FLAMEGEYSER_REIGNITE_TIME_VARIANCE = seg_time*0.5

TUNING.JUNGLETREE_CHOPS_SMALL = 5
TUNING.JUNGLETREE_CHOPS_NORMAL = 10
TUNING.JUNGLETREE_CHOPS_TALL = 15
TUNING.JUNGLETREE_WINDBLOWN_SPEED = 0.2
TUNING.JUNGLETREE_WINDBLOWN_FALL_CHANCE = 0.01

TUNING.JUNGLETREESEED_GROWTIME = {base=4.5*day_time, random=0.75*day_time}

TUNING.JUNGLETREE_GROW_TIME = {
    {base=4.5*day_time, random=0.5*day_time},   --tall to short
    {base=8*day_time, random=5*day_time},   --short to normal
    {base=8*day_time, random=5*day_time},   --normal to tall
}

TUNING.COCONUT_GROWTIME = {base=2.5*day_time, random=0.75*day_time}

TUNING.PALMTREE_GROW_TIME = {
    {base=1.5*day_time, random=0.5*day_time},   --tall to short
    {base=5*day_time, random=2*day_time},   --short to normal
    {base=5*day_time, random=2*day_time},   --normal to tall
}

TUNING.PALMTREE_CHOPS_SMALL = 5
TUNING.PALMTREE_CHOPS_NORMAL = 10
TUNING.PALMTREE_CHOPS_TALL = 15
TUNING.PALMTREE_COCONUT_CHANCE = 0.01

TUNING.MANGROVETREE_CHOPS_SMALL = 5
TUNING.MANGROVETREE_CHOPS_NORMAL = 10
TUNING.MANGROVETREE_CHOPS_TALL = 15
TUNING.MANGROVETREE_WINDBLOWN_SPEED = 0.2
TUNING.MANGROVETREE_WINDBLOWN_FALL_CHANCE = 0.01
TUNING.MANGROVETREE_GROW_TIME = {
    {base=4.5*day_time, random=0.5*day_time},   --tall to short
    {base=8*day_time, random=5*day_time},   --short to normal
    {base=8*day_time, random=5*day_time},   --normal to tall
    {base=2.5*day_time, random=0.75*day_time}   --stump to short
}

TUNING.EVERGREEN_WINDBLOWN_SPEED = 0.2
TUNING.EVERGREEN_WINDBLOWN_FALL_CHANCE = 0.01

TUNING.DECIDUOUS_WINDBLOWN_SPEED = 0.2
TUNING.DECIDUOUS_WINDBLOWN_FALL_CHANCE = 0.01

TUNING.LIVINGJUNGLETREE_CHANCE = .8
TUNING.LIVINGJUNGLETREE_WORK = 20

TUNING.POOP_WILBUR_FERTILIZE = day_time * 0.5
TUNING.POOP_WILBUR_SOILCYCLES = 5
TUNING.POOP_WILBUR_WITHEREDCYCLES = 0.5


TUNING.POOP_THROWN_DAMAGE = 10 --TODO unused in IA? maybe Wilbur stuff -M

TUNING.FLUP_DART_DAMAGE = 20
-- TUNING.FIRE_DART_DAMAGE = 5 --why would they do that? -M

TUNING.MACHETE_DAMAGE = wilson_attack * .88
TUNING.MACHETE_USES = 100

TUNING.CUTLASS_DAMAGE = wilson_attack*2
TUNING.CUTLASS_BONUS_DAMAGE = wilson_attack*1
TUNING.CUTLASS_USES = 150

TUNING.BLUBBERSUIT_PERISHTIME = total_day_time*8

TUNING.TARSUIT_PERISHTIME = total_day_time

TUNING.ARMORLIMESTONE = wilson_health * 5.5 * multiplayer_armor_durability_modifier
TUNING.ARMORLIMESTONE_ABSORPTION = 0.7
TUNING.ARMORLIMESTONE_SPEED_MULT = 0.9

TUNING.ARMORCACTUS = wilson_health * 3 * multiplayer_armor_durability_modifier
TUNING.ARMORCACTUS_ABSORPTION = .8
TUNING.ARMORCACTUS_DMG = wilson_attack/2

TUNING.WOODLEGS_BOATCANNON_DAMAGE = 50
TUNING.BOATCANNON_DAMAGE = 100
TUNING.BOATCANNON_RADIUS = 4
TUNING.BOATCANNON_BUILDINGDAMAGE = 10
TUNING.BOATCANNON_AMMO_COUNT = 15

TUNING.WINDBREAKER_PERISHTIME = total_day_time*10
TUNING.AERODYNAMICHAT_PERISHTIME = total_day_time*3
TUNING.AERODYNAMICHAT_SPEED_MULT = 1.25

TUNING.CAPTAINHAT_PERISHTIME = total_day_time*2
TUNING.CAPTAINHAT_DEPLETION_MULT = .5 --reduce durability usage of boat to x%
TUNING.PIRATEHAT_PERISHTIME = total_day_time*2
TUNING.GASHAT_PERISHTIME = total_day_time*4
TUNING.SHARK_HAT_PERISHTIME = total_day_time*9
TUNING.DOUBLE_UMBRELLA_PERISHTIME = total_day_time*12

TUNING.SPEAR_LAUNCHER_DAMAGE_MOD = 3
TUNING.SPEAR_LAUNCHER_ATTACK_RANGE = 12
TUNING.SPEAR_LAUNCHER_HIT_RANGE = 14
TUNING.SPEAR_LAUNCHER_USES = 8
TUNING.SPEAR_LAUNCHER_SPEAR_WEAR = 10

TUNING.ARMOR_SNAKESKIN_PERISHTIME = total_day_time*8 --was 10
TUNING.SNAKESKINHAT_PERISHTIME = total_day_time*8 --was 10

TUNING.TELESCOPE_USES = 5
TUNING.TELESCOPE_RANGE = 200
TUNING.TELESCOPE_ARC = 15 --degrees

TUNING.SUPERTELESCOPE_RANGE = 400

TUNING.WOODLEGSHAT_PERISHTIME = total_day_time*10
TUNING.WOODLEGSHAT_TREASURES = 6

TUNING.ARMOR_OXHAT = wilson_health * 4 * multiplayer_armor_durability_modifier
TUNING.ARMOR_OXHAT_ABSORPTION = .85

TUNING.ARMORSEASHELL = wilson_health * 5 * multiplayer_armor_durability_modifier
TUNING.ARMORSEASHELL_ABSORPTION = 0.75

TUNING.SAILSTICK_PERISHTIME = total_day_time * 10
TUNING.WIND_CONCH_USES = 10

-- cactus spike
TUNING.NEEDLESPEAR_DAMAGE = wilson_attack/2 -- wilson_attack is the default damage of a normal spear
TUNING.NEEDLESPEAR_USES = 5

TUNING.PEG_LEG_DAMAGE = wilson_attack -- wilson_attack is the default damage of a normal spear
TUNING.PEG_LEG_USES = 50

TUNING.OX_FLUTE_USES = 5

TUNING.HARPOON_DAMAGE = 200
TUNING.HARPOON_USES = 10
TUNING.HARPOON_RANGE = 6
TUNING.HARPOON_SPEED = 30

TUNING.VOLCANOSTAFF_USES = 5
TUNING.VOLCANOSTAFF_FIRERAIN_COUNT = 8
TUNING.VOLCANOSTAFF_FIRERAIN_RADIUS = 5
TUNING.VOLCANOSTAFF_FIRERAIN_DELAY = 0.5
TUNING.VOLCANOSTAFF_ASH_TIMER = 10.0

TUNING.VOLCANOBOOK_FIRERAIN_COUNT = 4
TUNING.VOLCANOBOOK_FIRERAIN_RADIUS = 5
TUNING.VOLCANOBOOK_FIRERAIN_DELAY = 0.5

TUNING.COCONADE_FUSE = 5
TUNING.COCONADE_DAMAGE = 250
TUNING.COCONADE_EXPLOSIONRANGE = 6
TUNING.COCONADE_BUILDINGDAMAGE = 10

TUNING.COCONADE_POISON_CLOUD_DURATION = 3 --unused in SW -M

TUNING.COCONADE_OBSIDIAN_DAMAGE = 350
TUNING.COCONADE_OBSIDIAN_EXPLOSIONRANGE = 9
TUNING.COCONADE_OBSIDIAN_BUILDINGDAMAGE = 15

TUNING.ICEMAKER_SPAWN_TIME = seg_time
TUNING.ICEMAKER_FUEL_MAX = seg_time * 3

TUNING.TRAWLNET_MAX_ITEMS = 9
TUNING.TRAWLNET_ITEM_DISTANCE = 100 --How far you have to travel to get another item
TUNING.TRAWLING_SPEED_MULT = 0.25 --This is actually speed reduction (speed = 1 - speed_mult)
TUNING.TRAWL_SINK_TIME = seg_time * 3

TUNING.LIMESTONEWALL_HEALTH = 500
TUNING.ENFORCEDLIMESTONEWALL_HEALTH = 750

TUNING.REPAIR_CORAL_WORK = 1
TUNING.REPAIR_CORAL_HEALTH = 25 --based on stone wall ratio
TUNING.REPAIR_LIMESTONE_WORK = 2
TUNING.REPAIR_LIMESTONE_HEALTH = 75 --based on stone wall ratio

TUNING.SANDCASTLE_PERISHTIME = total_day_time
TUNING.SANDCASTLE_RAIN_PERISH_RATE = 2
TUNING.SANDCASTLE_WIND_PERISH_RATE = 2

TUNING.SEAGULLSPAWNER_REGEN_PERIOD = 5
TUNING.SEAGULLSPAWNER_SPAWN_PERIOD = 3

TUNING.FISHING_CROCODOG_SPAWN_CHANCE = 0.2
TUNING.SHARKBAIT_CROCODOG_SPAWN_MULT = 0.005 --Chance of spawning a crocodog is this number multiplied by hunger value of the food
TUNING.SHARKBAIT_SHARX_CHANCE = 0.4 --Chance of getting sharx instead of a crocodog
TUNING.SHARKBAIT_SHARX_MIN = 2
TUNING.SHARKBAIT_SHARX_MAX = 4
TUNING.PUDDLE_CROCODOG_SPAWN_CHANCE = 0.2 --unused in SW -M

TUNING.GOLD_VALUES.IA_TRINKETS = {
    [13] = 6,
    [14] = 8,
    [15] = 6,
    [16] = 7,
    [17] = 6,
    [18] = 7,
    [19] = 6,
    [20] = 9,
    [21] = 9,
    [22] = 4,
    [23] = 10,
}
TUNING.GOLD_VALUES.SUNKEN_BOAT_TRINKETS = {
    2, 2, 7, 1, 4,
}

TUNING.DUBLOON_VALUES = {
    SEAFOOD = 1+3,
    RARESEAFOOD = 5+3,
    TRINKETS = {
        6+3,8+3,6+3,7+3,6+3,7+3,6+3,9+3,9+3,4+3,7+3,9+3, -- ROG trinkets 1-12
        -- DST trinkets 13+
        7+3, --Gnomette
        --TODO make up the rest
        -- 3, --[14] Leaky Teacup
        -- 4, --[15] White Bishop
        -- 4, --[16] Black Bishop
        -- 2, --[17] Bent Spork
        -- 6, --[18] Toy Trojan Horse
        -- 6, --[19] Unbalanced Top
        -- 7, --[20] Back Scratcher
        -- 5, --[21] Beaten Beater
        -- 4, --[22] Ball of Twine
        -- 3, --[23] Shoe Horn
        -- 8, --[24] Lucky Cat Jar
        -- 2, --[25] Air Unfreshener
        -- 9, --[26] Potato Cup
        -- 4, --[27] Wire Hanger
        -- 4, --[28] White Rook
        -- 4, --[29] Black Rook
        -- 4, --[30] White Knight
        -- 4, --[31] Black Knight
        -- 1, --[32] Crystal Ball
        -- 1, --[33] Spider Ring
        -- 1, --[34] Hand / Monkey Paw?
        -- 1, --[35] Empty Potion Bottle
        -- 1, --[36] Vampire Teeth
        -- 1, --[37] Wooden Stake
    },
    IA_TRINKETS = {
        [13] = 4+3,
        [14] = 4+3,
        [15] = 5+3,
        [16] = 2+3,
        [17] = 2+3,
        [18] = 8+3,
        [19] = 5+3,
        [20] = 8+3,
        [21] = 5+3,
        [22] = 2+3,
        [23] = 8+3,
    },
    SUNKEN_BOAT_TRINKETS = {
        3+3, 3+3, 6+3, 2+3, 5+3,
    },
}

--These are unused in SW -M
TUNING.FLOTSAM_REBATCH_TIME = total_day_time * 15
TUNING.FLOTSAM_INDIVIDUAL_TIME = total_day_time * 0.2
TUNING.FLOTSAM_BATCH_SIZE = { min = 2, max = 5 }
TUNING.FLOTSAM_SPAWN_RADIUS = 35
TUNING.FLOTSAM_DRIFT_SPEED = 1
TUNING.FLOTSAM_DECAY_TIME = total_day_time * 2

TUNING.DO_SEA_DAMAGE_TO_BOAT = true --This seems more like a debug value than tuning
TUNING.BOAT_HITFX_THRESHOLD = .08 --percent of health you need to lose to show the fx
TUNING.BOATCONTAINERCLOSEDIST = 4
TUNING.BOAT_REPAIR_KIT_HEALING = 100
TUNING.BOAT_REPAIR_KIT_USES = 3
TUNING.TRUSTY_TAPE_BOAT_HEALING = 50

TUNING.SUNKENPREFAB_REMOVE_TIME = total_day_time*2

TUNING.APPEASEMENT_TINY = 4
TUNING.APPEASEMENT_SMALL = 8
TUNING.APPEASEMENT_MEDIUM = 16
TUNING.APPEASEMENT_LARGE = 32
TUNING.APPEASEMENT_HUGE = 64

TUNING.WRATH_SMALL = -8
TUNING.WRATH_LARGE = -16
TUNING.WRATH_HUGE = -64

TUNING.VOLCANO_ALTAR_MAXAPPEASEMENTS = 5
TUNING.VOLCANO_ALTAR_DAMAGE = 6

TUNING.VOLCANO_FIRERAIN_WARNING = 2
TUNING.VOLCANO_FIRERAIN_RADIUS = 20
TUNING.VOLCANO_FIRERAIN_DAMAGE = 300
TUNING.VOLCANO_FIRERAIN_LAVA_CHANCE = 0.5
TUNING.VOLCANO_DRAGOONEGG_CHANCE = 0.25

TUNING.VOLCANO_EDGEDIST_MIN = 24
TUNING.VOLCANO_EDGEDIST_MAX = 128

TUNING.MAPWRAPPER_TELEPORT_RANGE = 4
TUNING.MAPWRAPPER_LOSECONTROL_RANGE = 8
TUNING.MAPWRAPPER_GAINCONTROL_RANGE = 8
TUNING.MAPWRAPPER_WARN_RANGE = 14
TUNING.MAPWRAPPER_EDGEFOG_RANGE = 6

-- meant for worldgen
TUNING.MAPEDGE_PADDING = TUNING.MAPWRAPPER_WARN_RANGE + 10

TUNING.TAR_EXTRACTOR_MAX_FUEL_TIME = total_day_time*2
TUNING.SEA_YARD_MAX_FUEL_TIME = seg_time*6

TUNING.TAR_TRAP_TIME = seg_time

TUNING.SLOWING_OBJECT_SLOWDOWN = 0.35

TUNING.CHIMINEA_FUEL_MAX = (night_time+dusk_time)*2
TUNING.CHIMINEA_FUEL_START = night_time+dusk_time
TUNING.CHIMINEA_BONUS_MULT = 2

TUNING.LAVAPOOL_FUEL_MAX = (night_time+dusk_time)
TUNING.LAVAPOOL_FUEL_START = (night_time+dusk_time)*.75


-- SW wither values --TODO unused in IA
TUNING.SW_MIN_PLANT_WITHER_TEMP = 60
TUNING.SW_MAX_PLANT_WITHER_TEMP = 75
TUNING.SW_MIN_PLANT_REJUVENATE_TEMP = 50
TUNING.SW_MAX_PLANT_REJUVENATE_TEMP = 55

TUNING.WALANI_HEALTH = 120
TUNING.WALANI_SANITY = 200
TUNING.WALANI_HUNGER = 200
TUNING.WALANI_SANITY_RATE_MODIFIER = -0.1
TUNING.WALANI_HUNGER_RATE_MODIFIER = 0.2

-- TUNING.WARLY_IA_HUNGER = 250
TUNING.WARLY_IA_HUNGER_RATE_MODIFIER = 1.33
TUNING.WARLY_IA_GOURMET_BONUS = 0.33 -- warly's chef meal bonus (normally added, but subtracted if harmful)
TUNING.WARLY_IA_GOURMET_PERISHTIME_MULT = 0.5
TUNING.WARLY_IA_MULT_COOKED = 0.9
TUNING.WARLY_IA_MULT_DRIED = 0.8
TUNING.WARLY_IA_MULT_RAW = 0.7
-- Same old is applied as a scale when eating the same thing in a row.
TUNING.WARLY_IA_SAME_OLD_MULTIPLIERS = {0.85, 0.7, 0.55}
TUNING.WARLY_IA_SAME_OLD_COOLDOWN = total_day_time * 1.5

TUNING.WILBUR_WALK_SPEED_PENALTY = -0.5
TUNING.WILBUR_SPEED_BONUS = 2.5
TUNING.WILBUR_TIME_TO_RUN = 3
TUNING.WILBUR_RUN_HUNGER_RATE_MULT = 0.33
TUNING.WILBUR_HEALTH = 125
TUNING.WILBUR_HUNGER = 175
TUNING.WILBUR_SANITY = 150

-- character vars
TUNING.WOODLEGS_WATER_SANITY = -0.08
TUNING.WOODLEGS_WALK_SPEED = 2
TUNING.WOODLEGS_RUN_SPEED = 4

-- standard poison vars
TUNING.VENOM_GLAND_DAMAGE = 75
TUNING.VENOM_GLAND_MIN_HEALTH = 5

TUNING.POISON_IMMUNE_DURATION = total_day_time -- the time you are immune to poison after taking antivenom
TUNING.POISON_DURATION = 120 -- the time in seconds that poison normally endures
TUNING.POISON_DAMAGE_PER_INTERVAL = 2 -- the amount of health damage poison causes per interval
TUNING.POISON_INTERVAL = 10 -- how frequently damage is applied

-- Total poison attack dmg = normal attack dmg + (POISON_DURATION/POISON_INTERVAL * POISON_DAMAGE_PER_INTERVAL)

TUNING.POISON_DAMAGE_RAMP = {--Elapsed time must be greater than the time value for the associated damage_scale/fxlevel value to be used
    -- (total damage after 3 days: 289.54)
    {time = 0.00*total_day_time, 	damage_scale = 0.50, 	interval_scale = 1.0, 	fxlevel = 1}, -- 48.00 DMG
    {time = 1.00*total_day_time, 	damage_scale = 0.75, 	interval_scale = 1.0, 	fxlevel = 1}, -- 54.00 DMG
    {time = 1.75*total_day_time, 	damage_scale = 1.00, 	interval_scale = 1.0, 	fxlevel = 2}, -- 48.00 DMG
    {time = 2.25*total_day_time, 	damage_scale = 1.25, 	interval_scale = 0.9, 	fxlevel = 2}, -- 60.00 DMG
    {time = 2.70*total_day_time, 	damage_scale = 1.50, 	interval_scale = 0.7, 	fxlevel = 3}, -- 41.14 DMG
    {time = 2.90*total_day_time, 	damage_scale = 2.00, 	interval_scale = 0.5, 	fxlevel = 4}, -- 38.40 DMG
}

TUNING.POISON_PERISH_PENALTY = 0.5

TUNING.POISON_HUNGER_DRAIN_MOD = 0.80 --adjusted for DST modifier lists -M
TUNING.POISON_DAMAGE_MOD = -0.25
TUNING.POISON_ATTACK_PERIOD_MOD = 0.25
TUNING.POISON_SPEED_MOD = 0.75

TUNING.AREA_POISONER_CHECK_INTERVAL = .5 -- How frequently an area poisoner checks for nearby entities to infect

TUNING.POISON_SANITY_SCALE = 0.05 -- sanity hit = poison hit * POISON_SANITY_SCALE  set to 0 to turn off


TUNING.FLOODING_WET_SEASON_PERCENT = 0.9 --percent into wet season floods start spawning --UNUSED
TUNING.FLOODING_SPAWN_TIME = 8 * total_day_time --time floods will spawn after start --UNUSED
TUNING.FLOODING_SPAWN_PER_SEC = 1.0/30.0 --flood spawns per second --UNUSED
TUNING.FLOODING_FLOOD_TIME = 2 * seg_time --seconds flood take to reach max size --UNUSED (floodlistener)
--FLOODING_FLOOD_RATE = 0.15 --rate floods increase in size, a scale of rain rate; smaller is slower
TUNING.FLOODING_DRY_TIME_VARIANCE = 2 * total_day_time --dry time is days left in green season plus this random variance --UNUSED (floodlistener)
--FLOODING_DRY_RATE = 0.4 --rate floods decrease in size, a scale of tempurature, and atmosphere moisture
TUNING.FLOODING_MAX_WATERLEVEL = 8 -- radius of max flood size in tiles --UNUSED (floodlistener)

--The following flood vars are actually used! *gasp*
TUNING.MAX_FLOOD_LEVEL = math.ceil(15 * (IA_CONFIG.scale_floodpuddles or 1))
TUNING.FLOOD_FREQUENCY = 0.005
TUNING.FLOOD_GROW_TIME = TUNING.SEG_TIME
--In SW, the puddles take exactly 25% of Dryseason to go from MAX_FLOOD_LEVEL to 0
--I've calculated this as the intended rate. 15 days * 25% / 15 levels = .25 daysPerLevel = 16 seg_time * .25 = 4 seg_timePerLevel  -M
TUNING.FLOOD_DRY_TIME = TUNING.SEG_TIME * 4


TUNING.WIND_GUSTSPEED_PEAK_MIN = 0.9
TUNING.WIND_GUSTSPEED_PEAK_MAX = 1.0
TUNING.WIND_GUSTRAMPUP_TIME = 0.5
TUNING.WIND_GUSTRAMPDOWN_TIME = 32.0/30.0 --Hacky, exact time of windshirl anim
TUNING.WIND_GUSTLENGTH_MIN = 7 -- measured in seconds
TUNING.WIND_GUSTLENGTH_MAX = 10
TUNING.WIND_GUSTDELAY_MIN = 15 -- time between gusts
TUNING.WIND_GUSTDELAY_MAX = 16

TUNING.HURRICANE_LENGTH_MIN = 1.5 * total_day_time --1 in SW
TUNING.HURRICANE_LENGTH_MAX = 2.5 * total_day_time
TUNING.HURRICANE_GUST_START_MOISTURE = 300 --how much atmo moisture after wind and before rain (rises by 3-4 per second)
TUNING.HURRICANE_GUST_END_MOISTURE = 300
TUNING.HURRICANE_PERCENT_WIND_START = 0.01
TUNING.HURRICANE_PERCENT_WIND_END = 0.8
TUNING.HURRICANE_PERCENT_HAIL_START = 0.25
TUNING.HURRICANE_PERCENT_HAIL_END = 0.95
TUNING.HURRICANE_LIGHTNING_STRIKE_CHANCE = 0.1
-- TUNING.HURRICANE_RAIN_SCALE = 1
-- TUNING.HURRICANE_DISSIPATION_SCALE = 1
TUNING.HURRICANE_HAIL_SCALE = 0.5
TUNING.HURRICANE_HAIL_DAMAGE = 1
TUNING.HURRICANE_HAIL_BREAK_CHANCE = 0.8

TUNING.HURRICANE_TEASE_LENGTH = 0.5 * total_day_time

TUNING.WINDBLOWN_DESTROY_DIST = 15 --distance from player wind blown prefabs can be destroyed, fall over, get picked, etc
TUNING.WINDBLOWN_SCALE_MIN = {
    LIGHT = 0.1,
    MEDIUM = 0.1,
    HEAVY = 0.01,
}
TUNING.WINDBLOWN_SCALE_MAX = {
    LIGHT = 1.0,
    MEDIUM = 0.25,
    HEAVY = 0.05,
}

TUNING.WINDPROOFNESS_SMALL = 0.2
TUNING.WINDPROOFNESS_SMALLMED = 0.35
TUNING.WINDPROOFNESS_MED = 0.5
TUNING.WINDPROOFNESS_LARGE = 0.7
TUNING.WINDPROOFNESS_HUGE = 0.9
TUNING.WINDPROOFNESS_ABSOLUTE = 1

TUNING.WIND_PUSH_MULTIPLIER = 0.4 --was 0.5
TUNING.FLOOD_SPEED_MULTIPLIER = 0.8 --was 0.6

TUNING.WIND_HUNGER_MULTIPLIER = 1.1 --unused in SW -M
TUNING.FLOOD_HUNGER_MULTIPLIER = 1.1

TUNING.PALMTREE_WINDBLOWN_SPEED = 0.2
TUNING.PALMTREE_WINDBLOWN_FALL_CHANCE = 0.01
TUNING.GRASS_WINDBLOWN_SPEED = 0.2
TUNING.GRASS_WINDBLOWN_FALL_CHANCE = 0.01
TUNING.SAPLING_WINDBLOWN_SPEED = 0.2
TUNING.SAPLING_WINDBLOWN_FALL_CHANCE = 0.1
TUNING.REEDS_WINDBLOWN_SPEED = 0.2
TUNING.REEDS_WINDBLOWN_FALL_CHANCE = 0.1
TUNING.BERRYBUSH_WINDBLOWN_SPEED = 0.2
TUNING.BERRYBUSH_WINDBLOWN_FALL_CHANCE = 0.01
TUNING.FLOWER_WINDBLOWN_SPEED = 0.2
TUNING.FLOWER_WINDBLOWN_FALL_CHANCE = 0.1
TUNING.PIGHOUSE_WINDBLOWN_SPEED = 0.2
TUNING.PIGHOUSE_WINDBLOWN_FALL_CHANCE = 0.1
TUNING.WALLHAY_WINDBLOWN_SPEED = 0.2
TUNING.WALLHAY_WINDBLOWN_DAMAGE_CHANCE = 0.9
TUNING.WALLHAY_WINDBLOWN_DAMAGE = wilson_attack
TUNING.WALLWOOD_WINDBLOWN_SPEED = 0.2
TUNING.WALLWOOD_WINDBLOWN_DAMAGE_CHANCE = 0.9
TUNING.WALLWOOD_WINDBLOWN_DAMAGE = 0.5*wilson_attack
TUNING.MUSSELFARM_WINDBLOWN_SPEED = 0.2
TUNING.MUSSELFARM_WINDBLOWN_FALL_CHANCE = 0.1
TUNING.SAND_WINDBLOWN_SPEED = 0.2
TUNING.SAND_WINDBLOWN_FALL_CHANCE = 0.1

TUNING.SANDBAG_HEALTH = 200

TUNING.FIRE_WINDBLOWN_SPEED = 0.7
TUNING.FIRE_BLOWOUT_CHANCE = 0.9 --chance a fire blows out when wind gets fast enough

TUNING.TREE_CREAK_WINDBLOWN_SPEED = 0.2 --creak sound (all trees)
TUNING.TREE_CREAK_RANGE = 16


TUNING.FISHING_ROD_BASE_NIBBLE_TIME = 5
TUNING.FISHING_ROD_NIBBLE_TIME_VARIANCE = 5
TUNING.FISHING_ROD_STEAL_CHANCE = 50

TUNING.BIG_FISHING_ROD_BASE_NIBBLE_TIME = 2 --For catching fish entities (fishing 2)
TUNING.BIG_FISHING_ROD_NIBBLE_TIME_VARIANCE = 2 --For catching fish entities (fishing 2)
TUNING.BIG_FISHING_ROD_STEAL_CHANCE = 0
TUNING.BIG_FISHING_ROD_USES = 14
TUNING.BIG_FISHING_ROD_MIN_WAIT_TIME = 4 --For pond fishing
TUNING.BIG_FISHING_ROD_MAX_WAIT_TIME = 20 --For pond fishing

TUNING.CAFFEINE_FOOD_BONUS_SPEED = 5 -- player base speed plus this
TUNING.HYDRO_FOOD_BONUS_DRY = 1
TUNING.HYDRO_FOOD_BONUS_DRY_RATE = 3 -- player base speed plus this
TUNING.HYDRO_FOOD_BONUS_SURF = 2 -- player base speed plus this
TUNING.HYDRO_FOOD_BONUS_COOL_RATE = 3 
TUNING.FOOD_SPEED_AVERAGE = 30 -- eating roasted coffee beans
TUNING.FOOD_SPEED_LONG = total_day_time / 2 -- drinking coffee

TUNING.VOLCANORIM_ACTIVE_HEAT = 70
TUNING.VOLCANORIM_ACTIVE_MULT = 32
TUNING.VOLCANORIM_LAVA_HEAT = 140
TUNING.VOLCANORIM_LAVA_MULT = 32
TUNING.VOLCANORIM_LAVA_DIST = 4

TUNING.CAMPFIRE_FLOOD_RATE = 100 --basically go out instantly (really, this should be handled more explicitly in code) -M
TUNING.CAMPFIRE_WIND_RATE = 10
TUNING.COLDFIRE_FLOOD_RATE = 100
TUNING.COLDFIRE_WIND_RATE = 10

TUNING.BAMBOO_HACKS = 6
TUNING.BAMBOO_REGROW_TIME = total_day_time*4
TUNING.BAMBOO_WINDBLOWN_SPEED = 0.2
TUNING.BAMBOO_WINDBLOWN_FALL_CHANCE = 0.1

TUNING.VINE_HACKS = 6
TUNING.VINE_REGROW_TIME = total_day_time*4
TUNING.VINE_WINDBLOWN_SPEED = 0.2
TUNING.VINE_WINDBLOWN_FALL_CHANCE = 0.1

TUNING.OBSIDIANTOOLFACTOR = 2.5
TUNING.OBSIDIANTOOL_WORK = 2.5

TUNING.OBSIDIAN_WEAPON_MAXCHARGES = 30
TUNING.OBSIDIAN_TOOL_MAXCHARGES = 75
TUNING.OBSIDIAN_TOOL_MAXHEAT = 60

-- Take a look at the regular FIREPIT values way above for reference
TUNING.OBSIDIANFIREPIT_BONUS_MULT = 3 -- regular firepit is 2
TUNING.OBSIDIANFIREPIT_RAIN_RATE = 2 -- regular rirepit is 2
TUNING.OBSIDIANFIREPIT_FUEL_MAX = (night_time+dusk_time)*3
TUNING.OBSIDIANFIREPIT_FUEL_START = night_time+dusk_time
TUNING.OBSIDIANFIRE_WINDBLOWN_SPEED = 0.7
TUNING.OBSIDIANFIRE_BLOWOUT_CHANCE = 0 -- never blow out
TUNING.OBSIDIANFIREPIT_FLOOD_RATE = 100

-- light radius stages for the level of the OBSIDIANFIREFIRE
TUNING.OBSIDIANLIGHT_RADIUS_1 = 4
TUNING.OBSIDIANLIGHT_RADIUS_2 = 8
TUNING.OBSIDIANLIGHT_RADIUS_3 = 12
TUNING.OBSIDIANLIGHT_RADIUS_4 = 14

TUNING.OBSIDIAN_SPEAR_DAMAGE = wilson_attack * 1.5 --Deals up to double damage with use.

TUNING.MAPREVEAL_NO_BONUS = 1
TUNING.MAPREVEAL_RAFT_BONUS = 1.5
TUNING.MAPREVEAL_LOGRAFT_BONUS = 1.5
TUNING.MAPREVEAL_ROWBOAT_BONUS = 2
TUNING.MAPREVEAL_CARGOBOAT_BONUS = 2.5
TUNING.MAPREVEAL_ARMOUREDBOAT_BONUS = 2.5
TUNING.MAPREVEAL_PIRATEHAT_BONUS = 3 * 4 --3*4 = 3 tiles
TUNING.MAPREVEAL_WOODLEGSBOAT_BONUS = 2
TUNING.MAPREVEAL_WORNPIRATEHAT_BONUS = 1.25
TUNING.MAPREVEAL_HURRICANE_PENALTY = 0.5

TUNING.WAVEBOOST = 5
TUNING.WAVE_BOOST_ANGLE_THRESHOLD = 90
TUNING.WAVE_LANE_SPACING = 12
TUNING.MAX_WAVES = 16 --in player radius

TUNING.WAVE_HIT_MOISTURE = 15
TUNING.WAVE_HIT_DAMAGE = 5

TUNING.ROGUEWAVE_HIT_MOISTURE = 25
TUNING.ROGUEWAVE_HIT_DAMAGE = 10
TUNING.ROGUEWAVE_SPEED_MULTIPLIER = 3

TUNING.RAFT_HEALTH = 150
TUNING.RAFT_PERISHTIME = total_day_time*2
TUNING.RAFT_SANITY_DRAIN = 0
TUNING.RAFT_SPEED = -1
TUNING.RAFT_HITMOISTURERATE = 1.25
TUNING.RAFT_LEAKING_HEALTH = 40

TUNING.LOGRAFT_HEALTH = 150
TUNING.LOGRAFT_PERISHTIME = total_day_time*2
TUNING.LOGRAFT_SANITY_DRAIN = 0
TUNING.LOGRAFT_SPEED = -2
TUNING.LOGRAFT_LEAKING_HEALTH = 40

TUNING.ROWBOAT_HEALTH = 250
TUNING.ROWBOAT_PERISHTIME = total_day_time*3
TUNING.ROWBOAT_SANITY_DRAIN = 0
TUNING.ROWBOAT_SPEED = 0
TUNING.ROWBOAT_LEAKING_HEALTH = 40

TUNING.CARGOBOAT_HEALTH = 300
TUNING.CARGOBOAT_PERISHTIME = total_day_time*3
TUNING.CARGOBOAT_SANITY_DRAIN = 0
TUNING.CARGOBOAT_SPEED = -1
TUNING.CARGOBOAT_LEAKING_HEALTH = 40

TUNING.ARMOUREDBOAT_HEALTH = 500
TUNING.ARMOUREDBOAT_PERISHTIME = total_day_time*4
TUNING.ARMOUREDBOAT_SANITY_DRAIN = 0
TUNING.ARMOUREDBOAT_SPEED = 0
TUNING.ARMOUREDBOAT_LEAKING_HEALTH = 40
TUNING.ARMOUREDBOAT_HIT_IMMUNITY = 3

TUNING.ENCRUSTEDBOAT_HEALTH = 800
TUNING.ENCRUSTEDBOAT_PERISHTIME = total_day_time*5
TUNING.ENCRUSTEDBOAT_SANITY_DRAIN = 0
TUNING.ENCRUSTEDBOAT_SPEED = -2
TUNING.ENCRUSTEDBOAT_WAVEBOOST = 20
TUNING.ENCRUSTEDBOAT_LEAKING_HEALTH = 40
TUNING.ENCRUSTEDBOAT_HIT_IMMUNITY = 4

TUNING.WOODLEGSBOAT_HEALTH = 500
TUNING.WOODLEGSBOAT_SANITY_DRAIN = 0
TUNING.WOODLEGSBOAT_SPEED = 0
TUNING.WOODLEGSBOAT_LEAKING_HEALTH = 40
TUNING.WOODLEGSBOAT_HIT_IMMUNITY = 2
TUNING.WOODLEGSBOAT_DAMAGESCALE = 0.5

TUNING.SURFBOARD_HEALTH = 100
TUNING.SURFBOARD_PERISHTIME = total_day_time*2
TUNING.SURFBOARD_SANITY_DRAIN = 0
TUNING.SURFBOARD_SPEED = 0.5
TUNING.SURFBOARD_WAVEBOOST = 25
TUNING.SURFBOARD_ROGUEBOOST = 35
TUNING.SURFBOARD_WAVESANITYBOOST = TUNING.SANITY_SUPERTINY
TUNING.SURFBOARD_HITMOISTURERATE = 1.5

TUNING.BOAT_TORCH_LIGHTTIME = night_time*1.75
TUNING.BOAT_LANTERN_LIGHTTIME = (night_time+dusk_time)*2.6
TUNING.BOTTLE_LANTERN_LIGHTTIME = (night_time+dusk_time)*2.6

TUNING.SAIL_PALM_SPEED_MULT = 1.2
TUNING.SAIL_PALM_ACCEL_MULT = 1
TUNING.SAIL_PALM_PERISH_TIME = total_day_time*2

TUNING.SAIL_CLOTH_SPEED_MULT = 1.3
TUNING.SAIL_CLOTH_ACCEL_MULT = 1.33
TUNING.SAIL_CLOTH_PERISH_TIME = total_day_time*3

TUNING.SAIL_SNAKESKIN_SPEED_MULT = 1.25
TUNING.SAIL_SNAKESKIN_ACCEL_MULT = 1.25
TUNING.SAIL_SNAKESKIN_PERISH_TIME = total_day_time*4

TUNING.SAIL_FEATHER_SPEED_MULT = 1.4
TUNING.SAIL_FEATHER_ACCEL_MULT = 1.5
TUNING.SAIL_FEATHER_PERISH_TIME = total_day_time*2

TUNING.IRON_WIND_SPEED_MULT =  1.5
TUNING.IRON_WIND_ACCEL_MULT = 2
TUNING.IRON_WIND_PERISH_TIME = total_day_time*4

TUNING.SAIL_WOODLEGS_ACCEL_MULT = 0.5

TUNING.QUACKERINGRAM_USE_COUNT = 15
TUNING.QUACKERINGRAM_DAMAGE = 150
TUNING.QUACKERINGRAM_TIMEOUT = 1

TUNING.MOISTURE_MAX_WETNESS = 100
TUNING.MOISTURE_MIN_WETNESS = 0
TUNING.MOISTURE_FLOOD_WETNESS = 50

TUNING.WATERVISUALSHIMMER = 1.0
TUNING.WATERVISUALCAMERA = 1.0